# CIFAR-10 structured slicing notebook

This notebook contains only the structured slicing experiments used here:

- DSWD
- HDSWD
- HSW_DSW
- HSW_HDSWD

No FEAT / CURV branches are used in this cleaned version.

In [1]:


try:
    import torch_fidelity
except ImportError:
    !pip install -q torch-fidelity
    import torch_fidelity

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.6/85.6 kB 5.7 MB/s eta 0:00:00

In [2]:
# @title
# Optional: install missing packages in Colab
import sys, subprocess, pkgutil

def ensure(pkg, pip_name=None):
    pip_name = pip_name or pkg
    if pkgutil.find_loader(pkg) is None:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", pip_name])

ensure("torchmetrics")
ensure("pandas")

/tmp/ipykernel_1981/3939325059.py:7: DeprecationWarning: 'pkgutil.find_loader' is deprecated and slated for removal in Python 3.14; use importlib.util.find_spec() instead
  if pkgutil.find_loader(pkg) is None:

In [3]:
# @title
# Mount Google Drive if running in Colab
import os

IN_COLAB = "google.colab" in str(get_ipython())
if IN_COLAB:
    from google.colab import drive
    drive.mount("/content/drive", force_remount=True)

Mounted at /content/drive

In [4]:
# @title
import os, json, csv, math, time, random, warnings, uuid
from dataclasses import dataclass, fields
from pathlib import Path
from typing import Dict, Tuple, List, Optional

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torchvision import datasets, transforms, utils as vutils

from torchmetrics.image.fid import FrechetInceptionDistance
from torchmetrics.image.kid import KernelInceptionDistance

import re
import shutil
import subprocess
from PIL import Image

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", device)

device: cuda

In [5]:
# @title

@dataclass
class TrainConfig:
    experiment_name: str = "cifar10_dsw_v2"
    run_tag: str = "bs512"

    output_root: str = "/content/runs_local"
    drive_output_root: str = "/content/drive/MyDrive/cifar10_dsw_runs" if os.path.exists("/content/drive/MyDrive") else "./runs_drive_backup"
    data_root: str = "/content/data"

    seeds: Tuple[int, ...] = (42,)
    modes: Tuple[str, ...] = (
        "DSWD",
        "HDSWD",
        "HSW_DSW",
        "HSW_HDSWD",
    )

    image_size: int = 64
    num_channels: int = 3
    latent_size: int = 100
    hidden_channels: int = 64

    batch_size: int = 512
    epochs: int = 100
    lr_g: float = 5e-4
    lr_d: float = 5e-4
    lr_t: float = 1e-4
    beta1: float = 0.5
    beta2: float = 0.999

    num_workers: int = 2
    pin_memory: bool = True

    num_projections: int = 256
    p: int = 2
    selector_steps: int = 1
    selector_hidden: int = 512

    use_diversity_reg: bool = True
    diversity_weight: float = 10.0

    sample_every: int = 5
    eval_every: int = 10
    final_eval_samples: int = 10000
    mid_eval_samples: int = 2000
    kid_subsets: int = 10
    kid_subset_size: int = 100

    resume_if_possible: bool = True
    autoskip_complete: bool = True

    drive_backup_every: int = 10
    drive_backup_on_eval: bool = True
    final_full_sync_to_drive: bool = True
    sync_history_on_backup: bool = True
    sync_eval_history_on_backup: bool = True
    sync_samples_on_backup: bool = False
    sync_eval_ckpts_on_backup: bool = False

    eval_backend: str = "torch_fidelity"
    fidelity_cache_root: str = "/content/fidelity_cache_local"
    fidelity_batch_size: int = 128

    enable_deterministic_algorithms: bool = True

    # hierarchical projector knobs
    h_num_base: int = 128
    h_num_bottleneck: int = 32
    h_base_rank: int = 512
    h_bottleneck_diversity_weight: float = 5.0
    h_mix_act: str = "linear"

    # hierarchical slicer knobs
    hsw_slicer_dims: Tuple[int, ...] = (512, 128)
    hsw_slicer_act: str = "linear"
    hsw_proj_rank: int = 0

    current_epoch: int = 0

cfg = TrainConfig()
print(cfg)

TrainConfig(experiment_name='cifar10_dsw_v2', run_tag='bs512', output_root='/content/runs_local', drive_output_root='/content/drive/MyDrive/cifar10_dsw_runs', data_root='/content/data', seeds=(42,), modes=('DSWD', 'HDSWD', 'HSW_DSW', 'HSW_HDSWD'), image_size=64, num_channels=3, latent_size=100, hidden_channels=64, batch_size=512, epochs=100, lr_g=0.0005, lr_d=0.0005, lr_t=0.0001, beta1=0.5, beta2=0.999, num_workers=2, pin_memory=True, num_projections=256, p=2, selector_steps=1, selector_hidden=512, use_diversity_reg=True, diversity_weight=10.0, sample_every=5, eval_every=10, final_eval_samples=10000, mid_eval_samples=2000, kid_subsets=10, kid_subset_size=100, resume_if_possible=True, autoskip_complete=True, drive_backup_every=10, drive_backup_on_eval=True, final_full_sync_to_drive=True, sync_history_on_backup=True, sync_eval_history_on_backup=True, sync_samples_on_backup=False, sync_eval_ckpts_on_backup=False, eval_backend='torch_fidelity', fidelity_cache_root='/content/fidelity_cache_local', fidelity_batch_size=128, enable_deterministic_algorithms=True, h_num_base=128, h_num_bottleneck=32, h_base_rank=512, h_bottleneck_diversity_weight=5.0, h_mix_act='linear', hsw_slicer_dims=(512, 128), hsw_slicer_act='linear', hsw_proj_rank=0, current_epoch=0)

In [6]:
# @title
def seed_everything(seed: int):
    os.environ["PYTHONHASHSEED"] = str(seed)
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True
    if getattr(cfg, "enable_deterministic_algorithms", True):
        torch.use_deterministic_algorithms(True)

def experiment_root(cfg: TrainConfig) -> Path:
    return Path(cfg.output_root) / cfg.experiment_name / cfg.run_tag

def drive_experiment_root(cfg: TrainConfig) -> Path:
    return Path(cfg.drive_output_root) / cfg.experiment_name / cfg.run_tag

def run_dir(cfg: TrainConfig, mode: str, seed: int) -> Path:
    return experiment_root(cfg) / mode / f"seed_{seed}"

def drive_run_dir(cfg: TrainConfig, mode: str, seed: int) -> Path:
    return drive_experiment_root(cfg) / mode / f"seed_{seed}"

def ensure_run_dirs(base: Path):
    for sub in ["checkpoints", "logs", "samples", "eval", "plots"]:
        (base / sub).mkdir(parents=True, exist_ok=True)

def complete_marker(base: Path) -> Path:
    return base / "COMPLETE_LOCAL"

def synced_complete_marker(base: Path) -> Path:
    return base / "COMPLETE_SYNCED"

def history_csv_path(base: Path) -> Path:
    return base / "logs" / "history.csv"

def eval_csv_path(base: Path) -> Path:
    return base / "logs" / "eval_history.csv"

def drive_last_ckpt_path(cfg: TrainConfig, mode: str, seed: int) -> Path:
    return drive_run_dir(cfg, mode, seed) / "checkpoints" / "last.pt"

def drive_best_ckpt_path(cfg: TrainConfig, mode: str, seed: int) -> Path:
    return drive_run_dir(cfg, mode, seed) / "checkpoints" / "best_fid.pt"

def drive_complete_marker(cfg: TrainConfig, mode: str, seed: int) -> Path:
    return drive_run_dir(cfg, mode, seed) / "COMPLETE"

def config_to_dict(cfg: TrainConfig) -> Dict:
    return dict(vars(cfg))

def append_row(csv_path: Path, row: Dict):
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    exists = csv_path.exists()
    with open(csv_path, "a", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(row.keys()))
        if not exists:
            writer.writeheader()
        writer.writerow(row)

def atomic_write_text(path: Path, text: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + f".tmp_{uuid.uuid4().hex}")
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(text)
    os.replace(tmp, path)

def save_json(path: Path, obj: Dict):
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + f".tmp_{uuid.uuid4().hex}")
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2)
    os.replace(tmp, path)

def atomic_torch_save(obj, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + f".tmp_{uuid.uuid4().hex}")
    torch.save(obj, tmp)
    os.replace(tmp, path)

def safe_copy_file(src: Path, dst: Path, verbose: bool = False) -> bool:
    try:
        if not src.exists():
            return False
        dst.parent.mkdir(parents=True, exist_ok=True)
        tmp = dst.with_name(dst.name + f".tmp_{uuid.uuid4().hex}")
        shutil.copy2(src, tmp)
        os.replace(tmp, dst)
        if verbose:
            print(f"[COPIED] {src} -> {dst}")
        return True
    except Exception as e:
        warnings.warn(f"Failed to copy {src} -> {dst}: {e}")
        return False

def sync_resume_artifacts_to_drive(cfg: TrainConfig, mode: str, seed: int, verbose: bool = True) -> bool:
    local_base = run_dir(cfg, mode, seed)
    drive_base = drive_run_dir(cfg, mode, seed)
    drive_base.mkdir(parents=True, exist_ok=True)

    relative_files = [
        Path("checkpoints/last.pt"),
        Path("checkpoints/best_fid.pt"),
        Path("eval/final_metrics.json"),
    ]
    if getattr(cfg, "sync_history_on_backup", True):
        relative_files.append(Path("logs/history.csv"))
    if getattr(cfg, "sync_eval_history_on_backup", True):
        relative_files.append(Path("logs/eval_history.csv"))
    if getattr(cfg, "sync_samples_on_backup", False):
        relative_files.extend([Path("samples/best_grid.png"), Path("samples/last_grid.png")])

    ok = True
    copied = 0
    for rel in relative_files:
        src = local_base / rel
        dst = drive_base / rel
        if src.exists():
            copied += int(safe_copy_file(src, dst, verbose=False))

    if getattr(cfg, "sync_eval_ckpts_on_backup", False):
        eval_ckpt_src = local_base / "checkpoints" / "eval_ckpts"
        eval_ckpt_dst = drive_base / "checkpoints" / "eval_ckpts"
        if eval_ckpt_src.exists():
            for src in sorted(eval_ckpt_src.glob("*.pt")):
                ok = safe_copy_file(src, eval_ckpt_dst / src.name, verbose=False) and ok
                copied += int(ok)

    if verbose:
        print(f"[SYNC-RESUME] {mode} seed={seed} copied sparse artifacts to {drive_base} (count={copied})")
    return ok

def sync_mode_to_drive(cfg: TrainConfig, mode: str, seed: int, verbose: bool = True) -> bool:
    local_base = run_dir(cfg, mode, seed)
    drive_base = drive_run_dir(cfg, mode, seed)
    drive_base.mkdir(parents=True, exist_ok=True)

    ok = True
    copied = 0
    for src in sorted(local_base.rglob("*")):
        if src.is_dir():
            continue
        rel = src.relative_to(local_base)
        dst = drive_base / rel
        ok = safe_copy_file(src, dst, verbose=False) and ok
        copied += int(src.exists())

    if ok:
        atomic_write_text(drive_complete_marker(cfg, mode, seed), "done")
    if verbose:
        status = "OK" if ok else "PARTIAL"
        print(f"[SYNC-FULL:{status}] {local_base} -> {drive_base} (files_seen={copied})")
    return ok

def hydrate_local_run_from_drive(cfg: TrainConfig, mode: str, seed: int):
    local_base = run_dir(cfg, mode, seed)
    drive_base = drive_run_dir(cfg, mode, seed)
    if local_base.exists():
        return
    if drive_base.exists():
        local_base.parent.mkdir(parents=True, exist_ok=True)
        shutil.copytree(drive_base, local_base, dirs_exist_ok=True)
        print(f"[HYDRATED] {drive_base} -> {local_base}")

def pick_existing_checkpoints(*paths: Path) -> List[Path]:
    existing = [p for p in paths if p.exists()]
    return sorted(existing, key=lambda p: p.stat().st_mtime, reverse=True)

def maybe_sync_completed_local_run(cfg: TrainConfig, mode: str, seed: int) -> bool:
    base = run_dir(cfg, mode, seed)
    if not complete_marker(base).exists():
        return False
    if synced_complete_marker(base).exists() or drive_complete_marker(cfg, mode, seed).exists():
        return True
    if not getattr(cfg, "final_full_sync_to_drive", True):
        return True
    print(f"[INFO] Found locally complete but unsynced run for {mode} seed={seed}; trying final sync only.")
    ok = sync_mode_to_drive(cfg, mode, seed, verbose=True)
    if ok:
        atomic_write_text(synced_complete_marker(base), "done")
    return ok

print("Local experiment root:", experiment_root(cfg))
print("Drive experiment root:", drive_experiment_root(cfg))

Local experiment root: /content/runs_local/cifar10_dsw_v2/bs512
Drive experiment root: /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512

In [7]:
# @title
# Data
def seed_worker(worker_id):
    worker_seed = torch.initial_seed() % 2**32
    np.random.seed(worker_seed)
    random.seed(worker_seed)

def build_loaders(cfg: TrainConfig, seed: int):
    g = torch.Generator()
    g.manual_seed(seed)

    tfm = transforms.Compose([
        transforms.Resize(cfg.image_size),
        transforms.ToTensor(),
        transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
    ])

    train_ds = datasets.CIFAR10(cfg.data_root, train=True, download=True, transform=tfm)
    test_ds = datasets.CIFAR10(cfg.data_root, train=False, download=True, transform=tfm)

    train_loader = DataLoader(
        train_ds,
        batch_size=cfg.batch_size,
        shuffle=True,
        num_workers=cfg.num_workers,
        pin_memory=cfg.pin_memory,
        drop_last=True,
        worker_init_fn=seed_worker,
        generator=g,
    )
    test_loader = DataLoader(
        test_ds,
        batch_size=cfg.batch_size,
        shuffle=False,
        num_workers=cfg.num_workers,
        pin_memory=cfg.pin_memory,
        drop_last=False,
        worker_init_fn=seed_worker,
        generator=g,
    )
    return train_loader, test_loader

train_loader, test_loader = build_loaders(cfg, cfg.seeds[0])
len(train_loader), len(test_loader)

100%|██████████| 170M/170M [00:18<00:00, 9.03MB/s]

(97, 20)

In [8]:
# @title
# Models (adapted from the DSW/DCGAN code)

class Generator(nn.Module):
    def __init__(self, latent_size=128, num_channels=3, hidden_channels=64):
        super().__init__()
        self.latent_size = latent_size
        self.main = nn.Sequential(
            nn.ConvTranspose2d(latent_size, hidden_channels * 8, 4, 1, 0, bias=False),
            nn.BatchNorm2d(hidden_channels * 8),
            nn.ReLU(True),

            nn.ConvTranspose2d(hidden_channels * 8, hidden_channels * 4, 4, 2, 1, bias=False),
            nn.BatchNorm2d(hidden_channels * 4),
            nn.ReLU(True),

            nn.ConvTranspose2d(hidden_channels * 4, hidden_channels * 2, 4, 2, 1, bias=False),
            nn.BatchNorm2d(hidden_channels * 2),
            nn.ReLU(True),

            nn.ConvTranspose2d(hidden_channels * 2, hidden_channels, 4, 2, 1, bias=False),
            nn.BatchNorm2d(hidden_channels),
            nn.ReLU(True),

            nn.ConvTranspose2d(hidden_channels, num_channels, 4, 2, 1, bias=False),
            nn.Tanh(),
        )

    def forward(self, z):
        return self.main(z.view(z.shape[0], self.latent_size, 1, 1))

class Discriminator(nn.Module):
    def __init__(self, latent_size=128, num_channels=3, hidden_channels=64):
        super().__init__()
        self.main1 = nn.Sequential(
            nn.Conv2d(num_channels, hidden_channels, 4, 2, 1, bias=False),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(hidden_channels, hidden_channels * 2, 4, 2, 1, bias=False),
            nn.BatchNorm2d(hidden_channels * 2),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(hidden_channels * 2, hidden_channels * 4, 4, 2, 1, bias=False),
            nn.BatchNorm2d(hidden_channels * 4),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(hidden_channels * 4, hidden_channels * 8, 4, 2, 1, bias=False),
            nn.BatchNorm2d(hidden_channels * 8),
            nn.Tanh(),
        )
        self.main2 = nn.Sequential(
            nn.Conv2d(hidden_channels * 8, 1, 4, 1, 0, bias=False),
            nn.Sigmoid(),
        )

    def forward(self, x):
        feat = self.main1(x)
        y = self.main2(feat).view(x.shape[0], -1)
        return y, feat.view(x.shape[0], -1)

def weights_init(m):
    classname = m.__class__.__name__
    if classname.find("Conv") != -1:
        nn.init.normal_(m.weight.data, 0.0, 0.02)
    elif classname.find("BatchNorm") != -1:
        nn.init.normal_(m.weight.data, 1.0, 0.02)
        nn.init.constant_(m.bias.data, 0)

G = Generator(cfg.latent_size, cfg.num_channels, cfg.hidden_channels).to(device)
D = Discriminator(cfg.latent_size, cfg.num_channels, cfg.hidden_channels).to(device)
G.apply(weights_init); D.apply(weights_init)
z = torch.randn(4, cfg.latent_size, device=device)
x = G(z)
y, feat = D(x)
print(x.shape, y.shape, feat.shape)

torch.Size([4, 3, 64, 64]) torch.Size([4, 1]) torch.Size([4, 8192])

In [9]:
# @title
def get_rng_state():
    state = {
        "python_random_state": random.getstate(),
        "numpy_random_state": np.random.get_state(),
        "torch_random_state": torch.get_rng_state(),
    }
    if torch.cuda.is_available():
        state["torch_cuda_random_state_all"] = torch.cuda.get_rng_state_all()
    return state


def set_rng_state(state):
    if state is None:
        return

    if "python_random_state" in state:
        random.setstate(state["python_random_state"])

    if "numpy_random_state" in state:
        np.random.set_state(state["numpy_random_state"])

    if "torch_random_state" in state:
        torch.set_rng_state(state["torch_random_state"])

    if torch.cuda.is_available() and "torch_cuda_random_state_all" in state:
        torch.cuda.set_rng_state_all(state["torch_cuda_random_state_all"])

In [10]:
# @title

# Projection nets

class TransformNet(nn.Module):
    def __init__(self, proj_dim: int):
        super().__init__()
        self.net = nn.Sequential(nn.Linear(proj_dim, proj_dim))

    def forward(self, theta, summary=None):
        out = self.net(theta)
        return F.normalize(out, dim=1)


class ConditionedTransformNet(nn.Module):
    def __init__(self, proj_dim: int, summary_dim: int, hidden: int = 512):
        super().__init__()
        self.theta_proj = nn.Linear(proj_dim, hidden)
        self.summary_proj = nn.Linear(summary_dim, hidden)
        self.out = nn.Linear(hidden, proj_dim)

    def forward(self, theta, summary):
        if summary.ndim == 1:
            summary = summary.unsqueeze(0)
        s = self.summary_proj(summary).expand(theta.shape[0], -1)
        h = torch.tanh(self.theta_proj(theta) + s)
        out = self.out(h)
        return F.normalize(out, dim=1)

In [11]:
# @title

# SW / DSW utilities

def sample_random_projections(num_projections: int, dim: int, device: torch.device):
    theta = torch.randn(num_projections, dim, device=device)
    return F.normalize(theta, dim=1)

def sliced_wasserstein_distance(x, y, theta, p=2):
    proj_x = x @ theta.t()
    proj_y = y @ theta.t()
    proj_x = torch.sort(proj_x, dim=0)[0]
    proj_y = torch.sort(proj_y, dim=0)[0]
    diff = (proj_x - proj_y).abs().pow(p)
    return diff.mean().pow(1.0 / p)

def selector_forward(mode: str, selector, theta0, real_feat, fake_feat, real_images=None, fake_images=None, cfg=None):
    return selector(theta0)

In [12]:
# @title

# Train steps

bce = nn.BCELoss()

def set_requires_grad(module: nn.Module, flag: bool):
    if module is None:
        return
    for p in module.parameters():
        p.requires_grad_(flag)

def train_discriminator_step(discriminator, optimizer_d, real_images, fake_images):
    real_label = torch.ones((real_images.shape[0], 1), device=real_images.device)
    fake_label = torch.zeros((real_images.shape[0], 1), device=real_images.device)

    optimizer_d.zero_grad(set_to_none=True)
    y_real, _ = discriminator(real_images.detach())
    loss_real = bce(y_real, real_label)

    y_fake, _ = discriminator(fake_images.detach())
    loss_fake = bce(y_fake, fake_label)

    loss_d = loss_real + loss_fake
    loss_d.backward()
    optimizer_d.step()

    return {
        "d_total": float(loss_d.item()),
        "d_real": float(loss_real.item()),
        "d_fake": float(loss_fake.item()),
    }

def optimize_selector(
    selector,
    opt_t,
    real_feat,
    fake_feat,
    num_projections,
    mode,
    cfg,
    real_images=None,
    fake_images=None,
    p=2,
):
    last = {
        "selector_obj": 0.0,
        "selector_entropy": 0.0,
        "selector_diversity": 0.0,
        "selector_mean_abs_cos": 0.0,
    }

    if selector is None or opt_t is None:
        return last

    for _ in range(cfg.selector_steps):
        theta0 = sample_random_projections(num_projections, real_feat.shape[1], real_feat.device)

        theta = selector_forward(
            mode,
            selector,
            theta0,
            real_feat,
            fake_feat,
            real_images=real_images,
            fake_images=fake_images,
            cfg=cfg,
        )

        sw = sliced_wasserstein_distance(real_feat.detach(), fake_feat.detach(), theta, p=p)

        div_val = torch.tensor(0.0, device=real_feat.device)
        if cfg.use_diversity_reg:
            div_val = direction_diversity_penalty(theta)
            selector_loss = -sw + cfg.diversity_weight * div_val
        else:
            selector_loss = -sw

        mac_val = mean_abs_offdiag_cos(theta)

        opt_t.zero_grad(set_to_none=True)
        selector_loss.backward()
        opt_t.step()

        last = {
            "selector_obj": float(sw.item()),
            "selector_entropy": 0.0,
            "selector_diversity": float(div_val.item()),
            "selector_mean_abs_cos": float(mac_val.item()),
        }

    return last

def generator_step(mode, generator, discriminator, selector, opt_g, real_images, cfg, opt_t=None):
    z = torch.randn(real_images.shape[0], cfg.latent_size, device=real_images.device)
    fake_images = generator(z)

    with torch.no_grad():
        _, real_feat = discriminator(real_images)

    set_requires_grad(discriminator, False)
    try:
        _, fake_feat = discriminator(fake_images)

        selector_stats = optimize_selector(
            selector,
            opt_t,
            real_feat,
            fake_feat,
            cfg.num_projections,
            mode=mode,
            cfg=cfg,
            real_images=real_images,
            fake_images=fake_images,
            p=cfg.p,
        )

        with torch.no_grad():
            theta0 = sample_random_projections(cfg.num_projections, real_feat.shape[1], real_feat.device)
            theta = selector_forward(
                mode,
                selector,
                theta0,
                real_feat,
                fake_feat,
                real_images=real_images,
                fake_images=fake_images,
                cfg=cfg,
            )

        sw = sliced_wasserstein_distance(real_feat, fake_feat, theta, p=cfg.p)
        g_total = sw

        opt_g.zero_grad(set_to_none=True)
        g_total.backward()
        opt_g.step()
    finally:
        set_requires_grad(discriminator, True)

    return fake_images.detach(), {
        "g_total": float(g_total.item()),
        "g_sw": float(sw.item()),
        "selector_obj": float(selector_stats["selector_obj"]),
        "selector_entropy": float(selector_stats["selector_entropy"]),
        "selector_diversity": float(selector_stats["selector_diversity"]),
        "selector_mean_abs_cos": float(selector_stats["selector_mean_abs_cos"]),
    }

In [13]:
# @title

# Checkpoint / resume
from pathlib import Path

def get_selector_arch(mode: str, cfg: TrainConfig, selector=None) -> str:
    cls_name = selector.__class__.__name__ if selector is not None else "None"
    if mode == "DSWD":
        return "DSWD::TransformNet::full"
    return f"{mode}::{cls_name}"

def make_models(cfg: TrainConfig, mode: str):
    G = Generator(cfg.latent_size, cfg.num_channels, cfg.hidden_channels).to(device)
    D = Discriminator(cfg.latent_size, cfg.num_channels, cfg.hidden_channels).to(device)
    G.apply(weights_init)
    D.apply(weights_init)

    feat_dim = cfg.hidden_channels * 8 * 4 * 4

    if mode == "DSWD":
        selector = TransformNet(feat_dim).to(device)
    else:
        raise ValueError(mode)

    opt_t = torch.optim.Adam(selector.parameters(), lr=cfg.lr_t, betas=(cfg.beta1, cfg.beta2))
    opt_g = torch.optim.Adam(G.parameters(), lr=cfg.lr_g, betas=(cfg.beta1, cfg.beta2))
    opt_d = torch.optim.Adam(D.parameters(), lr=cfg.lr_d, betas=(cfg.beta1, cfg.beta2))
    return G, D, selector, opt_g, opt_d, opt_t

def save_eval_checkpoint(
    run_dir,
    epoch,
    mode,
    seed,
    generator,
    discriminator,
    selector,
    opt_g=None,
    opt_d=None,
    opt_t=None,
    metrics=None,
    cfg=None,
):
    ckpt_dir = Path(run_dir) / "checkpoints" / "eval_ckpts"
    ckpt_dir.mkdir(parents=True, exist_ok=True)

    name = f"epoch_{epoch:04d}"
    if metrics is not None and "fid" in metrics:
        try:
            name += f"_fid_{float(metrics['fid']):.3f}"
        except Exception:
            pass
    path = ckpt_dir / f"{name}.pt"

    payload = {
        "run_schema_version": 2,
        "epoch": epoch,
        "mode": mode,
        "seed": seed,
        "selector_arch": get_selector_arch(mode, cfg, selector),
        "generator": generator.state_dict(),
        "discriminator": discriminator.state_dict(),
        "selector": selector.state_dict() if selector is not None else None,
        "metrics": metrics,
        "cfg": config_to_dict(cfg) if cfg is not None else None,
        "rng_state": get_rng_state(),
    }

    if opt_g is not None:
        payload["opt_g"] = opt_g.state_dict()
    if opt_d is not None:
        payload["opt_d"] = opt_d.state_dict()
    if opt_t is not None:
        payload["opt_t"] = opt_t.state_dict()

    atomic_torch_save(payload, path)
    return path

def save_checkpoint(path: Path, epoch: int, G, D, selector, opt_g, opt_d, opt_t, fixed_noise, best_fid, cfg, mode: str, seed: int):
    payload = {
        "run_schema_version": 2,
        "epoch": epoch,
        "mode": mode,
        "seed": seed,
        "selector_arch": get_selector_arch(mode, cfg, selector),
        "G": G.state_dict(),
        "D": D.state_dict(),
        "opt_g": opt_g.state_dict(),
        "opt_d": opt_d.state_dict(),
        "fixed_noise": fixed_noise.detach().cpu(),
        "best_fid": best_fid,
        "cfg": config_to_dict(cfg),
        "rng_state": get_rng_state(),
    }
    if selector is not None:
        payload["selector"] = selector.state_dict()
    if opt_t is not None:
        payload["opt_t"] = opt_t.state_dict()
    atomic_torch_save(payload, path)

def _load_checkpoint_into_objects(ckpt, G, D, selector, opt_g, opt_d, opt_t, expected_mode: str, expected_seed: int, expected_arch: str):
    ckpt_mode = ckpt.get("mode")
    if ckpt_mode is not None and ckpt_mode != expected_mode:
        raise RuntimeError(f"Checkpoint mode mismatch: expected {expected_mode}, got {ckpt_mode}")

    ckpt_seed = ckpt.get("seed")
    if ckpt_seed is not None and int(ckpt_seed) != int(expected_seed):
        raise RuntimeError(f"Checkpoint seed mismatch: expected {expected_seed}, got {ckpt_seed}")

    ckpt_arch = ckpt.get("selector_arch")
    if ckpt_arch is not None and ckpt_arch != expected_arch:
        raise RuntimeError(f"Selector architecture mismatch: expected {expected_arch}, got {ckpt_arch}")

    G.load_state_dict(ckpt["G"])
    D.load_state_dict(ckpt["D"])
    opt_g.load_state_dict(ckpt["opt_g"])
    opt_d.load_state_dict(ckpt["opt_d"])
    if selector is not None and "selector" in ckpt and ckpt["selector"] is not None:
        selector.load_state_dict(ckpt["selector"])
    if opt_t is not None and "opt_t" in ckpt:
        opt_t.load_state_dict(ckpt["opt_t"])

def maybe_resume(base: Path, cfg: TrainConfig, mode: str, seed: int):
    ensure_run_dirs(base)
    G, D, selector, opt_g, opt_d, opt_t = make_models(cfg, mode)
    fixed_noise = torch.randn(64, cfg.latent_size, device=device)
    best_fid = float("inf")
    start_epoch = 1

    expected_arch = get_selector_arch(mode, cfg, selector)
    local_last = base / "checkpoints" / "last.pt"
    drive_last = drive_last_ckpt_path(cfg, mode, seed)

    candidates = []
    for p in [local_last, drive_last]:
        if p.exists():
            candidates.append((p.stat().st_mtime, p))
    candidates.sort(reverse=True)

    loaded = False
    for _, ckpt_path in candidates:
        try:
            ckpt = torch.load(ckpt_path, map_location=device)
            _load_checkpoint_into_objects(ckpt, G, D, selector, opt_g, opt_d, opt_t, mode, seed, expected_arch)
            fixed_noise = ckpt.get("fixed_noise", fixed_noise).to(device)
            best_fid = float(ckpt.get("best_fid", best_fid))
            start_epoch = int(ckpt["epoch"]) + 1
            rng_state = ckpt.get("rng_state")
            if rng_state is not None:
                set_rng_state(rng_state)
            print(f"[INFO] Resumed {mode} seed={seed} from {ckpt_path} @ epoch {start_epoch-1}")
            loaded = True
            break
        except Exception as e:
            warnings.warn(f"Failed to resume from {ckpt_path}: {e}")

    if not loaded:
        print(f"[INFO] No valid checkpoint found for {mode} seed={seed}; starting fresh.")

    return G, D, selector, opt_g, opt_d, opt_t, fixed_noise, start_epoch, best_fid

In [14]:
# @title

# Evaluation and visualization

def save_uint8_tensor_dir(images_uint8: torch.Tensor, out_dir: Path, overwrite: bool = True):
    if overwrite and out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    for i, img in enumerate(images_uint8):
        arr = img.permute(1, 2, 0).cpu().numpy()   # CHW -> HWC
        Image.fromarray(arr).save(out_dir / f"{i:06d}.png")


def get_fidelity_cache_root(cfg: TrainConfig) -> Path:
    root = Path(cfg.fidelity_cache_root)
    root.mkdir(parents=True, exist_ok=True)
    return root

@torch.no_grad()
def save_sample_grid(path: Path, generator, fixed_noise):
    generator.eval()
    samples = generator(fixed_noise.to(device)).cpu()
    grid = vutils.make_grid(samples, nrow=8, normalize=True, value_range=(-1, 1))
    path.parent.mkdir(parents=True, exist_ok=True)
    vutils.save_image(grid, path)

@torch.no_grad()
def collect_generated_images(generator, total_samples: int, cfg: TrainConfig):
    generator.eval()
    batches = []
    remaining = total_samples
    while remaining > 0:
        bs = min(cfg.batch_size, remaining)
        z = torch.randn(bs, cfg.latent_size, device=device)
        fake = generator(z)
        fake_uint8 = ((fake.clamp(-1, 1) + 1) * 127.5).to(torch.uint8).cpu()
        batches.append(fake_uint8)
        remaining -= bs
    return torch.cat(batches, dim=0)

@torch.no_grad()
def collect_real_images(loader, total_samples: int):
    batches = []
    remaining = total_samples
    for x, _ in loader:
        take = min(x.shape[0], remaining)
        x = x[:take]
        x_uint8 = ((x.clamp(-1, 1) + 1) * 127.5).to(torch.uint8)
        batches.append(x_uint8.cpu())
        remaining -= take
        if remaining <= 0:
            break
    return torch.cat(batches, dim=0)

@torch.no_grad()
def evaluate_fid_kid(generator, real_loader, cfg: TrainConfig, total_samples: int, mode: str, seed: int):
    rng_state = get_rng_state()
    cache_root = get_fidelity_cache_root(cfg)
    fake_dir = None
    try:
        real = collect_real_images(real_loader, total_samples)
        fake = collect_generated_images(generator, total_samples, cfg)

        real_dir = cache_root / cfg.run_tag / "real_cache" / f"img_{cfg.image_size}" / f"n_{total_samples}"
        if not real_dir.exists() or len(list(real_dir.glob("*.png"))) != total_samples:
            save_uint8_tensor_dir(real, real_dir, overwrite=True)

        fake_dir = cache_root / cfg.run_tag / "_tmp_fake" / mode / f"seed_{seed}" / f"eval_{total_samples}_{uuid.uuid4().hex}"
        save_uint8_tensor_dir(fake, fake_dir, overwrite=True)

        metrics_dict = torch_fidelity.calculate_metrics(
            input1=str(fake_dir),
            input2=str(real_dir),
            cuda=(device.type == "cuda"),
            fid=True,
            kid=True,
            isc=False,
            prc=False,
            verbose=False,
            cache_root=str(cache_root),
            batch_size=cfg.fidelity_batch_size,
            samples_find_deep=False,
        )

        return {
            "fid": float(metrics_dict["frechet_inception_distance"]),
            "kid_mean": float(metrics_dict["kernel_inception_distance_mean"]),
            "kid_std": float(metrics_dict["kernel_inception_distance_std"]),
        }

    finally:
        if fake_dir is not None and fake_dir.exists():
            shutil.rmtree(fake_dir, ignore_errors=True)
        set_rng_state(rng_state)

def make_run_plots(base: Path):
    hist_path = history_csv_path(base)
    eval_path = eval_csv_path(base)
    if not hist_path.exists():
        return
    hist = pd.read_csv(hist_path)
    eval_df = pd.read_csv(eval_path) if eval_path.exists() else pd.DataFrame()

    plot_dir = base / "plots"
    plot_dir.mkdir(parents=True, exist_ok=True)

    plt.figure(figsize=(10, 5))
    for col in ["g_total", "g_sw", "d_total"]:
        if col in hist.columns:
            plt.plot(hist["epoch"], hist[col], label=col)
    plt.legend()
    plt.xlabel("epoch")
    plt.ylabel("loss")
    plt.title("Training losses")
    plt.tight_layout()
    plt.savefig(plot_dir / "losses.png", dpi=160)
    plt.close()

    if "selector_diversity" in hist.columns:
        plt.figure(figsize=(8, 4))
        plt.plot(hist["epoch"], hist["selector_diversity"], label="selector_diversity")
        plt.xlabel("epoch")
        plt.ylabel("penalty")
        plt.title("Selector diversity penalty")
        plt.tight_layout()
        plt.savefig(plot_dir / "selector_diversity.png", dpi=160)
        plt.close()

    if "selector_mean_abs_cos" in hist.columns:
        plt.figure(figsize=(8, 4))
        plt.plot(hist["epoch"], hist["selector_mean_abs_cos"], label="selector_mean_abs_cos")
        plt.xlabel("epoch")
        plt.ylabel("mean abs cos")
        plt.title("Mean absolute off-diagonal cosine")
        plt.tight_layout()
        plt.savefig(plot_dir / "selector_mean_abs_cos.png", dpi=160)
        plt.close()

    if len(eval_df) > 0:
        plt.figure(figsize=(10, 4))
        plt.subplot(1, 2, 1)
        plt.plot(eval_df["epoch"], eval_df["fid"], marker="o")
        plt.title("FID")
        plt.xlabel("epoch")
        plt.subplot(1, 2, 2)
        plt.plot(eval_df["epoch"], eval_df["kid_mean"], marker="o")
        plt.title("KID")
        plt.xlabel("epoch")
        plt.tight_layout()
        plt.savefig(plot_dir / "fid_kid.png", dpi=160)
        plt.close()

In [15]:
# @title
# Training loop

def sync_device(device):
    if device.type == "cuda":
        torch.cuda.synchronize(device)


def train_one_run(cfg: TrainConfig, mode: str, seed: int):
    hydrate_local_run_from_drive(cfg, mode, seed)

    base = run_dir(cfg, mode, seed)
    ensure_run_dirs(base)

    if cfg.autoskip_complete:
        if synced_complete_marker(base).exists() or drive_complete_marker(cfg, mode, seed).exists():
            print(f"[SKIP] {mode} seed={seed} already complete and synced.")
            return
        if maybe_sync_completed_local_run(cfg, mode, seed):
            print(f"[SKIP] {mode} seed={seed} already complete locally; sync handled.")
            return

    seed_everything(seed)
    train_loader, test_loader = build_loaders(cfg, seed)
    G, D, selector, opt_g, opt_d, opt_t, fixed_noise, start_epoch, best_fid = maybe_resume(base, cfg, mode, seed)
    last_eval_metrics = None
    last_eval_epoch = None

    for epoch in range(start_epoch, cfg.epochs + 1):
        cfg.current_epoch = epoch
        G.train()
        D.train()
        meter = {k: [] for k in [
            "g_total",
            "g_sw",
            "d_total",
            "d_real",
            "d_fake",
            "selector_obj",
            "selector_entropy",
            "selector_diversity",
            "selector_mean_abs_cos",
        ]}

        t0 = time.time()
        batch_compute_times = []
        total_samples_this_epoch = 0

        for real_images, _ in train_loader:
            real_images = real_images.to(device, non_blocking=True)
            bs = real_images.shape[0]
            total_samples_this_epoch += bs

            sync_device(device)
            batch_t0 = time.perf_counter()

            z = torch.randn(bs, cfg.latent_size, device=device)
            fake_images = G(z).detach()

            d_stats = train_discriminator_step(D, opt_d, real_images, fake_images)
            fake_images, g_stats = generator_step(mode, G, D, selector, opt_g, real_images, cfg, opt_t=opt_t)

            sync_device(device)
            batch_t1 = time.perf_counter()
            batch_compute_times.append(batch_t1 - batch_t0)

            for k, v in d_stats.items():
                meter[k].append(v)
            for k, v in g_stats.items():
                meter[k].append(v)

        epoch_time_sec = time.time() - t0
        total_compute_time = float(np.sum(batch_compute_times))
        avg_minibatch_compute_sec = float(np.mean(batch_compute_times))
        std_minibatch_compute_sec = float(np.std(batch_compute_times))
        throughput_img_per_sec = float(total_samples_this_epoch / total_compute_time) if total_compute_time > 0 else 0.0

        row = {
            "epoch": epoch,
            "seed": seed,
            "mode": mode,
            "time_sec": round(epoch_time_sec, 3),
            "num_minibatches": len(batch_compute_times),
            "total_compute_sec": total_compute_time,
            "avg_minibatch_compute_sec": avg_minibatch_compute_sec,
            "std_minibatch_compute_sec": std_minibatch_compute_sec,
            "throughput_img_per_sec": throughput_img_per_sec,
            "g_total": float(np.mean(meter["g_total"])),
            "g_sw": float(np.mean(meter["g_sw"])),
            "d_total": float(np.mean(meter["d_total"])),
            "d_real": float(np.mean(meter["d_real"])),
            "d_fake": float(np.mean(meter["d_fake"])),
            "selector_obj": float(np.mean(meter["selector_obj"])),
            "selector_entropy": float(np.mean(meter["selector_entropy"])),
            "selector_diversity": float(np.mean(meter["selector_diversity"])),
            "selector_mean_abs_cos": float(np.mean(meter["selector_mean_abs_cos"])),
            "lr_g": opt_g.param_groups[0]["lr"],
            "lr_d": opt_d.param_groups[0]["lr"],
            "lr_t": opt_t.param_groups[0]["lr"] if opt_t is not None else 0.0,
        }
        append_row(history_csv_path(base), row)

        print(
            f"[{mode}][seed={seed}] epoch {epoch:03d}/{cfg.epochs} | "
            f"G={row['g_total']:.4f} D={row['d_total']:.4f} SW={row['g_sw']:.4f} "
            f"DIV={row['selector_diversity']:.4f} "
            f"MAC={row['selector_mean_abs_cos']:.4f} "
            f"MB_time={row['avg_minibatch_compute_sec']:.4f}s"
        )

        if epoch % cfg.sample_every == 0 or epoch == 1:
            save_sample_grid(base / "samples" / f"epoch_{epoch:04d}.png", G, fixed_noise)

        if epoch % cfg.eval_every == 0 or epoch == cfg.epochs:
            metrics = evaluate_fid_kid(
                G,
                test_loader,
                cfg,
                total_samples=cfg.mid_eval_samples if epoch < cfg.epochs else cfg.final_eval_samples,
                mode=mode,
                seed=seed,
            )
            eval_row = {"epoch": epoch, "seed": seed, "mode": mode, **metrics}
            append_row(eval_csv_path(base), eval_row)
            print("  eval:", metrics)
            last_eval_metrics = metrics
            last_eval_epoch = epoch

            save_eval_checkpoint(
                run_dir=run_dir(cfg, mode, seed),
                epoch=epoch,
                mode=mode,
                seed=seed,
                generator=G,
                discriminator=D,
                selector=selector,
                opt_g=opt_g,
                opt_d=opt_d,
                opt_t=opt_t,
                metrics=metrics,
                cfg=cfg,
            )

            if metrics["fid"] < best_fid:
                best_fid = metrics["fid"]
                save_checkpoint(
                    base / "checkpoints" / "best_fid.pt",
                    epoch,
                    G,
                    D,
                    selector,
                    opt_g,
                    opt_d,
                    opt_t,
                    fixed_noise,
                    best_fid,
                    cfg,
                    mode=mode,
                    seed=seed,
                )
                save_sample_grid(base / "samples" / "best_grid.png", G, fixed_noise)

            if getattr(cfg, "drive_backup_on_eval", True):
                sync_resume_artifacts_to_drive(cfg, mode, seed, verbose=True)

        save_checkpoint(
            base / "checkpoints" / "last.pt",
            epoch,
            G,
            D,
            selector,
            opt_g,
            opt_d,
            opt_t,
            fixed_noise,
            best_fid,
            cfg,
            mode=mode,
            seed=seed,
        )

        if cfg.drive_backup_every > 0 and (epoch % cfg.drive_backup_every == 0):
            sync_resume_artifacts_to_drive(cfg, mode, seed, verbose=True)

    if last_eval_metrics is None or last_eval_epoch != cfg.epochs:
        final_metrics = evaluate_fid_kid(
            G,
            test_loader,
            cfg,
            total_samples=cfg.final_eval_samples,
            mode=mode,
            seed=seed,
        )
    else:
        final_metrics = last_eval_metrics

    save_json(base / "eval" / "final_metrics.json", final_metrics)
    save_sample_grid(base / "samples" / "last_grid.png", G, fixed_noise)
    make_run_plots(base)
    atomic_write_text(complete_marker(base), "done")

    sync_resume_artifacts_to_drive(cfg, mode, seed, verbose=True)
    if getattr(cfg, "final_full_sync_to_drive", True):
        ok = sync_mode_to_drive(cfg, mode, seed, verbose=True)
        if ok:
            atomic_write_text(synced_complete_marker(base), "done")
    else:
        atomic_write_text(synced_complete_marker(base), "done")
    try:
        from google.colab import drive
        drive.flush_and_unmount()
        print("[FLUSH] Drive 已强制同步完成")
    except Exception as e:
        print(f"[WARN] flush_and_unmount 失败: {e}")
    print(f"[DONE] {mode} seed={seed} -> {base}")


def train_all(cfg: TrainConfig):
    for mode in cfg.modes:
        for seed in cfg.seeds:
            train_one_run(cfg, mode, seed)

## Patch: structured modes with two switches

This cleaned notebook uses two structural switches:

- hierarchical slicer encoder: OFF / ON
- hierarchical projector: OFF / ON

This gives four modes:

- `DSWD`      : encoder OFF, projector OFF
- `HDSWD`     : encoder OFF, projector ON
- `HSW_DSW`   : encoder ON,  projector OFF
- `HSW_HDSWD` : encoder ON,  projector ON

In [16]:

# @title
# Unified structured selectors: optional hierarchical slicer + optional hierarchical projector

_old_get_selector_arch = get_selector_arch
_old_make_models = make_models
_old_selector_forward = selector_forward
_old_optimize_selector = optimize_selector
_old_generator_step = generator_step


class LowRankTransformNet(nn.Module):
    def __init__(self, proj_dim: int, rank: int = 512):
        super().__init__()
        self.rank = int(rank)
        self.down = nn.Linear(proj_dim, self.rank, bias=False)
        self.up = nn.Linear(self.rank, proj_dim, bias=False)
        nn.init.normal_(self.down.weight, mean=0.0, std=1.0 / math.sqrt(proj_dim))
        nn.init.zeros_(self.up.weight)

    def forward(self, theta):
        out = theta + self.up(self.down(theta))
        return F.normalize(out, dim=1)


class PersistentHierarchicalSlicer(nn.Module):
    def __init__(self, d: int, Ls, act: str = "linear"):
        super().__init__()
        self.d = int(d)
        self.Ls = list(Ls)
        self.act = str(act)

        modules = []
        for i, out_dim in enumerate(self.Ls):
            in_dim = self.d if i == 0 else self.Ls[i - 1]
            modules.append(nn.Linear(in_dim, out_dim, bias=False))
            if i != len(self.Ls) - 1 and self.act == "tanh":
                modules.append(nn.Tanh())
        self.U_list = nn.Sequential(*modules)
        self.reset()

    @property
    def out_dim(self):
        return int(self.Ls[-1])

    def forward(self, x):
        x = x.view(x.shape[0], -1)
        return self.U_list(x)

    def project_parameters(self):
        with torch.no_grad():
            for U in self.U_list.modules():
                if isinstance(U, nn.Linear):
                    U.weight.copy_(U.weight / U.weight.norm(dim=1, keepdim=True).clamp_min(1e-8))

    def reset(self):
        with torch.no_grad():
            for U in self.U_list.modules():
                if isinstance(U, nn.Linear):
                    nn.init.normal_(U.weight, mean=0.0, std=1.0)
            self.project_parameters()


class HierarchicalProjector(nn.Module):
    def __init__(
        self,
        proj_dim: int,
        num_base: int = 128,
        num_bottleneck: int = 32,
        num_final: int = 256,
        base_rank: int = 512,
        act: str = "linear",
    ):
        super().__init__()
        self.proj_dim = int(proj_dim)
        self.num_base = int(num_base)
        self.num_bottleneck = int(num_bottleneck)
        self.num_final = int(num_final)
        self.base_rank = int(base_rank)
        self.act = str(act)

        if self.base_rank > 0 and self.base_rank < proj_dim:
            self.base_transform = LowRankTransformNet(proj_dim, rank=self.base_rank)
        else:
            self.base_transform = TransformNet(proj_dim)

        self.mix1 = nn.Parameter(torch.randn(self.num_bottleneck, self.num_base) * 0.05)
        self.mix2 = nn.Parameter(torch.randn(self.num_final, self.num_bottleneck) * 0.05)

    def _row_normalize(self, W: torch.Tensor, eps: float = 1e-8):
        return W / W.norm(dim=1, keepdim=True).clamp_min(eps)

    def project_parameters(self):
        with torch.no_grad():
            self.mix1.copy_(self._row_normalize(self.mix1))
            self.mix2.copy_(self._row_normalize(self.mix2))

    def reset(self):
        with torch.no_grad():
            self.mix1.normal_(0.0, 0.05)
            self.mix2.normal_(0.0, 0.05)
            self.project_parameters()

    def forward(self, theta0: torch.Tensor, return_intermediates: bool = False):
        theta_base = self.base_transform(theta0)

        W1 = self._row_normalize(self.mix1)
        bottleneck = W1 @ theta_base
        if self.act == "tanh":
            bottleneck = torch.tanh(bottleneck)
        bottleneck = F.normalize(bottleneck, dim=1)

        W2 = self._row_normalize(self.mix2)
        theta_final = W2 @ bottleneck
        theta_final = F.normalize(theta_final, dim=1)

        if return_intermediates:
            return theta_final, bottleneck, theta_base
        return theta_final


class StructuredSelector(nn.Module):
    def __init__(
        self,
        feat_dim: int,
        use_hier_slicer: bool = False,
        use_hier_projector: bool = False,
        slicer_dims=None,
        slicer_act: str = "linear",
        proj_rank: int = 0,
        num_base: int = 128,
        num_bottleneck: int = 32,
        num_final: int = 256,
        base_rank: int = 512,
        hier_proj_act: str = "linear",
    ):
        super().__init__()
        self.feat_dim = int(feat_dim)
        self.use_hier_slicer = bool(use_hier_slicer)
        self.use_hier_projector = bool(use_hier_projector)

        self.slicer_dims = list(slicer_dims or [512, 128])
        self.slicer_act = str(slicer_act)
        self.proj_rank = int(proj_rank)

        self.num_base = int(num_base)
        self.num_bottleneck = int(num_bottleneck)
        self.num_final = int(num_final)
        self.base_rank = int(base_rank)
        self.hier_proj_act = str(hier_proj_act)

        if self.use_hier_slicer:
            self.slicer = PersistentHierarchicalSlicer(self.feat_dim, self.slicer_dims, act=self.slicer_act)
            rep_dim = self.slicer.out_dim
        else:
            self.slicer = None
            rep_dim = self.feat_dim
        self._rep_dim = int(rep_dim)

        if self.use_hier_projector:
            self.projector = HierarchicalProjector(
                proj_dim=self._rep_dim,
                num_base=self.num_base,
                num_bottleneck=self.num_bottleneck,
                num_final=self.num_final,
                base_rank=self.base_rank,
                act=self.hier_proj_act,
            )
        else:
            if self.proj_rank > 0 and self.proj_rank < self._rep_dim:
                self.projector = LowRankTransformNet(self._rep_dim, rank=self.proj_rank)
            else:
                self.projector = TransformNet(self._rep_dim)

    @property
    def rep_dim(self):
        return self._rep_dim

    def encode(self, feat: torch.Tensor):
        if self.slicer is None:
            return feat.view(feat.shape[0], -1)
        return self.slicer(feat)

    def project_theta(self, theta0: torch.Tensor, return_intermediates: bool = False):
        if self.use_hier_projector:
            return self.projector(theta0, return_intermediates=return_intermediates)
        theta = self.projector(theta0)
        if return_intermediates:
            return theta, None, None
        return theta

    def project_parameters(self):
        if self.slicer is not None and hasattr(self.slicer, "project_parameters"):
            self.slicer.project_parameters()
        if self.use_hier_projector and hasattr(self.projector, "project_parameters"):
            self.projector.project_parameters()

In [17]:

# @title
# Override selector architecture / model construction / selector forward for all structured modes

STRUCTURED_MODES = ("HDSWD", "HSW_DSW", "HSW_HDSWD")

def get_selector_arch(mode: str, cfg: TrainConfig, selector=None) -> str:
    cls_name = selector.__class__.__name__ if selector is not None else "None"
    if cls_name == "StructuredSelector":
        return (
            f"{mode}::StructuredSelector::"
            f"slicer_{getattr(selector, 'use_hier_slicer', False)}::"
            f"projector_{getattr(selector, 'use_hier_projector', False)}::"
            f"slicer_dims_{getattr(selector, 'slicer_dims', None)}::"
            f"slicer_act_{getattr(selector, 'slicer_act', None)}::"
            f"proj_rank_{getattr(selector, 'proj_rank', None)}::"
            f"num_base_{getattr(selector, 'num_base', None)}::"
            f"num_bottleneck_{getattr(selector, 'num_bottleneck', None)}::"
            f"num_final_{getattr(selector, 'num_final', None)}::"
            f"base_rank_{getattr(selector, 'base_rank', None)}::"
            f"hier_proj_act_{getattr(selector, 'hier_proj_act', None)}"
        )
    return _old_get_selector_arch(mode, cfg, selector)

def make_models(cfg: TrainConfig, mode: str):
    if mode not in STRUCTURED_MODES:
        return _old_make_models(cfg, mode)

    G = Generator(cfg.latent_size, cfg.num_channels, cfg.hidden_channels).to(device)
    D = Discriminator(cfg.latent_size, cfg.num_channels, cfg.hidden_channels).to(device)
    G.apply(weights_init)
    D.apply(weights_init)

    feat_dim = cfg.hidden_channels * 8 * 4 * 4

    use_hier_slicer = mode in ("HSW_DSW", "HSW_HDSWD")
    use_hier_projector = mode in ("HDSWD", "HSW_HDSWD")

    selector = StructuredSelector(
        feat_dim=feat_dim,
        use_hier_slicer=use_hier_slicer,
        use_hier_projector=use_hier_projector,
        slicer_dims=list(getattr(cfg, "hsw_slicer_dims", [512, 128])),
        slicer_act=str(getattr(cfg, "hsw_slicer_act", "linear")),
        proj_rank=int(getattr(cfg, "hsw_proj_rank", 0)),
        num_base=int(getattr(cfg, "h_num_base", 128)),
        num_bottleneck=int(getattr(cfg, "h_num_bottleneck", 32)),
        num_final=int(getattr(cfg, "num_projections", 256)),
        base_rank=int(getattr(cfg, "h_base_rank", 512)),
        hier_proj_act=str(getattr(cfg, "h_mix_act", "linear")),
    ).to(device)
    selector.project_parameters()

    opt_t = torch.optim.Adam(selector.parameters(), lr=cfg.lr_t, betas=(cfg.beta1, cfg.beta2))
    opt_g = torch.optim.Adam(G.parameters(), lr=cfg.lr_g, betas=(cfg.beta1, cfg.beta2))
    opt_d = torch.optim.Adam(D.parameters(), lr=cfg.lr_d, betas=(cfg.beta1, cfg.beta2))
    return G, D, selector, opt_g, opt_d, opt_t

def selector_forward(mode: str, selector, theta0, real_feat, fake_feat, real_images=None, fake_images=None, cfg=None):
    if mode in STRUCTURED_MODES and isinstance(selector, StructuredSelector):
        return selector.project_theta(theta0, return_intermediates=False)

    return _old_selector_forward(
        mode,
        selector,
        theta0,
        real_feat,
        fake_feat,
        real_images=real_images,
        fake_images=fake_images,
        cfg=cfg,
    )

In [18]:
# @title
# Override diversity penalty: off-diagonal only

def direction_diversity_penalty(theta: torch.Tensor, eps: float = 1e-8):
    theta = F.normalize(theta, dim=1)
    cos_mat = theta @ theta.t()
    L = theta.shape[0]
    eye = torch.eye(L, device=theta.device, dtype=theta.dtype)
    off = cos_mat - eye
    return off.pow(2).sum() / (L * (L - 1) + eps)

def mean_abs_offdiag_cos(theta: torch.Tensor):
    theta = F.normalize(theta, dim=1)
    gram = theta @ theta.t()
    L = theta.shape[0]
    eye = torch.eye(L, device=theta.device, dtype=theta.dtype)
    off = (gram - eye).abs()
    return off.sum() / (L * (L - 1) + 1e-8)

In [19]:

# @title
# Override selector optimization + generator step for all structured modes

def _structured_representation(selector, feat):
    return selector.encode(feat)

def _structured_theta0(selector, num_projections, device):
    if getattr(selector, "use_hier_projector", False):
        n = int(getattr(selector, "num_base", num_projections))
    else:
        n = int(num_projections)
    return sample_random_projections(n, selector.rep_dim, device)

def optimize_selector(
    selector,
    opt_t,
    real_feat,
    fake_feat,
    num_projections,
    mode,
    cfg,
    real_images=None,
    fake_images=None,
    p=2,
):
    if not (mode in STRUCTURED_MODES and isinstance(selector, StructuredSelector)):
        return _old_optimize_selector(
            selector,
            opt_t,
            real_feat,
            fake_feat,
            num_projections,
            mode,
            cfg,
            real_images=real_images,
            fake_images=fake_images,
            p=p,
        )

    last = {
        "selector_obj": 0.0,
        "selector_entropy": 0.0,
        "selector_diversity": 0.0,
        "selector_mean_abs_cos": 0.0,
    }

    div_w_final = float(getattr(cfg, "diversity_weight", 10.0))
    div_w_bottleneck = float(getattr(cfg, "h_bottleneck_diversity_weight", 5.0))

    for _ in range(cfg.selector_steps):
        Zx = _structured_representation(selector, real_feat.detach())
        Zy = _structured_representation(selector, fake_feat.detach())

        theta0 = _structured_theta0(selector, num_projections, real_feat.device)
        theta_final, bottleneck, theta_base = selector.project_theta(theta0, return_intermediates=True)

        sw = sliced_wasserstein_distance(Zx, Zy, theta_final, p=p)

        div_final = torch.tensor(0.0, device=real_feat.device)
        div_bottleneck = torch.tensor(0.0, device=real_feat.device)

        if cfg.use_diversity_reg:
            div_final = direction_diversity_penalty(theta_final)
            if bottleneck is not None:
                div_bottleneck = direction_diversity_penalty(bottleneck)
            selector_loss = -sw + div_w_final * div_final + div_w_bottleneck * div_bottleneck
        else:
            selector_loss = -sw

        mac_val = mean_abs_offdiag_cos(theta_final)

        opt_t.zero_grad(set_to_none=True)
        selector_loss.backward()
        opt_t.step()

        if hasattr(selector, "project_parameters"):
            selector.project_parameters()

        last = {
            "selector_obj": float(sw.item()),
            "selector_entropy": 0.0,
            "selector_diversity": float((div_final + div_w_bottleneck * div_bottleneck).item()),
            "selector_mean_abs_cos": float(mac_val.item()),
        }

    return last

def generator_step(mode, generator, discriminator, selector, opt_g, real_images, cfg, opt_t=None):
    if not (mode in STRUCTURED_MODES and isinstance(selector, StructuredSelector)):
        return _old_generator_step(mode, generator, discriminator, selector, opt_g, real_images, cfg, opt_t=opt_t)

    z = torch.randn(real_images.shape[0], cfg.latent_size, device=real_images.device)
    fake_images = generator(z)

    with torch.no_grad():
        _, real_feat = discriminator(real_images)

    set_requires_grad(discriminator, False)
    set_requires_grad(selector, False)
    try:
        _, fake_feat = discriminator(fake_images)

        set_requires_grad(selector, True)
        selector_stats = optimize_selector(
            selector,
            opt_t,
            real_feat,
            fake_feat,
            cfg.num_projections,
            mode=mode,
            cfg=cfg,
            real_images=real_images,
            fake_images=fake_images,
            p=cfg.p,
        )
        set_requires_grad(selector, False)

        with torch.no_grad():
            Zx = _structured_representation(selector, real_feat)
            theta0 = _structured_theta0(selector, cfg.num_projections, real_feat.device)
            theta = selector.project_theta(theta0, return_intermediates=False)

        Zy = _structured_representation(selector, fake_feat)
        sw = sliced_wasserstein_distance(Zx, Zy, theta, p=cfg.p)
        g_total = sw

        opt_g.zero_grad(set_to_none=True)
        g_total.backward()
        opt_g.step()
    finally:
        set_requires_grad(discriminator, True)
        set_requires_grad(selector, True)

    return fake_images.detach(), {
        "g_total": float(g_total.item()),
        "g_sw": float(sw.item()),
        "selector_obj": float(selector_stats["selector_obj"]),
        "selector_entropy": float(selector_stats["selector_entropy"]),
        "selector_diversity": float(selector_stats["selector_diversity"]),
        "selector_mean_abs_cos": float(selector_stats["selector_mean_abs_cos"]),
    }

## Run: DSWD / HDSWD / HSW_DSW / HSW_HDSWD

In [21]:
# @title
# Run four structured modes with two switches:
# DSWD (none), HDSWD (projector only), HSW_DSW (slicer only), HSW_HDSWD (both)

cfg = TrainConfig()

cfg.output_root = "/content/runs_local"
cfg.drive_output_root = "/content/drive/MyDrive/cifar10_dsw_runs" if os.path.exists("/content/drive/MyDrive") else "./runs_drive_backup"
cfg.fidelity_cache_root = "/content/fidelity_cache_local"

cfg.p = 2
cfg.seeds = (42,)
cfg.modes = ("DSWD", "HDSWD", "HSW_DSW", "HSW_HDSWD")

cfg.epochs = 100
cfg.eval_every = 10
cfg.sample_every = 5
cfg.run_tag = "bs512_structured_four_modes_v1"

cfg.latent_size = 100
cfg.lr_g = 5e-4
cfg.lr_d = 5e-4
cfg.lr_t = 1e-4

cfg.num_projections = 256
cfg.selector_steps = 1
cfg.use_diversity_reg = True
cfg.diversity_weight = 10.0

cfg.h_num_base = 128
cfg.h_num_bottleneck = 32
cfg.h_base_rank = 512
cfg.h_bottleneck_diversity_weight = 5.0
cfg.h_mix_act = "linear"

cfg.hsw_slicer_dims = (512, 128)
cfg.hsw_slicer_act = "linear"
cfg.hsw_proj_rank = 0

cfg.drive_backup_every = 10
cfg.drive_backup_on_eval = True
cfg.final_full_sync_to_drive = True
cfg.sync_history_on_backup = True
cfg.sync_eval_history_on_backup = True
cfg.sync_samples_on_backup = False
cfg.sync_eval_ckpts_on_backup = False

cfg.resume_if_possible = True
cfg.autoskip_complete = True

print("Experiment root:", experiment_root(cfg))
train_all(cfg)

Experiment root: /content/runs_local/cifar10_dsw_v2/bs512_structured_four_modes_v1
[INFO] No valid checkpoint found for DSWD seed=42; starting fresh.

/tmp/ipykernel_1981/1607171771.py:155: UserWarning: Failed to resume from /content/runs_local/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_42/checkpoints/last.pt: Weights only load failed. This file can still be loaded, to do so you have two options, do those steps only if you trust the source of the checkpoint.
	(1) In PyTorch 2.6, we changed the default value of the `weights_only` argument in `torch.load` from `False` to `True`. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
	(2) Alternatively, to load with `weights_only=True` please check the recommended steps in the following error message.
	WeightsUnpickler error: Unsupported global: GLOBAL numpy._core.multiarray._reconstruct was not an allowed global by default. Please use `torch.serialization.add_safe_globals([numpy._core.multiarray._reconstruct])` or the `torch.serialization.safe_globals([numpy._core.multiarray._reconstruct])` context manager to allowlist this global if you trust this class/function.

Check the documentation of torch.load to learn more about types accepted by default with weights_only https://pytorch.org/docs/stable/generated/torch.load.html.
  warnings.warn(f"Failed to resume from {ckpt_path}: {e}")

[DSWD][seed=42] epoch 001/100 | G=1.3431 D=2.1900 SW=1.3431 DIV=0.1471 MAC=0.3769 MB_time=0.0393s
[DSWD][seed=42] epoch 002/100 | G=1.6251 D=0.8590 SW=1.6251 DIV=0.0474 MAC=0.2150 MB_time=0.0388s
[DSWD][seed=42] epoch 003/100 | G=1.5818 D=0.9773 SW=1.5818 DIV=0.0422 MAC=0.2008 MB_time=0.0390s
[DSWD][seed=42] epoch 004/100 | G=1.5149 D=0.9523 SW=1.5149 DIV=0.0364 MAC=0.1856 MB_time=0.0388s
[DSWD][seed=42] epoch 005/100 | G=1.4519 D=0.8869 SW=1.4519 DIV=0.0353 MAC=0.1826 MB_time=0.0389s
[DSWD][seed=42] epoch 006/100 | G=1.4407 D=0.8943 SW=1.4407 DIV=0.0356 MAC=0.1840 MB_time=0.0391s
[DSWD][seed=42] epoch 007/100 | G=1.6287 D=0.7495 SW=1.6287 DIV=0.0392 MAC=0.1937 MB_time=0.0388s
[DSWD][seed=42] epoch 008/100 | G=1.6512 D=0.8373 SW=1.6512 DIV=0.0419 MAC=0.2005 MB_time=0.0388s
[DSWD][seed=42] epoch 009/100 | G=1.5432 D=0.6955 SW=1.5432 DIV=0.0391 MAC=0.1938 MB_time=0.0388s
[DSWD][seed=42] epoch 010/100 | G=1.6801 D=0.7329 SW=1.6801 DIV=0.0408 MAC=0.1980 MB_time=0.0387s

Downloading: "https://github.com/toshas/torch-fidelity/releases/download/v0.2.0/weights-inception-2015-12-05-6726825d.pth" to /root/.cache/torch/hub/checkpoints/weights-inception-2015-12-05-6726825d.pth

  eval: {'fid': 276.7709660721068, 'kid_mean': 0.24400680303573608, 'kid_std': 0.0019143165088067998}
[SYNC-RESUME] DSWD seed=42 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_42 (count=4)
[SYNC-RESUME] DSWD seed=42 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_42 (count=4)
[DSWD][seed=42] epoch 011/100 | G=1.5338 D=0.6536 SW=1.5338 DIV=0.0394 MAC=0.1945 MB_time=0.0394s
[DSWD][seed=42] epoch 012/100 | G=1.1856 D=0.8902 SW=1.1856 DIV=0.0330 MAC=0.1774 MB_time=0.0393s
[DSWD][seed=42] epoch 013/100 | G=0.9908 D=0.7828 SW=0.9908 DIV=0.0260 MAC=0.1565 MB_time=0.0394s
[DSWD][seed=42] epoch 014/100 | G=0.8980 D=0.8568 SW=0.8980 DIV=0.0230 MAC=0.1468 MB_time=0.0392s
[DSWD][seed=42] epoch 015/100 | G=0.8558 D=0.8207 SW=0.8558 DIV=0.0212 MAC=0.1403 MB_time=0.0393s
[DSWD][seed=42] epoch 016/100 | G=0.8138 D=0.8701 SW=0.8138 DIV=0.0201 MAC=0.1364 MB_time=0.0392s
[DSWD][seed=42] epoch 017/100 | G=0.8420 D=0.8552 SW=0.8420 DIV=0.0196 MAC=0.1347 MB_time=0.0391s
[DSWD][seed=42] epoch 018/100 | G=0.8484 D=0.8577 SW=0.8484 DIV=0.0205 MAC=0.1377 MB_time=0.0391s
[DSWD][seed=42] epoch 019/100 | G=0.8779 D=0.8725 SW=0.8779 DIV=0.0209 MAC=0.1388 MB_time=0.0391s
[DSWD][seed=42] epoch 020/100 | G=0.7313 D=0.8798 SW=0.7313 DIV=0.0176 MAC=0.1267 MB_time=0.0392s
  eval: {'fid': 181.5650865738158, 'kid_mean': 0.14998821020126343, 'kid_std': 0.0018761152403601353}
[SYNC-RESUME] DSWD seed=42 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_42 (count=4)
[SYNC-RESUME] DSWD seed=42 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_42 (count=4)
[DSWD][seed=42] epoch 021/100 | G=1.0682 D=0.6844 SW=1.0682 DIV=0.0200 MAC=0.1352 MB_time=0.0394s
[DSWD][seed=42] epoch 022/100 | G=0.6534 D=0.9655 SW=0.6534 DIV=0.0195 MAC=0.1329 MB_time=0.0393s
[DSWD][seed=42] epoch 023/100 | G=0.7874 D=0.8748 SW=0.7874 DIV=0.0181 MAC=0.1281 MB_time=0.0391s
[DSWD][seed=42] epoch 024/100 | G=0.8757 D=0.7993 SW=0.8757 DIV=0.0194 MAC=0.1327 MB_time=0.0393s
[DSWD][seed=42] epoch 025/100 | G=0.8920 D=0.7456 SW=0.8920 DIV=0.0201 MAC=0.1353 MB_time=0.0396s
[DSWD][seed=42] epoch 026/100 | G=1.0469 D=0.7798 SW=1.0469 DIV=0.0230 MAC=0.1451 MB_time=0.0394s
[DSWD][seed=42] epoch 027/100 | G=1.1446 D=0.6959 SW=1.1446 DIV=0.0260 MAC=0.1544 MB_time=0.0392s
[DSWD][seed=42] epoch 028/100 | G=1.1494 D=0.6636 SW=1.1494 DIV=0.0260 MAC=0.1546 MB_time=0.0393s
[DSWD][seed=42] epoch 029/100 | G=1.1232 D=0.7074 SW=1.1232 DIV=0.0276 MAC=0.1590 MB_time=0.0392s
[DSWD][seed=42] epoch 030/100 | G=1.6774 D=0.5744 SW=1.6774 DIV=0.0361 MAC=0.1826 MB_time=0.0391s
  eval: {'fid': 178.0285775384001, 'kid_mean': 0.15006714582443237, 'kid_std': 0.0019890737669128284}
[SYNC-RESUME] DSWD seed=42 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_42 (count=4)
[SYNC-RESUME] DSWD seed=42 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_42 (count=4)
[DSWD][seed=42] epoch 031/100 | G=1.0782 D=0.7092 SW=1.0782 DIV=0.0304 MAC=0.1670 MB_time=0.0393s
[DSWD][seed=42] epoch 032/100 | G=1.3253 D=0.5822 SW=1.3253 DIV=0.0261 MAC=0.1534 MB_time=0.0393s
[DSWD][seed=42] epoch 033/100 | G=3.8384 D=0.0655 SW=3.8384 DIV=0.0752 MAC=0.2667 MB_time=0.0391s
[DSWD][seed=42] epoch 034/100 | G=1.4267 D=0.6512 SW=1.4267 DIV=0.0584 MAC=0.2341 MB_time=0.0392s
[DSWD][seed=42] epoch 035/100 | G=1.2074 D=0.6534 SW=1.2074 DIV=0.0337 MAC=0.1759 MB_time=0.0392s
[DSWD][seed=42] epoch 036/100 | G=0.8851 D=0.7223 SW=0.8851 DIV=0.0237 MAC=0.1450 MB_time=0.0393s
[DSWD][seed=42] epoch 037/100 | G=1.0167 D=0.6364 SW=1.0167 DIV=0.0233 MAC=0.1435 MB_time=0.0392s
[DSWD][seed=42] epoch 038/100 | G=0.7184 D=0.6887 SW=0.7184 DIV=0.0202 MAC=0.1321 MB_time=0.0391s
[DSWD][seed=42] epoch 039/100 | G=0.7123 D=0.8402 SW=0.7123 DIV=0.0180 MAC=0.1234 MB_time=0.0392s
[DSWD][seed=42] epoch 040/100 | G=0.9917 D=0.7134 SW=0.9917 DIV=0.0210 MAC=0.1341 MB_time=0.0391s
  eval: {'fid': 150.13508319819073, 'kid_mean': 0.11837746858596802, 'kid_std': 0.0015789907825613464}
[SYNC-RESUME] DSWD seed=42 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_42 (count=4)
[SYNC-RESUME] DSWD seed=42 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_42 (count=4)
[DSWD][seed=42] epoch 041/100 | G=0.7137 D=0.6888 SW=0.7137 DIV=0.0175 MAC=0.1212 MB_time=0.0392s
[DSWD][seed=42] epoch 042/100 | G=0.8307 D=0.6594 SW=0.8307 DIV=0.0184 MAC=0.1244 MB_time=0.0392s
[DSWD][seed=42] epoch 043/100 | G=0.7263 D=0.7779 SW=0.7263 DIV=0.0175 MAC=0.1201 MB_time=0.0392s
[DSWD][seed=42] epoch 044/100 | G=0.6000 D=0.8830 SW=0.6000 DIV=0.0151 MAC=0.1102 MB_time=0.0393s
[DSWD][seed=42] epoch 045/100 | G=0.6759 D=0.5595 SW=0.6759 DIV=0.0136 MAC=0.1035 MB_time=0.0391s
[DSWD][seed=42] epoch 046/100 | G=0.7579 D=0.6384 SW=0.7579 DIV=0.0159 MAC=0.1130 MB_time=0.0392s
[DSWD][seed=42] epoch 047/100 | G=0.6437 D=0.8425 SW=0.6437 DIV=0.0148 MAC=0.1079 MB_time=0.0391s
[DSWD][seed=42] epoch 048/100 | G=0.7858 D=0.5976 SW=0.7858 DIV=0.0161 MAC=0.1130 MB_time=0.0392s
[DSWD][seed=42] epoch 049/100 | G=2.8593 D=0.1244 SW=2.8593 DIV=0.0425 MAC=0.1898 MB_time=0.0392s
[DSWD][seed=42] epoch 050/100 | G=4.4021 D=0.3249 SW=4.4021 DIV=0.1059 MAC=0.3190 MB_time=0.0392s
  eval: {'fid': 225.63526029441022, 'kid_mean': 0.1901559853553772, 'kid_std': 0.00172174431911601}
[SYNC-RESUME] DSWD seed=42 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_42 (count=4)
[SYNC-RESUME] DSWD seed=42 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_42 (count=4)
[DSWD][seed=42] epoch 051/100 | G=1.3460 D=0.5589 SW=1.3460 DIV=0.0563 MAC=0.2272 MB_time=0.0394s
[DSWD][seed=42] epoch 052/100 | G=1.0139 D=0.5745 SW=1.0139 DIV=0.0339 MAC=0.1719 MB_time=0.0393s
[DSWD][seed=42] epoch 053/100 | G=0.9277 D=0.5524 SW=0.9277 DIV=0.0245 MAC=0.1430 MB_time=0.0391s
[DSWD][seed=42] epoch 054/100 | G=0.8876 D=0.4606 SW=0.8876 DIV=0.0218 MAC=0.1334 MB_time=0.0392s
[DSWD][seed=42] epoch 055/100 | G=0.7438 D=0.7475 SW=0.7438 DIV=0.0181 MAC=0.1195 MB_time=0.0392s
[DSWD][seed=42] epoch 056/100 | G=0.6155 D=0.7137 SW=0.6155 DIV=0.0164 MAC=0.1121 MB_time=0.0392s
[DSWD][seed=42] epoch 057/100 | G=0.7111 D=0.5832 SW=0.7111 DIV=0.0162 MAC=0.1113 MB_time=0.0393s
[DSWD][seed=42] epoch 058/100 | G=0.9657 D=0.4462 SW=0.9657 DIV=0.0188 MAC=0.1212 MB_time=0.0391s
[DSWD][seed=42] epoch 059/100 | G=0.6635 D=0.7378 SW=0.6635 DIV=0.0177 MAC=0.1170 MB_time=0.0391s
[DSWD][seed=42] epoch 060/100 | G=0.6371 D=0.7454 SW=0.6371 DIV=0.0155 MAC=0.1078 MB_time=0.0391s
  eval: {'fid': 98.0437015693131, 'kid_mean': 0.06029759168624878, 'kid_std': 0.001358848847729198}
[SYNC-RESUME] DSWD seed=42 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_42 (count=4)
[SYNC-RESUME] DSWD seed=42 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_42 (count=4)
[DSWD][seed=42] epoch 061/100 | G=0.8796 D=0.5600 SW=0.8796 DIV=0.0152 MAC=0.1063 MB_time=0.0392s
[DSWD][seed=42] epoch 062/100 | G=0.6354 D=0.6027 SW=0.6354 DIV=0.0176 MAC=0.1160 MB_time=0.0391s
[DSWD][seed=42] epoch 063/100 | G=0.6343 D=0.6391 SW=0.6343 DIV=0.0150 MAC=0.1052 MB_time=0.0392s
[DSWD][seed=42] epoch 064/100 | G=1.3959 D=0.3604 SW=1.3959 DIV=0.0202 MAC=0.1237 MB_time=0.0392s
[DSWD][seed=42] epoch 065/100 | G=1.7809 D=0.1683 SW=1.7809 DIV=0.0415 MAC=0.1901 MB_time=0.0392s
[DSWD][seed=42] epoch 066/100 | G=2.1820 D=0.5992 SW=2.1820 DIV=0.0507 MAC=0.2121 MB_time=0.0393s
[DSWD][seed=42] epoch 067/100 | G=0.7220 D=0.5684 SW=0.7220 DIV=0.0251 MAC=0.1422 MB_time=0.0392s
[DSWD][seed=42] epoch 068/100 | G=0.6504 D=0.6303 SW=0.6504 DIV=0.0189 MAC=0.1197 MB_time=0.0393s
[DSWD][seed=42] epoch 069/100 | G=0.6896 D=0.6616 SW=0.6896 DIV=0.0171 MAC=0.1126 MB_time=0.0391s
[DSWD][seed=42] epoch 070/100 | G=0.5896 D=0.7342 SW=0.5896 DIV=0.0158 MAC=0.1071 MB_time=0.0393s
  eval: {'fid': 95.41387499080997, 'kid_mean': 0.05964199781417847, 'kid_std': 0.001298510150553142}
[SYNC-RESUME] DSWD seed=42 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_42 (count=4)
[SYNC-RESUME] DSWD seed=42 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_42 (count=4)
[DSWD][seed=42] epoch 071/100 | G=0.5779 D=0.6266 SW=0.5779 DIV=0.0133 MAC=0.0966 MB_time=0.0395s
[DSWD][seed=42] epoch 072/100 | G=0.7084 D=0.5323 SW=0.7084 DIV=0.0154 MAC=0.1050 MB_time=0.0393s
[DSWD][seed=42] epoch 073/100 | G=0.7291 D=0.4806 SW=0.7291 DIV=0.0156 MAC=0.1058 MB_time=0.0391s
[DSWD][seed=42] epoch 074/100 | G=0.6833 D=0.5252 SW=0.6833 DIV=0.0160 MAC=0.1073 MB_time=0.0391s
[DSWD][seed=42] epoch 075/100 | G=0.6904 D=0.6221 SW=0.6904 DIV=0.0165 MAC=0.1092 MB_time=0.0394s
[DSWD][seed=42] epoch 076/100 | G=0.8310 D=0.4729 SW=0.8310 DIV=0.0179 MAC=0.1147 MB_time=0.0391s
[DSWD][seed=42] epoch 077/100 | G=1.7179 D=0.1626 SW=1.7179 DIV=0.0261 MAC=0.1413 MB_time=0.0392s
[DSWD][seed=42] epoch 078/100 | G=2.9225 D=0.0209 SW=2.9225 DIV=0.0619 MAC=0.2369 MB_time=0.0392s
[DSWD][seed=42] epoch 079/100 | G=1.9493 D=0.1536 SW=1.9493 DIV=0.0589 MAC=0.2295 MB_time=0.0391s
[DSWD][seed=42] epoch 080/100 | G=0.9966 D=0.5848 SW=0.9966 DIV=0.0333 MAC=0.1657 MB_time=0.0393s
  eval: {'fid': 106.5188533827976, 'kid_mean': 0.07320870637893677, 'kid_std': 0.0014851152455656348}
[SYNC-RESUME] DSWD seed=42 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_42 (count=4)
[SYNC-RESUME] DSWD seed=42 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_42 (count=4)
[DSWD][seed=42] epoch 081/100 | G=0.8874 D=0.3676 SW=0.8874 DIV=0.0248 MAC=0.1394 MB_time=0.0392s
[DSWD][seed=42] epoch 082/100 | G=0.8883 D=0.3877 SW=0.8883 DIV=0.0218 MAC=0.1287 MB_time=0.0393s
[DSWD][seed=42] epoch 083/100 | G=0.7410 D=0.5352 SW=0.7410 DIV=0.0194 MAC=0.1199 MB_time=0.0393s
[DSWD][seed=42] epoch 084/100 | G=0.7731 D=0.4579 SW=0.7731 DIV=0.0185 MAC=0.1165 MB_time=0.0392s
[DSWD][seed=42] epoch 085/100 | G=0.8183 D=0.4232 SW=0.8183 DIV=0.0187 MAC=0.1172 MB_time=0.0392s
[DSWD][seed=42] epoch 086/100 | G=0.8284 D=0.8831 SW=0.8284 DIV=0.0185 MAC=0.1164 MB_time=0.0391s
[DSWD][seed=42] epoch 087/100 | G=0.5038 D=0.5702 SW=0.5038 DIV=0.0128 MAC=0.0936 MB_time=0.0391s
[DSWD][seed=42] epoch 088/100 | G=0.5501 D=0.7238 SW=0.5501 DIV=0.0118 MAC=0.0888 MB_time=0.0393s
[DSWD][seed=42] epoch 089/100 | G=0.7247 D=0.3787 SW=0.7247 DIV=0.0136 MAC=0.0963 MB_time=0.0391s
[DSWD][seed=42] epoch 090/100 | G=0.6421 D=0.3850 SW=0.6421 DIV=0.0156 MAC=0.1042 MB_time=0.0393s
  eval: {'fid': 84.14708039291071, 'kid_mean': 0.048235681056976315, 'kid_std': 0.0011073407524005005}
[SYNC-RESUME] DSWD seed=42 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_42 (count=4)
[SYNC-RESUME] DSWD seed=42 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_42 (count=4)
[DSWD][seed=42] epoch 091/100 | G=0.7325 D=0.4918 SW=0.7325 DIV=0.0161 MAC=0.1059 MB_time=0.0392s
[DSWD][seed=42] epoch 092/100 | G=0.6344 D=0.6891 SW=0.6344 DIV=0.0135 MAC=0.0954 MB_time=0.0394s
[DSWD][seed=42] epoch 093/100 | G=1.9604 D=0.0851 SW=1.9604 DIV=0.0292 MAC=0.1473 MB_time=0.0393s
[DSWD][seed=42] epoch 094/100 | G=2.3108 D=0.0204 SW=2.3108 DIV=0.0578 MAC=0.2261 MB_time=0.0392s
[DSWD][seed=42] epoch 095/100 | G=2.0145 D=0.0246 SW=2.0145 DIV=0.0525 MAC=0.2144 MB_time=0.0392s
[DSWD][seed=42] epoch 096/100 | G=1.7751 D=0.0481 SW=1.7751 DIV=0.0484 MAC=0.2047 MB_time=0.0392s
[DSWD][seed=42] epoch 097/100 | G=1.5347 D=0.1287 SW=1.5347 DIV=0.0415 MAC=0.1872 MB_time=0.0392s
[DSWD][seed=42] epoch 098/100 | G=0.9097 D=0.4668 SW=0.9097 DIV=0.0303 MAC=0.1550 MB_time=0.0392s
[DSWD][seed=42] epoch 099/100 | G=0.8414 D=0.3124 SW=0.8414 DIV=0.0219 MAC=0.1277 MB_time=0.0392s
[DSWD][seed=42] epoch 100/100 | G=0.7534 D=0.5049 SW=0.7534 DIV=0.0201 MAC=0.1205 MB_time=0.0391s
  eval: {'fid': 62.53161130166467, 'kid_mean': 0.04390214443206787, 'kid_std': 0.0013928221666566684}
[SYNC-RESUME] DSWD seed=42 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_42 (count=4)
[SYNC-RESUME] DSWD seed=42 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_42 (count=4)
[SYNC-RESUME] DSWD seed=42 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_42 (count=5)
[SYNC-FULL:OK] /content/runs_local/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_42 -> /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_42 (files_seen=44)
[FLUSH] Drive 已强制同步完成
[DONE] DSWD seed=42 -> /content/runs_local/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_42
[INFO] No valid checkpoint found for HDSWD seed=42; starting fresh.
[HDSWD][seed=42] epoch 001/100 | G=0.8618 D=4.7954 SW=0.8618 DIV=0.0685 MAC=0.1531 MB_time=0.0363s
[HDSWD][seed=42] epoch 002/100 | G=0.5878 D=0.7260 SW=0.5878 DIV=0.0667 MAC=0.1513 MB_time=0.0357s
[HDSWD][seed=42] epoch 003/100 | G=0.5567 D=1.0955 SW=0.5567 DIV=0.0699 MAC=0.1512 MB_time=0.0359s
[HDSWD][seed=42] epoch 004/100 | G=0.6480 D=0.9891 SW=0.6480 DIV=0.0770 MAC=0.1519 MB_time=0.0357s
[HDSWD][seed=42] epoch 005/100 | G=0.8164 D=0.9508 SW=0.8164 DIV=0.0933 MAC=0.1554 MB_time=0.0360s
[HDSWD][seed=42] epoch 006/100 | G=0.9776 D=0.9098 SW=0.9776 DIV=0.1143 MAC=0.1590 MB_time=0.0357s
[HDSWD][seed=42] epoch 007/100 | G=0.8898 D=0.9125 SW=0.8898 DIV=0.1319 MAC=0.1623 MB_time=0.0359s
[HDSWD][seed=42] epoch 008/100 | G=1.0549 D=0.8022 SW=1.0549 DIV=0.1516 MAC=0.1650 MB_time=0.0359s
[HDSWD][seed=42] epoch 009/100 | G=0.9827 D=0.8266 SW=0.9827 DIV=0.1517 MAC=0.1653 MB_time=0.0362s
[HDSWD][seed=42] epoch 010/100 | G=1.0107 D=0.8636 SW=1.0107 DIV=0.1623 MAC=0.1662 MB_time=0.0358s
  eval: {'fid': 293.4946076922493, 'kid_mean': 0.2767423915863037, 'kid_std': 0.0017824294124939575}
[SYNC-RESUME] HDSWD seed=42 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_42 (count=4)
[SYNC-RESUME] HDSWD seed=42 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_42 (count=4)
[HDSWD][seed=42] epoch 011/100 | G=0.9237 D=0.8445 SW=0.9237 DIV=0.1529 MAC=0.1653 MB_time=0.0357s
[HDSWD][seed=42] epoch 012/100 | G=0.7387 D=0.9926 SW=0.7387 DIV=0.1487 MAC=0.1634 MB_time=0.0355s
[HDSWD][seed=42] epoch 013/100 | G=0.5366 D=0.9077 SW=0.5366 DIV=0.1324 MAC=0.1598 MB_time=0.0357s
[HDSWD][seed=42] epoch 014/100 | G=0.5647 D=0.9380 SW=0.5647 DIV=0.1180 MAC=0.1559 MB_time=0.0356s
[HDSWD][seed=42] epoch 015/100 | G=0.5551 D=0.8932 SW=0.5551 DIV=0.1071 MAC=0.1539 MB_time=0.0355s
[HDSWD][seed=42] epoch 016/100 | G=0.5581 D=0.9394 SW=0.5581 DIV=0.1008 MAC=0.1518 MB_time=0.0356s
[HDSWD][seed=42] epoch 017/100 | G=0.5451 D=0.9087 SW=0.5451 DIV=0.1027 MAC=0.1526 MB_time=0.0357s
[HDSWD][seed=42] epoch 018/100 | G=0.5021 D=0.9721 SW=0.5021 DIV=0.0991 MAC=0.1511 MB_time=0.0356s
[HDSWD][seed=42] epoch 019/100 | G=0.4910 D=0.9372 SW=0.4910 DIV=0.0926 MAC=0.1499 MB_time=0.0358s
[HDSWD][seed=42] epoch 020/100 | G=0.5182 D=0.9271 SW=0.5182 DIV=0.0913 MAC=0.1496 MB_time=0.0356s
  eval: {'fid': 176.23963265503, 'kid_mean': 0.14462413072586058, 'kid_std': 0.0015970263842359329}
[SYNC-RESUME] HDSWD seed=42 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_42 (count=4)
[SYNC-RESUME] HDSWD seed=42 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_42 (count=4)
[HDSWD][seed=42] epoch 021/100 | G=0.5001 D=0.9089 SW=0.5001 DIV=0.0898 MAC=0.1493 MB_time=0.0357s
[HDSWD][seed=42] epoch 022/100 | G=0.4373 D=1.0140 SW=0.4373 DIV=0.0837 MAC=0.1478 MB_time=0.0358s
[HDSWD][seed=42] epoch 023/100 | G=0.6165 D=0.8386 SW=0.6165 DIV=0.0936 MAC=0.1500 MB_time=0.0357s
[HDSWD][seed=42] epoch 024/100 | G=0.5258 D=0.8093 SW=0.5258 DIV=0.0916 MAC=0.1501 MB_time=0.0356s
[HDSWD][seed=42] epoch 025/100 | G=0.6823 D=1.0159 SW=0.6823 DIV=0.0995 MAC=0.1521 MB_time=0.0357s
[HDSWD][seed=42] epoch 026/100 | G=1.1125 D=0.6574 SW=1.1125 DIV=0.1438 MAC=0.1619 MB_time=0.0356s
[HDSWD][seed=42] epoch 027/100 | G=1.9195 D=0.3848 SW=1.9195 DIV=0.1785 MAC=0.1692 MB_time=0.0358s
[HDSWD][seed=42] epoch 028/100 | G=2.7378 D=0.4006 SW=2.7378 DIV=0.3252 MAC=0.1935 MB_time=0.0358s
[HDSWD][seed=42] epoch 029/100 | G=0.7704 D=0.8256 SW=0.7704 DIV=0.3023 MAC=0.1907 MB_time=0.0358s
[HDSWD][seed=42] epoch 030/100 | G=0.9116 D=0.6771 SW=0.9116 DIV=0.2082 MAC=0.1747 MB_time=0.0357s
  eval: {'fid': 180.90215685723098, 'kid_mean': 0.1548175048828125, 'kid_std': 0.0017767973826335291}
[SYNC-RESUME] HDSWD seed=42 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_42 (count=4)
[SYNC-RESUME] HDSWD seed=42 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_42 (count=4)
[HDSWD][seed=42] epoch 031/100 | G=3.0236 D=0.1213 SW=3.0236 DIV=0.2301 MAC=0.1784 MB_time=0.0357s
[HDSWD][seed=42] epoch 032/100 | G=1.7610 D=0.5318 SW=1.7610 DIV=0.3382 MAC=0.1945 MB_time=0.0357s
[HDSWD][seed=42] epoch 033/100 | G=0.9715 D=0.5621 SW=0.9715 DIV=0.2621 MAC=0.1828 MB_time=0.0356s
[HDSWD][seed=42] epoch 034/100 | G=0.9885 D=0.5933 SW=0.9885 DIV=0.2028 MAC=0.1733 MB_time=0.0357s
[HDSWD][seed=42] epoch 035/100 | G=0.7641 D=0.7572 SW=0.7641 DIV=0.1686 MAC=0.1668 MB_time=0.0356s
[HDSWD][seed=42] epoch 036/100 | G=0.8821 D=0.6148 SW=0.8821 DIV=0.1429 MAC=0.1618 MB_time=0.0358s
[HDSWD][seed=42] epoch 037/100 | G=0.9578 D=0.5178 SW=0.9578 DIV=0.1424 MAC=0.1614 MB_time=0.0357s
[HDSWD][seed=42] epoch 038/100 | G=0.7929 D=0.7445 SW=0.7929 DIV=0.1460 MAC=0.1619 MB_time=0.0358s
[HDSWD][seed=42] epoch 039/100 | G=0.7947 D=0.6857 SW=0.7947 DIV=0.1275 MAC=0.1583 MB_time=0.0358s
[HDSWD][seed=42] epoch 040/100 | G=1.0092 D=0.4937 SW=1.0092 DIV=0.1373 MAC=0.1605 MB_time=0.0357s
  eval: {'fid': 155.5930864880632, 'kid_mean': 0.12439689874649047, 'kid_std': 0.001719553500908387}
[SYNC-RESUME] HDSWD seed=42 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_42 (count=4)
[SYNC-RESUME] HDSWD seed=42 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_42 (count=4)
[HDSWD][seed=42] epoch 041/100 | G=0.6526 D=0.7129 SW=0.6526 DIV=0.1322 MAC=0.1598 MB_time=0.0355s
[HDSWD][seed=42] epoch 042/100 | G=0.8381 D=0.6026 SW=0.8381 DIV=0.1348 MAC=0.1602 MB_time=0.0356s
[HDSWD][seed=42] epoch 043/100 | G=0.6231 D=0.7763 SW=0.6231 DIV=0.1179 MAC=0.1565 MB_time=0.0358s
[HDSWD][seed=42] epoch 044/100 | G=0.6372 D=0.6332 SW=0.6372 DIV=0.1090 MAC=0.1549 MB_time=0.0356s
[HDSWD][seed=42] epoch 045/100 | G=0.6612 D=0.6208 SW=0.6612 DIV=0.1148 MAC=0.1561 MB_time=0.0358s
[HDSWD][seed=42] epoch 046/100 | G=0.7117 D=0.7234 SW=0.7117 DIV=0.1091 MAC=0.1547 MB_time=0.0355s

## Summary

In [22]:
# @title
# Summarize results (best checkpoint and final epoch)
from pathlib import Path
import pandas as pd

base = experiment_root(cfg)
rows_best = []
rows_final = []

for mode_dir in base.iterdir():
    if not mode_dir.is_dir():
        continue
    for seed_dir in mode_dir.iterdir():
        eval_csv = seed_dir / "logs" / "eval_history.csv"
        if not eval_csv.exists():
            continue
        df = pd.read_csv(eval_csv)
        if len(df) == 0:
            continue

        best = df.loc[df["fid"].idxmin()].copy()
        final = df.sort_values("epoch").iloc[-1].copy()

        best["seed"] = seed_dir.name
        final["seed"] = seed_dir.name
        rows_best.append(best)
        rows_final.append(final)

best_df = pd.DataFrame(rows_best).sort_values("fid").reset_index(drop=True)
final_df = pd.DataFrame(rows_final).sort_values("fid").reset_index(drop=True)

print("=== Best over training ===")
display(best_df)

print("\n=== Final epoch ===")
display(final_df)

=== Best over training ===

   epoch     seed       mode        fid  kid_mean   kid_std
0    100  seed_42    HSW_DSW  54.988746  0.037053  0.001283
1    100  seed_42      HDSWD  58.694691  0.041272  0.001359
2    100  seed_42  HSW_HDSWD  59.506497  0.042151  0.001299
3    100  seed_42       DSWD  62.531611  0.043902  0.001393

=== Final epoch ===

   epoch     seed       mode        fid  kid_mean   kid_std
0    100  seed_42    HSW_DSW  54.988746  0.037053  0.001283
1    100  seed_42      HDSWD  58.694691  0.041272  0.001359
2    100  seed_42  HSW_HDSWD  59.506497  0.042151  0.001299
3    100  seed_42       DSWD  62.531611  0.043902  0.001393

In [23]:
# @title
# Run four structured modes with two switches:
# DSWD (none), HDSWD (projector only), HSW_DSW (slicer only), HSW_HDSWD (both)

cfg = TrainConfig()

cfg.output_root = "/content/runs_local"
cfg.drive_output_root = "/content/drive/MyDrive/cifar10_dsw_runs" if os.path.exists("/content/drive/MyDrive") else "./runs_drive_backup"
cfg.fidelity_cache_root = "/content/fidelity_cache_local"

cfg.p = 2
cfg.seeds = (123,)
cfg.modes = ("DSWD", "HDSWD", "HSW_DSW", "HSW_HDSWD")

cfg.epochs = 100
cfg.eval_every = 10
cfg.sample_every = 5
cfg.run_tag = "bs512_structured_four_modes_v1"

cfg.latent_size = 100
cfg.lr_g = 5e-4
cfg.lr_d = 5e-4
cfg.lr_t = 1e-4

cfg.num_projections = 256
cfg.selector_steps = 1
cfg.use_diversity_reg = True
cfg.diversity_weight = 10.0

cfg.h_num_base = 128
cfg.h_num_bottleneck = 32
cfg.h_base_rank = 512
cfg.h_bottleneck_diversity_weight = 5.0
cfg.h_mix_act = "linear"

cfg.hsw_slicer_dims = (512, 128)
cfg.hsw_slicer_act = "linear"
cfg.hsw_proj_rank = 0

cfg.drive_backup_every = 10
cfg.drive_backup_on_eval = True
cfg.final_full_sync_to_drive = True
cfg.sync_history_on_backup = True
cfg.sync_eval_history_on_backup = True
cfg.sync_samples_on_backup = False
cfg.sync_eval_ckpts_on_backup = False

cfg.resume_if_possible = True
cfg.autoskip_complete = True

print("Experiment root:", experiment_root(cfg))
train_all(cfg)

Experiment root: /content/runs_local/cifar10_dsw_v2/bs512_structured_four_modes_v1
[INFO] No valid checkpoint found for DSWD seed=123; starting fresh.
[DSWD][seed=123] epoch 001/100 | G=1.0328 D=1.1806 SW=1.0328 DIV=0.1402 MAC=0.3649 MB_time=0.0394s
[DSWD][seed=123] epoch 002/100 | G=0.6873 D=0.8849 SW=0.6873 DIV=0.0219 MAC=0.1410 MB_time=0.0395s
[DSWD][seed=123] epoch 003/100 | G=1.2803 D=0.9438 SW=1.2803 DIV=0.0181 MAC=0.1246 MB_time=0.0392s
[DSWD][seed=123] epoch 004/100 | G=1.7389 D=0.9190 SW=1.7389 DIV=0.0345 MAC=0.1750 MB_time=0.0392s
[DSWD][seed=123] epoch 005/100 | G=1.4404 D=1.0078 SW=1.4404 DIV=0.0406 MAC=0.1911 MB_time=0.0392s
[DSWD][seed=123] epoch 006/100 | G=1.4901 D=0.7833 SW=1.4901 DIV=0.0350 MAC=0.1771 MB_time=0.0392s
[DSWD][seed=123] epoch 007/100 | G=1.6391 D=0.7264 SW=1.6391 DIV=0.0404 MAC=0.1924 MB_time=0.0393s
[DSWD][seed=123] epoch 008/100 | G=1.7537 D=0.6974 SW=1.7537 DIV=0.0428 MAC=0.1992 MB_time=0.0392s
[DSWD][seed=123] epoch 009/100 | G=1.6228 D=0.7157 SW=1.6228 DIV=0.0411 MAC=0.1950 MB_time=0.0392s
[DSWD][seed=123] epoch 010/100 | G=1.3840 D=0.8695 SW=1.3840 DIV=0.0378 MAC=0.1856 MB_time=0.0391s
  eval: {'fid': 284.8155130317533, 'kid_mean': 0.27431931257247927, 'kid_std': 0.0021077922143224632}
[SYNC-RESUME] DSWD seed=123 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_123 (count=4)
[SYNC-RESUME] DSWD seed=123 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_123 (count=4)
[DSWD][seed=123] epoch 011/100 | G=1.1709 D=0.7450 SW=1.1709 DIV=0.0289 MAC=0.1609 MB_time=0.0393s
[DSWD][seed=123] epoch 012/100 | G=1.0396 D=0.8398 SW=1.0396 DIV=0.0266 MAC=0.1537 MB_time=0.0392s
[DSWD][seed=123] epoch 013/100 | G=1.0024 D=0.8201 SW=1.0024 DIV=0.0243 MAC=0.1465 MB_time=0.0391s
[DSWD][seed=123] epoch 014/100 | G=1.0328 D=0.8600 SW=1.0328 DIV=0.0256 MAC=0.1504 MB_time=0.0392s
[DSWD][seed=123] epoch 015/100 | G=1.0142 D=0.8083 SW=1.0142 DIV=0.0247 MAC=0.1477 MB_time=0.0391s
[DSWD][seed=123] epoch 016/100 | G=1.0225 D=0.7657 SW=1.0225 DIV=0.0240 MAC=0.1456 MB_time=0.0392s
[DSWD][seed=123] epoch 017/100 | G=0.8543 D=0.8270 SW=0.8543 DIV=0.0214 MAC=0.1370 MB_time=0.0394s
[DSWD][seed=123] epoch 018/100 | G=0.7931 D=0.9588 SW=0.7931 DIV=0.0199 MAC=0.1313 MB_time=0.0393s
[DSWD][seed=123] epoch 019/100 | G=0.8470 D=0.7887 SW=0.8470 DIV=0.0185 MAC=0.1261 MB_time=0.0394s
[DSWD][seed=123] epoch 020/100 | G=0.8636 D=0.8602 SW=0.8636 DIV=0.0201 MAC=0.1317 MB_time=0.0394s
  eval: {'fid': 182.5593007596792, 'kid_mean': 0.15346617221832276, 'kid_std': 0.0017509737331316813}
[SYNC-RESUME] DSWD seed=123 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_123 (count=4)
[SYNC-RESUME] DSWD seed=123 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_123 (count=4)
[DSWD][seed=123] epoch 021/100 | G=0.9578 D=0.7526 SW=0.9578 DIV=0.0217 MAC=0.1374 MB_time=0.0391s
[DSWD][seed=123] epoch 022/100 | G=0.9108 D=0.7834 SW=0.9108 DIV=0.0219 MAC=0.1378 MB_time=0.0391s
[DSWD][seed=123] epoch 023/100 | G=0.7593 D=0.8728 SW=0.7593 DIV=0.0180 MAC=0.1233 MB_time=0.0392s
[DSWD][seed=123] epoch 024/100 | G=0.8538 D=0.8658 SW=0.8538 DIV=0.0177 MAC=0.1220 MB_time=0.0392s
[DSWD][seed=123] epoch 025/100 | G=1.0599 D=0.6514 SW=1.0599 DIV=0.0234 MAC=0.1421 MB_time=0.0394s
[DSWD][seed=123] epoch 026/100 | G=0.9338 D=0.8222 SW=0.9338 DIV=0.0221 MAC=0.1378 MB_time=0.0393s
[DSWD][seed=123] epoch 027/100 | G=2.7130 D=0.2308 SW=2.7130 DIV=0.0455 MAC=0.1968 MB_time=0.0395s
[DSWD][seed=123] epoch 028/100 | G=1.1505 D=0.7793 SW=1.1505 DIV=0.0448 MAC=0.2000 MB_time=0.0392s
[DSWD][seed=123] epoch 029/100 | G=0.9981 D=0.7426 SW=0.9981 DIV=0.0260 MAC=0.1494 MB_time=0.0392s
[DSWD][seed=123] epoch 030/100 | G=0.9069 D=0.7303 SW=0.9069 DIV=0.0215 MAC=0.1339 MB_time=0.0391s
  eval: {'fid': 159.11310030726872, 'kid_mean': 0.13159733057022094, 'kid_std': 0.0017398358205846943}
[SYNC-RESUME] DSWD seed=123 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_123 (count=4)
[SYNC-RESUME] DSWD seed=123 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_123 (count=4)
[DSWD][seed=123] epoch 031/100 | G=1.0323 D=0.7158 SW=1.0323 DIV=0.0230 MAC=0.1392 MB_time=0.0394s
[DSWD][seed=123] epoch 032/100 | G=1.2334 D=0.5764 SW=1.2334 DIV=0.0265 MAC=0.1503 MB_time=0.0395s
[DSWD][seed=123] epoch 033/100 | G=0.8975 D=0.7511 SW=0.8975 DIV=0.0235 MAC=0.1403 MB_time=0.0398s
[DSWD][seed=123] epoch 034/100 | G=0.9704 D=0.8342 SW=0.9704 DIV=0.0236 MAC=0.1403 MB_time=0.0395s
[DSWD][seed=123] epoch 035/100 | G=1.5386 D=0.3450 SW=1.5386 DIV=0.0250 MAC=0.1426 MB_time=0.0394s
[DSWD][seed=123] epoch 036/100 | G=0.8721 D=0.8619 SW=0.8721 DIV=0.0299 MAC=0.1583 MB_time=0.0394s
[DSWD][seed=123] epoch 037/100 | G=0.9049 D=0.7176 SW=0.9049 DIV=0.0220 MAC=0.1341 MB_time=0.0392s
[DSWD][seed=123] epoch 038/100 | G=1.0582 D=0.6102 SW=1.0582 DIV=0.0251 MAC=0.1440 MB_time=0.0393s
[DSWD][seed=123] epoch 039/100 | G=1.0342 D=0.6225 SW=1.0342 DIV=0.0226 MAC=0.1354 MB_time=0.0392s
[DSWD][seed=123] epoch 040/100 | G=1.1388 D=0.6176 SW=1.1388 DIV=0.0251 MAC=0.1436 MB_time=0.0392s
  eval: {'fid': 128.75812557854323, 'kid_mean': 0.09294092655181885, 'kid_std': 0.0013358855038550306}
[SYNC-RESUME] DSWD seed=123 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_123 (count=4)
[SYNC-RESUME] DSWD seed=123 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_123 (count=4)
[DSWD][seed=123] epoch 041/100 | G=0.8843 D=0.7623 SW=0.8843 DIV=0.0229 MAC=0.1360 MB_time=0.0392s
[DSWD][seed=123] epoch 042/100 | G=0.7658 D=0.9140 SW=0.7658 DIV=0.0203 MAC=0.1267 MB_time=0.0392s
[DSWD][seed=123] epoch 043/100 | G=1.0536 D=0.5719 SW=1.0536 DIV=0.0221 MAC=0.1330 MB_time=0.0395s
[DSWD][seed=123] epoch 044/100 | G=1.5014 D=0.4746 SW=1.5014 DIV=0.0284 MAC=0.1533 MB_time=0.0394s
[DSWD][seed=123] epoch 045/100 | G=3.6120 D=0.0338 SW=3.6120 DIV=0.0711 MAC=0.2551 MB_time=0.0392s
[DSWD][seed=123] epoch 046/100 | G=1.6051 D=0.9337 SW=1.6051 DIV=0.0610 MAC=0.2289 MB_time=0.0392s
[DSWD][seed=123] epoch 047/100 | G=0.5838 D=0.9140 SW=0.5838 DIV=0.0182 MAC=0.1181 MB_time=0.0392s
[DSWD][seed=123] epoch 048/100 | G=0.6774 D=0.7685 SW=0.6774 DIV=0.0162 MAC=0.1101 MB_time=0.0392s
[DSWD][seed=123] epoch 049/100 | G=0.7067 D=0.6359 SW=0.7067 DIV=0.0164 MAC=0.1104 MB_time=0.0391s
[DSWD][seed=123] epoch 050/100 | G=0.7818 D=0.6768 SW=0.7818 DIV=0.0183 MAC=0.1173 MB_time=0.0392s
  eval: {'fid': 116.87332730969558, 'kid_mean': 0.08107315063476563, 'kid_std': 0.001625152302667382}
[SYNC-RESUME] DSWD seed=123 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_123 (count=4)
[SYNC-RESUME] DSWD seed=123 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_123 (count=4)
[DSWD][seed=123] epoch 051/100 | G=0.7301 D=0.6605 SW=0.7301 DIV=0.0168 MAC=0.1117 MB_time=0.0392s
[DSWD][seed=123] epoch 052/100 | G=0.7247 D=0.6561 SW=0.7247 DIV=0.0171 MAC=0.1123 MB_time=0.0392s
[DSWD][seed=123] epoch 053/100 | G=0.8897 D=0.6751 SW=0.8897 DIV=0.0198 MAC=0.1228 MB_time=0.0393s
[DSWD][seed=123] epoch 054/100 | G=0.7798 D=0.7145 SW=0.7798 DIV=0.0176 MAC=0.1143 MB_time=0.0392s
[DSWD][seed=123] epoch 055/100 | G=0.7254 D=0.5774 SW=0.7254 DIV=0.0170 MAC=0.1119 MB_time=0.0392s
[DSWD][seed=123] epoch 056/100 | G=0.8150 D=0.6327 SW=0.8150 DIV=0.0189 MAC=0.1187 MB_time=0.0391s
[DSWD][seed=123] epoch 057/100 | G=0.7703 D=0.5879 SW=0.7703 DIV=0.0174 MAC=0.1131 MB_time=0.0392s
[DSWD][seed=123] epoch 058/100 | G=1.0588 D=0.6148 SW=1.0588 DIV=0.0196 MAC=0.1208 MB_time=0.0391s
[DSWD][seed=123] epoch 059/100 | G=1.3080 D=0.4658 SW=1.3080 DIV=0.0328 MAC=0.1628 MB_time=0.0394s
[DSWD][seed=123] epoch 060/100 | G=1.1837 D=0.3971 SW=1.1837 DIV=0.0253 MAC=0.1404 MB_time=0.0391s
  eval: {'fid': 96.36933709632251, 'kid_mean': 0.05695509433746338, 'kid_std': 0.0012518361809470877}
[SYNC-RESUME] DSWD seed=123 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_123 (count=4)
[SYNC-RESUME] DSWD seed=123 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_123 (count=4)
[DSWD][seed=123] epoch 061/100 | G=0.9053 D=0.6673 SW=0.9053 DIV=0.0253 MAC=0.1405 MB_time=0.0391s
[DSWD][seed=123] epoch 062/100 | G=1.0626 D=0.4398 SW=1.0626 DIV=0.0248 MAC=0.1386 MB_time=0.0392s
[DSWD][seed=123] epoch 063/100 | G=0.8457 D=0.6375 SW=0.8457 DIV=0.0217 MAC=0.1280 MB_time=0.0392s
[DSWD][seed=123] epoch 064/100 | G=0.9724 D=0.4814 SW=0.9724 DIV=0.0227 MAC=0.1310 MB_time=0.0392s
[DSWD][seed=123] epoch 065/100 | G=0.7431 D=0.5996 SW=0.7431 DIV=0.0194 MAC=0.1197 MB_time=0.0392s
[DSWD][seed=123] epoch 066/100 | G=0.7499 D=0.5315 SW=0.7499 DIV=0.0167 MAC=0.1095 MB_time=0.0392s
[DSWD][seed=123] epoch 067/100 | G=1.9433 D=0.0750 SW=1.9433 DIV=0.0329 MAC=0.1604 MB_time=0.0393s
[DSWD][seed=123] epoch 068/100 | G=1.6273 D=0.5725 SW=1.6273 DIV=0.0464 MAC=0.1985 MB_time=0.0392s
[DSWD][seed=123] epoch 069/100 | G=0.9643 D=0.4687 SW=0.9643 DIV=0.0277 MAC=0.1477 MB_time=0.0393s
[DSWD][seed=123] epoch 070/100 | G=0.7885 D=0.5124 SW=0.7885 DIV=0.0203 MAC=0.1227 MB_time=0.0392s
  eval: {'fid': 94.74776486420063, 'kid_mean': 0.05844676494598389, 'kid_std': 0.00122716380713687}
[SYNC-RESUME] DSWD seed=123 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_123 (count=4)
[SYNC-RESUME] DSWD seed=123 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_123 (count=4)
[DSWD][seed=123] epoch 071/100 | G=0.8282 D=0.5389 SW=0.8282 DIV=0.0201 MAC=0.1216 MB_time=0.0392s
[DSWD][seed=123] epoch 072/100 | G=0.8198 D=0.4429 SW=0.8198 DIV=0.0185 MAC=0.1161 MB_time=0.0392s
[DSWD][seed=123] epoch 073/100 | G=1.0832 D=0.4144 SW=1.0832 DIV=0.0228 MAC=0.1311 MB_time=0.0392s
[DSWD][seed=123] epoch 074/100 | G=0.8317 D=0.4756 SW=0.8317 DIV=0.0216 MAC=0.1271 MB_time=0.0392s
[DSWD][seed=123] epoch 075/100 | G=0.8868 D=0.4872 SW=0.8868 DIV=0.0204 MAC=0.1223 MB_time=0.0392s
[DSWD][seed=123] epoch 076/100 | G=0.8328 D=0.4558 SW=0.8328 DIV=0.0199 MAC=0.1208 MB_time=0.0393s
[DSWD][seed=123] epoch 077/100 | G=0.7743 D=0.4819 SW=0.7743 DIV=0.0184 MAC=0.1149 MB_time=0.0393s
[DSWD][seed=123] epoch 078/100 | G=0.6903 D=0.8046 SW=0.6903 DIV=0.0169 MAC=0.1090 MB_time=0.0392s
[DSWD][seed=123] epoch 079/100 | G=1.0850 D=0.2846 SW=1.0850 DIV=0.0191 MAC=0.1166 MB_time=0.0392s
[DSWD][seed=123] epoch 080/100 | G=1.8738 D=0.0928 SW=1.8738 DIV=0.0340 MAC=0.1640 MB_time=0.0392s
  eval: {'fid': 95.37312723473366, 'kid_mean': 0.05683597326278687, 'kid_std': 0.001160514864722741}
[SYNC-RESUME] DSWD seed=123 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_123 (count=4)
[SYNC-RESUME] DSWD seed=123 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_123 (count=4)
[DSWD][seed=123] epoch 081/100 | G=2.5783 D=0.0183 SW=2.5783 DIV=0.0580 MAC=0.2253 MB_time=0.0392s
[DSWD][seed=123] epoch 082/100 | G=1.1499 D=0.4386 SW=1.1499 DIV=0.0425 MAC=0.1873 MB_time=0.0392s
[DSWD][seed=123] epoch 083/100 | G=0.8712 D=0.4061 SW=0.8712 DIV=0.0257 MAC=0.1402 MB_time=0.0392s
[DSWD][seed=123] epoch 084/100 | G=0.7193 D=0.4324 SW=0.7193 DIV=0.0203 MAC=0.1217 MB_time=0.0392s
[DSWD][seed=123] epoch 085/100 | G=0.6428 D=0.6635 SW=0.6428 DIV=0.0159 MAC=0.1049 MB_time=0.0392s
[DSWD][seed=123] epoch 086/100 | G=0.7770 D=0.4231 SW=0.7770 DIV=0.0165 MAC=0.1072 MB_time=0.0391s
[DSWD][seed=123] epoch 087/100 | G=0.7336 D=0.3919 SW=0.7336 DIV=0.0176 MAC=0.1112 MB_time=0.0392s
[DSWD][seed=123] epoch 088/100 | G=0.6758 D=0.4965 SW=0.6758 DIV=0.0163 MAC=0.1060 MB_time=0.0392s
[DSWD][seed=123] epoch 089/100 | G=0.7559 D=0.4096 SW=0.7559 DIV=0.0164 MAC=0.1062 MB_time=0.0393s
[DSWD][seed=123] epoch 090/100 | G=0.6800 D=0.4624 SW=0.6800 DIV=0.0164 MAC=0.1063 MB_time=0.0392s
  eval: {'fid': 78.14816323194862, 'kid_mean': 0.0416060471534729, 'kid_std': 0.0009900547071144722}
[SYNC-RESUME] DSWD seed=123 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_123 (count=4)
[SYNC-RESUME] DSWD seed=123 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_123 (count=4)
[DSWD][seed=123] epoch 091/100 | G=0.7364 D=1.1974 SW=0.7364 DIV=0.0160 MAC=0.1044 MB_time=0.0395s
[DSWD][seed=123] epoch 092/100 | G=0.6483 D=0.5794 SW=0.6483 DIV=0.0137 MAC=0.0956 MB_time=0.0391s
[DSWD][seed=123] epoch 093/100 | G=0.6310 D=0.4104 SW=0.6310 DIV=0.0134 MAC=0.0941 MB_time=0.0392s
[DSWD][seed=123] epoch 094/100 | G=1.7252 D=0.1148 SW=1.7252 DIV=0.0253 MAC=0.1345 MB_time=0.0393s
[DSWD][seed=123] epoch 095/100 | G=2.3766 D=0.0226 SW=2.3766 DIV=0.0556 MAC=0.2187 MB_time=0.0395s
[DSWD][seed=123] epoch 096/100 | G=1.3209 D=0.0681 SW=1.3209 DIV=0.0416 MAC=0.1842 MB_time=0.0391s
[DSWD][seed=123] epoch 097/100 | G=0.9972 D=0.5002 SW=0.9972 DIV=0.0302 MAC=0.1520 MB_time=0.0392s
[DSWD][seed=123] epoch 098/100 | G=0.8554 D=0.2714 SW=0.8554 DIV=0.0216 MAC=0.1246 MB_time=0.0392s
[DSWD][seed=123] epoch 099/100 | G=0.7809 D=0.6242 SW=0.7809 DIV=0.0205 MAC=0.1203 MB_time=0.0392s
[DSWD][seed=123] epoch 100/100 | G=0.7974 D=0.2955 SW=0.7974 DIV=0.0179 MAC=0.1111 MB_time=0.0392s
  eval: {'fid': 58.962416003742135, 'kid_mean': 0.04109405755996704, 'kid_std': 0.0014543608975819524}
[SYNC-RESUME] DSWD seed=123 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_123 (count=4)
[SYNC-RESUME] DSWD seed=123 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_123 (count=4)
[SYNC-RESUME] DSWD seed=123 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_123 (count=5)
[SYNC-FULL:OK] /content/runs_local/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_123 -> /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_123 (files_seen=43)
Drive not mounted, so nothing to flush and unmount.
[FLUSH] Drive 已强制同步完成
[DONE] DSWD seed=123 -> /content/runs_local/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_123
[INFO] No valid checkpoint found for HDSWD seed=123; starting fresh.
[HDSWD][seed=123] epoch 001/100 | G=0.9969 D=2.7356 SW=0.9969 DIV=0.0716 MAC=0.1543 MB_time=0.0356s
[HDSWD][seed=123] epoch 002/100 | G=0.5902 D=0.8286 SW=0.5902 DIV=0.0702 MAC=0.1527 MB_time=0.0353s
[HDSWD][seed=123] epoch 003/100 | G=0.5398 D=1.1141 SW=0.5398 DIV=0.0734 MAC=0.1523 MB_time=0.0355s
[HDSWD][seed=123] epoch 004/100 | G=0.6330 D=0.9218 SW=0.6330 DIV=0.0779 MAC=0.1527 MB_time=0.0359s
[HDSWD][seed=123] epoch 005/100 | G=0.9703 D=0.9876 SW=0.9703 DIV=0.1029 MAC=0.1579 MB_time=0.0354s
[HDSWD][seed=123] epoch 006/100 | G=0.7849 D=0.9889 SW=0.7849 DIV=0.1190 MAC=0.1605 MB_time=0.0356s
[HDSWD][seed=123] epoch 007/100 | G=0.8055 D=0.9036 SW=0.8055 DIV=0.1236 MAC=0.1608 MB_time=0.0355s
[HDSWD][seed=123] epoch 008/100 | G=0.8516 D=0.9123 SW=0.8516 DIV=0.1348 MAC=0.1624 MB_time=0.0355s
[HDSWD][seed=123] epoch 009/100 | G=0.9189 D=0.8171 SW=0.9189 DIV=0.1367 MAC=0.1619 MB_time=0.0357s
[HDSWD][seed=123] epoch 010/100 | G=0.9620 D=0.8305 SW=0.9620 DIV=0.1543 MAC=0.1658 MB_time=0.0355s
  eval: {'fid': 284.9624226157605, 'kid_mean': 0.27158268928527834, 'kid_std': 0.00231704961497829}
[SYNC-RESUME] HDSWD seed=123 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_123 (count=4)
[SYNC-RESUME] HDSWD seed=123 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_123 (count=4)
[HDSWD][seed=123] epoch 011/100 | G=0.8431 D=0.8860 SW=0.8431 DIV=0.1513 MAC=0.1637 MB_time=0.0355s
[HDSWD][seed=123] epoch 012/100 | G=0.7856 D=0.8982 SW=0.7856 DIV=0.1453 MAC=0.1622 MB_time=0.0355s
[HDSWD][seed=123] epoch 013/100 | G=0.6877 D=0.8913 SW=0.6877 DIV=0.1330 MAC=0.1597 MB_time=0.0354s
[HDSWD][seed=123] epoch 014/100 | G=0.6527 D=0.8770 SW=0.6527 DIV=0.1243 MAC=0.1573 MB_time=0.0355s
[HDSWD][seed=123] epoch 015/100 | G=0.5662 D=0.9606 SW=0.5662 DIV=0.1169 MAC=0.1560 MB_time=0.0355s
[HDSWD][seed=123] epoch 016/100 | G=0.5953 D=0.9087 SW=0.5953 DIV=0.1140 MAC=0.1549 MB_time=0.0354s
[HDSWD][seed=123] epoch 017/100 | G=0.5499 D=0.9349 SW=0.5499 DIV=0.1079 MAC=0.1530 MB_time=0.0353s
[HDSWD][seed=123] epoch 018/100 | G=0.5140 D=1.0160 SW=0.5140 DIV=0.0961 MAC=0.1506 MB_time=0.0354s
[HDSWD][seed=123] epoch 019/100 | G=0.6500 D=0.8386 SW=0.6500 DIV=0.1023 MAC=0.1517 MB_time=0.0356s
[HDSWD][seed=123] epoch 020/100 | G=0.6373 D=0.8954 SW=0.6373 DIV=0.1092 MAC=0.1536 MB_time=0.0355s
  eval: {'fid': 195.966670147779, 'kid_mean': 0.16789676427841185, 'kid_std': 0.0016768601118838584}
[SYNC-RESUME] HDSWD seed=123 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_123 (count=4)
[SYNC-RESUME] HDSWD seed=123 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_123 (count=4)
[HDSWD][seed=123] epoch 021/100 | G=0.7488 D=0.8062 SW=0.7488 DIV=0.1131 MAC=0.1541 MB_time=0.0358s
[HDSWD][seed=123] epoch 022/100 | G=0.6548 D=0.8980 SW=0.6548 DIV=0.1229 MAC=0.1561 MB_time=0.0355s
[HDSWD][seed=123] epoch 023/100 | G=2.7802 D=0.2279 SW=2.7802 DIV=0.1954 MAC=0.1695 MB_time=0.0355s
[HDSWD][seed=123] epoch 024/100 | G=1.4143 D=0.8678 SW=1.4143 DIV=0.3324 MAC=0.1928 MB_time=0.0354s
[HDSWD][seed=123] epoch 025/100 | G=0.8083 D=0.8370 SW=0.8083 DIV=0.2399 MAC=0.1784 MB_time=0.0356s
[HDSWD][seed=123] epoch 026/100 | G=0.9543 D=0.6722 SW=0.9543 DIV=0.1919 MAC=0.1701 MB_time=0.0358s
[HDSWD][seed=123] epoch 027/100 | G=0.7228 D=0.9008 SW=0.7228 DIV=0.1589 MAC=0.1640 MB_time=0.0357s
[HDSWD][seed=123] epoch 028/100 | G=0.7172 D=0.6991 SW=0.7172 DIV=0.1304 MAC=0.1582 MB_time=0.0355s
[HDSWD][seed=123] epoch 029/100 | G=0.6565 D=0.8879 SW=0.6565 DIV=0.1247 MAC=0.1569 MB_time=0.0358s
[HDSWD][seed=123] epoch 030/100 | G=0.7948 D=0.6717 SW=0.7948 DIV=0.1155 MAC=0.1549 MB_time=0.0357s
  eval: {'fid': 185.05576627117907, 'kid_mean': 0.15486565589904785, 'kid_std': 0.00173366249505772}
[SYNC-RESUME] HDSWD seed=123 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_123 (count=4)
[SYNC-RESUME] HDSWD seed=123 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_123 (count=4)
[HDSWD][seed=123] epoch 031/100 | G=0.8099 D=0.7349 SW=0.8099 DIV=0.1308 MAC=0.1578 MB_time=0.0357s
[HDSWD][seed=123] epoch 032/100 | G=0.9370 D=0.6640 SW=0.9370 DIV=0.1266 MAC=0.1571 MB_time=0.0359s
[HDSWD][seed=123] epoch 033/100 | G=0.6365 D=0.7557 SW=0.6365 DIV=0.1280 MAC=0.1575 MB_time=0.0356s
[HDSWD][seed=123] epoch 034/100 | G=0.7296 D=0.7092 SW=0.7296 DIV=0.1183 MAC=0.1559 MB_time=0.0356s
[HDSWD][seed=123] epoch 035/100 | G=1.4108 D=0.5873 SW=1.4108 DIV=0.1329 MAC=0.1586 MB_time=0.0356s
[HDSWD][seed=123] epoch 036/100 | G=3.5909 D=0.0456 SW=3.5909 DIV=0.2598 MAC=0.1814 MB_time=0.0355s
[HDSWD][seed=123] epoch 037/100 | G=2.1071 D=0.5007 SW=2.1071 DIV=0.3912 MAC=0.2029 MB_time=0.0355s

In [24]:
# @title
# Summarize results (best checkpoint and final epoch)
from pathlib import Path
import pandas as pd

base = experiment_root(cfg)
rows_best = []
rows_final = []

for mode_dir in base.iterdir():
    if not mode_dir.is_dir():
        continue
    for seed_dir in mode_dir.iterdir():
        eval_csv = seed_dir / "logs" / "eval_history.csv"
        if not eval_csv.exists():
            continue
        df = pd.read_csv(eval_csv)
        if len(df) == 0:
            continue

        best = df.loc[df["fid"].idxmin()].copy()
        final = df.sort_values("epoch").iloc[-1].copy()

        best["seed"] = seed_dir.name
        final["seed"] = seed_dir.name
        rows_best.append(best)
        rows_final.append(final)

best_df = pd.DataFrame(rows_best).sort_values("fid").reset_index(drop=True)
final_df = pd.DataFrame(rows_final).sort_values("fid").reset_index(drop=True)

print("=== Best over training ===")
display(best_df)

print("\n=== Final epoch ===")
display(final_df)

=== Best over training ===

   epoch      seed       mode        fid  kid_mean   kid_std
0    100   seed_42    HSW_DSW  54.988746  0.037053  0.001283
1    100   seed_42      HDSWD  58.694691  0.041272  0.001359
2    100  seed_123       DSWD  58.962416  0.041094  0.001454
3    100   seed_42  HSW_HDSWD  59.506497  0.042151  0.001299
4    100   seed_42       DSWD  62.531611  0.043902  0.001393
5    100  seed_123    HSW_DSW  71.982316  0.054797  0.001448
6    100  seed_123  HSW_HDSWD  77.625569  0.057942  0.001832
7     90  seed_123      HDSWD  83.118562  0.044150  0.001078

=== Final epoch ===

   epoch      seed       mode         fid  kid_mean   kid_std
0    100   seed_42    HSW_DSW   54.988746  0.037053  0.001283
1    100   seed_42      HDSWD   58.694691  0.041272  0.001359
2    100  seed_123       DSWD   58.962416  0.041094  0.001454
3    100   seed_42  HSW_HDSWD   59.506497  0.042151  0.001299
4    100   seed_42       DSWD   62.531611  0.043902  0.001393
5    100  seed_123    HSW_DSW   71.982316  0.054797  0.001448
6    100  seed_123  HSW_HDSWD   77.625569  0.057942  0.001832
7    100  seed_123      HDSWD  249.245444  0.224762  0.002766

In [25]:
# @title
# Run four structured modes with two switches:
# DSWD (none), HDSWD (projector only), HSW_DSW (slicer only), HSW_HDSWD (both)

cfg = TrainConfig()

cfg.output_root = "/content/runs_local"
cfg.drive_output_root = "/content/drive/MyDrive/cifar10_dsw_runs" if os.path.exists("/content/drive/MyDrive") else "./runs_drive_backup"
cfg.fidelity_cache_root = "/content/fidelity_cache_local"

cfg.p = 2
cfg.seeds = (40,)
cfg.modes = ("DSWD", "HDSWD", "HSW_DSW", "HSW_HDSWD")

cfg.epochs = 100
cfg.eval_every = 10
cfg.sample_every = 5
cfg.run_tag = "bs512_structured_four_modes_v1"

cfg.latent_size = 100
cfg.lr_g = 5e-4
cfg.lr_d = 5e-4
cfg.lr_t = 1e-4

cfg.num_projections = 256
cfg.selector_steps = 1
cfg.use_diversity_reg = True
cfg.diversity_weight = 10.0

cfg.h_num_base = 128
cfg.h_num_bottleneck = 32
cfg.h_base_rank = 512
cfg.h_bottleneck_diversity_weight = 5.0
cfg.h_mix_act = "linear"

cfg.hsw_slicer_dims = (512, 128)
cfg.hsw_slicer_act = "linear"
cfg.hsw_proj_rank = 0

cfg.drive_backup_every = 10
cfg.drive_backup_on_eval = True
cfg.final_full_sync_to_drive = True
cfg.sync_history_on_backup = True
cfg.sync_eval_history_on_backup = True
cfg.sync_samples_on_backup = False
cfg.sync_eval_ckpts_on_backup = False

cfg.resume_if_possible = True
cfg.autoskip_complete = True

print("Experiment root:", experiment_root(cfg))
train_all(cfg)

Experiment root: /content/runs_local/cifar10_dsw_v2/bs512_structured_four_modes_v1
[INFO] No valid checkpoint found for DSWD seed=40; starting fresh.
[DSWD][seed=40] epoch 001/100 | G=1.0928 D=5.6909 SW=1.0928 DIV=0.1328 MAC=0.3533 MB_time=0.0394s
[DSWD][seed=40] epoch 002/100 | G=0.8287 D=0.9026 SW=0.8287 DIV=0.0237 MAC=0.1493 MB_time=0.0392s
[DSWD][seed=40] epoch 003/100 | G=1.2265 D=0.9969 SW=1.2265 DIV=0.0199 MAC=0.1333 MB_time=0.0394s
[DSWD][seed=40] epoch 004/100 | G=1.1336 D=1.1002 SW=1.1336 DIV=0.0274 MAC=0.1566 MB_time=0.0396s
[DSWD][seed=40] epoch 005/100 | G=1.1392 D=0.9847 SW=1.1392 DIV=0.0263 MAC=0.1530 MB_time=0.0395s
[DSWD][seed=40] epoch 006/100 | G=1.4028 D=0.8639 SW=1.4028 DIV=0.0320 MAC=0.1702 MB_time=0.0393s
[DSWD][seed=40] epoch 007/100 | G=1.5030 D=0.7470 SW=1.5030 DIV=0.0354 MAC=0.1801 MB_time=0.0395s
[DSWD][seed=40] epoch 008/100 | G=1.4147 D=0.8003 SW=1.4147 DIV=0.0361 MAC=0.1823 MB_time=0.0394s
[DSWD][seed=40] epoch 009/100 | G=1.3394 D=0.7885 SW=1.3394 DIV=0.0340 MAC=0.1766 MB_time=0.0395s
[DSWD][seed=40] epoch 010/100 | G=0.9263 D=0.9055 SW=0.9263 DIV=0.0260 MAC=0.1527 MB_time=0.0395s
  eval: {'fid': 216.71423362184598, 'kid_mean': 0.18579277992248536, 'kid_std': 0.002071229389546993}
[SYNC-RESUME] DSWD seed=40 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_40 (count=4)
[SYNC-RESUME] DSWD seed=40 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_40 (count=4)
[DSWD][seed=40] epoch 011/100 | G=0.8442 D=0.8927 SW=0.8442 DIV=0.0208 MAC=0.1357 MB_time=0.0392s
[DSWD][seed=40] epoch 012/100 | G=0.8327 D=0.8551 SW=0.8327 DIV=0.0199 MAC=0.1323 MB_time=0.0391s
[DSWD][seed=40] epoch 013/100 | G=0.8445 D=0.8979 SW=0.8445 DIV=0.0196 MAC=0.1309 MB_time=0.0392s
[DSWD][seed=40] epoch 014/100 | G=0.8091 D=0.8856 SW=0.8091 DIV=0.0189 MAC=0.1284 MB_time=0.0391s
[DSWD][seed=40] epoch 015/100 | G=0.8249 D=0.8833 SW=0.8249 DIV=0.0193 MAC=0.1298 MB_time=0.0392s
[DSWD][seed=40] epoch 016/100 | G=0.9559 D=0.8269 SW=0.9559 DIV=0.0219 MAC=0.1393 MB_time=0.0394s
[DSWD][seed=40] epoch 017/100 | G=0.8381 D=0.8436 SW=0.8381 DIV=0.0200 MAC=0.1322 MB_time=0.0392s
[DSWD][seed=40] epoch 018/100 | G=2.8576 D=0.3973 SW=2.8576 DIV=0.0432 MAC=0.1881 MB_time=0.0392s
[DSWD][seed=40] epoch 019/100 | G=2.3622 D=0.4751 SW=2.3622 DIV=0.0781 MAC=0.2696 MB_time=0.0392s
[DSWD][seed=40] epoch 020/100 | G=1.2721 D=0.7549 SW=1.2721 DIV=0.0384 MAC=0.1863 MB_time=0.0393s
  eval: {'fid': 195.2816256399393, 'kid_mean': 0.161615252494812, 'kid_std': 0.0017353390562840798}
[SYNC-RESUME] DSWD seed=40 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_40 (count=4)
[SYNC-RESUME] DSWD seed=40 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_40 (count=4)
[DSWD][seed=40] epoch 021/100 | G=0.9622 D=0.7439 SW=0.9622 DIV=0.0240 MAC=0.1446 MB_time=0.0393s
[DSWD][seed=40] epoch 022/100 | G=0.8601 D=0.8030 SW=0.8601 DIV=0.0213 MAC=0.1349 MB_time=0.0394s
[DSWD][seed=40] epoch 023/100 | G=0.9634 D=0.7565 SW=0.9634 DIV=0.0199 MAC=0.1295 MB_time=0.0393s
[DSWD][seed=40] epoch 024/100 | G=0.8903 D=0.8111 SW=0.8903 DIV=0.0210 MAC=0.1331 MB_time=0.0393s
[DSWD][seed=40] epoch 025/100 | G=0.8982 D=0.6902 SW=0.8982 DIV=0.0210 MAC=0.1329 MB_time=0.0392s
[DSWD][seed=40] epoch 026/100 | G=1.4603 D=0.5405 SW=1.4603 DIV=0.0242 MAC=0.1425 MB_time=0.0393s
[DSWD][seed=40] epoch 027/100 | G=3.4626 D=0.0429 SW=3.4626 DIV=0.0709 MAC=0.2567 MB_time=0.0393s
[DSWD][seed=40] epoch 028/100 | G=1.2261 D=0.7717 SW=1.2261 DIV=0.0490 MAC=0.2082 MB_time=0.0393s
[DSWD][seed=40] epoch 029/100 | G=1.0544 D=0.7133 SW=1.0544 DIV=0.0282 MAC=0.1556 MB_time=0.0394s
[DSWD][seed=40] epoch 030/100 | G=1.0220 D=0.6471 SW=1.0220 DIV=0.0253 MAC=0.1459 MB_time=0.0392s
  eval: {'fid': 189.1831832239613, 'kid_mean': 0.1614030647277832, 'kid_std': 0.002044499802453686}
[SYNC-RESUME] DSWD seed=40 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_40 (count=4)
[SYNC-RESUME] DSWD seed=40 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_40 (count=4)
[DSWD][seed=40] epoch 031/100 | G=0.8413 D=0.6996 SW=0.8413 DIV=0.0217 MAC=0.1340 MB_time=0.0392s
[DSWD][seed=40] epoch 032/100 | G=1.0031 D=0.6624 SW=1.0031 DIV=0.0224 MAC=0.1364 MB_time=0.0391s
[DSWD][seed=40] epoch 033/100 | G=1.4309 D=0.5842 SW=1.4309 DIV=0.0313 MAC=0.1634 MB_time=0.0392s
[DSWD][seed=40] epoch 034/100 | G=0.7909 D=0.7555 SW=0.7909 DIV=0.0219 MAC=0.1332 MB_time=0.0391s
[DSWD][seed=40] epoch 035/100 | G=0.8621 D=0.8691 SW=0.8621 DIV=0.0201 MAC=0.1263 MB_time=0.0394s
[DSWD][seed=40] epoch 036/100 | G=0.6573 D=0.6544 SW=0.6573 DIV=0.0155 MAC=0.1090 MB_time=0.0394s
[DSWD][seed=40] epoch 037/100 | G=1.0679 D=0.5256 SW=1.0679 DIV=0.0237 MAC=0.1392 MB_time=0.0392s
[DSWD][seed=40] epoch 038/100 | G=0.8422 D=0.7189 SW=0.8422 DIV=0.0207 MAC=0.1290 MB_time=0.0393s
[DSWD][seed=40] epoch 039/100 | G=1.1544 D=0.5864 SW=1.1544 DIV=0.0226 MAC=0.1341 MB_time=0.0397s
[DSWD][seed=40] epoch 040/100 | G=1.3524 D=0.4598 SW=1.3524 DIV=0.0292 MAC=0.1551 MB_time=0.0392s
  eval: {'fid': 183.2296628295445, 'kid_mean': 0.15298790454864503, 'kid_std': 0.0019783842470044643}
[SYNC-RESUME] DSWD seed=40 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_40 (count=4)
[SYNC-RESUME] DSWD seed=40 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_40 (count=4)
[DSWD][seed=40] epoch 041/100 | G=1.0708 D=0.5386 SW=1.0708 DIV=0.0293 MAC=0.1560 MB_time=0.0393s
[DSWD][seed=40] epoch 042/100 | G=0.9966 D=0.6986 SW=0.9966 DIV=0.0259 MAC=0.1452 MB_time=0.0391s
[DSWD][seed=40] epoch 043/100 | G=1.0309 D=0.5984 SW=1.0309 DIV=0.0244 MAC=0.1400 MB_time=0.0395s
[DSWD][seed=40] epoch 044/100 | G=0.9507 D=0.5869 SW=0.9507 DIV=0.0219 MAC=0.1316 MB_time=0.0393s
[DSWD][seed=40] epoch 045/100 | G=0.7708 D=0.6995 SW=0.7708 DIV=0.0212 MAC=0.1290 MB_time=0.0392s
[DSWD][seed=40] epoch 046/100 | G=2.5624 D=0.1013 SW=2.5624 DIV=0.0418 MAC=0.1841 MB_time=0.0392s
[DSWD][seed=40] epoch 047/100 | G=2.6113 D=0.3514 SW=2.6113 DIV=0.0714 MAC=0.2553 MB_time=0.0392s
[DSWD][seed=40] epoch 048/100 | G=1.0080 D=0.4227 SW=1.0080 DIV=0.0352 MAC=0.1715 MB_time=0.0392s
[DSWD][seed=40] epoch 049/100 | G=0.8094 D=0.6898 SW=0.8094 DIV=0.0241 MAC=0.1385 MB_time=0.0392s
[DSWD][seed=40] epoch 050/100 | G=0.7252 D=0.6695 SW=0.7252 DIV=0.0194 MAC=0.1222 MB_time=0.0392s
  eval: {'fid': 141.41017741785396, 'kid_mean': 0.10968153715133667, 'kid_std': 0.0018709266504879235}
[SYNC-RESUME] DSWD seed=40 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_40 (count=4)
[SYNC-RESUME] DSWD seed=40 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_40 (count=4)
[DSWD][seed=40] epoch 051/100 | G=0.6799 D=0.6641 SW=0.6799 DIV=0.0174 MAC=0.1151 MB_time=0.0394s
[DSWD][seed=40] epoch 052/100 | G=0.6983 D=0.6301 SW=0.6983 DIV=0.0177 MAC=0.1164 MB_time=0.0393s
[DSWD][seed=40] epoch 053/100 | G=0.7653 D=0.4887 SW=0.7653 DIV=0.0179 MAC=0.1172 MB_time=0.0392s
[DSWD][seed=40] epoch 054/100 | G=0.9292 D=0.6830 SW=0.9292 DIV=0.0203 MAC=0.1262 MB_time=0.0392s
[DSWD][seed=40] epoch 055/100 | G=0.6044 D=0.7806 SW=0.6044 DIV=0.0168 MAC=0.1128 MB_time=0.0392s
[DSWD][seed=40] epoch 056/100 | G=0.7684 D=0.5633 SW=0.7684 DIV=0.0170 MAC=0.1138 MB_time=0.0392s
[DSWD][seed=40] epoch 057/100 | G=0.7766 D=0.5300 SW=0.7766 DIV=0.0192 MAC=0.1225 MB_time=0.0392s
[DSWD][seed=40] epoch 058/100 | G=0.8173 D=0.5284 SW=0.8173 DIV=0.0184 MAC=0.1191 MB_time=0.0393s
[DSWD][seed=40] epoch 059/100 | G=0.9272 D=0.4767 SW=0.9272 DIV=0.0192 MAC=0.1219 MB_time=0.0392s
[DSWD][seed=40] epoch 060/100 | G=2.2583 D=0.0893 SW=2.2583 DIV=0.0505 MAC=0.2106 MB_time=0.0392s
  eval: {'fid': 177.76037398853376, 'kid_mean': 0.15900195598602296, 'kid_std': 0.001964752928346347}
[SYNC-RESUME] DSWD seed=40 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_40 (count=4)
[SYNC-RESUME] DSWD seed=40 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_40 (count=4)
[DSWD][seed=40] epoch 061/100 | G=1.0978 D=0.4999 SW=1.0978 DIV=0.0320 MAC=0.1634 MB_time=0.0392s
[DSWD][seed=40] epoch 062/100 | G=0.7691 D=0.4871 SW=0.7691 DIV=0.0221 MAC=0.1322 MB_time=0.0393s
[DSWD][seed=40] epoch 063/100 | G=0.6004 D=0.9774 SW=0.6004 DIV=0.0155 MAC=0.1071 MB_time=0.0392s
[DSWD][seed=40] epoch 064/100 | G=0.7871 D=0.4590 SW=0.7871 DIV=0.0172 MAC=0.1137 MB_time=0.0392s
[DSWD][seed=40] epoch 065/100 | G=0.6704 D=0.5882 SW=0.6704 DIV=0.0160 MAC=0.1090 MB_time=0.0391s
[DSWD][seed=40] epoch 066/100 | G=0.7259 D=0.4480 SW=0.7259 DIV=0.0167 MAC=0.1116 MB_time=0.0392s
[DSWD][seed=40] epoch 067/100 | G=0.6390 D=0.7609 SW=0.6390 DIV=0.0149 MAC=0.1042 MB_time=0.0392s
[DSWD][seed=40] epoch 068/100 | G=1.7446 D=0.1461 SW=1.7446 DIV=0.0283 MAC=0.1479 MB_time=0.0392s
[DSWD][seed=40] epoch 069/100 | G=2.5093 D=0.0804 SW=2.5093 DIV=0.0590 MAC=0.2303 MB_time=0.0391s
[DSWD][seed=40] epoch 070/100 | G=0.9528 D=0.3993 SW=0.9528 DIV=0.0350 MAC=0.1704 MB_time=0.0392s
  eval: {'fid': 117.79307925813299, 'kid_mean': 0.0798414134979248, 'kid_std': 0.001458038641314217}
[SYNC-RESUME] DSWD seed=40 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_40 (count=4)
[SYNC-RESUME] DSWD seed=40 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_40 (count=4)
[DSWD][seed=40] epoch 071/100 | G=0.8710 D=0.3815 SW=0.8710 DIV=0.0228 MAC=0.1336 MB_time=0.0393s
[DSWD][seed=40] epoch 072/100 | G=0.8338 D=0.4570 SW=0.8338 DIV=0.0211 MAC=0.1272 MB_time=0.0392s
[DSWD][seed=40] epoch 073/100 | G=0.7626 D=0.4734 SW=0.7626 DIV=0.0177 MAC=0.1147 MB_time=0.0391s
[DSWD][seed=40] epoch 074/100 | G=0.8136 D=0.5423 SW=0.8136 DIV=0.0187 MAC=0.1183 MB_time=0.0392s
[DSWD][seed=40] epoch 075/100 | G=0.7656 D=0.3914 SW=0.7656 DIV=0.0189 MAC=0.1194 MB_time=0.0393s
[DSWD][seed=40] epoch 076/100 | G=0.5192 D=1.3906 SW=0.5192 DIV=0.0139 MAC=0.0991 MB_time=0.0393s
[DSWD][seed=40] epoch 077/100 | G=0.5286 D=0.4921 SW=0.5286 DIV=0.0116 MAC=0.0895 MB_time=0.0392s
[DSWD][seed=40] epoch 078/100 | G=0.5636 D=0.4902 SW=0.5636 DIV=0.0122 MAC=0.0921 MB_time=0.0392s
[DSWD][seed=40] epoch 079/100 | G=0.5038 D=1.0529 SW=0.5038 DIV=0.0115 MAC=0.0885 MB_time=0.0392s
[DSWD][seed=40] epoch 080/100 | G=0.5875 D=0.4400 SW=0.5875 DIV=0.0116 MAC=0.0890 MB_time=0.0395s
  eval: {'fid': 101.30467573695586, 'kid_mean': 0.06496525287628174, 'kid_std': 0.0014526697235783864}
[SYNC-RESUME] DSWD seed=40 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_40 (count=4)
[SYNC-RESUME] DSWD seed=40 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_40 (count=4)
[DSWD][seed=40] epoch 081/100 | G=0.6460 D=0.4129 SW=0.6460 DIV=0.0134 MAC=0.0966 MB_time=0.0392s
[DSWD][seed=40] epoch 082/100 | G=1.2473 D=0.2783 SW=1.2473 DIV=0.0206 MAC=0.1223 MB_time=0.0392s
[DSWD][seed=40] epoch 083/100 | G=1.7912 D=0.1091 SW=1.7912 DIV=0.0457 MAC=0.1974 MB_time=0.0392s
[DSWD][seed=40] epoch 084/100 | G=0.8669 D=0.3054 SW=0.8669 DIV=0.0252 MAC=0.1397 MB_time=0.0391s
[DSWD][seed=40] epoch 085/100 | G=0.5839 D=0.9757 SW=0.5839 DIV=0.0155 MAC=0.1047 MB_time=0.0392s
[DSWD][seed=40] epoch 086/100 | G=0.7283 D=0.3680 SW=0.7283 DIV=0.0158 MAC=0.1057 MB_time=0.0392s
[DSWD][seed=40] epoch 087/100 | G=0.7802 D=0.4059 SW=0.7802 DIV=0.0169 MAC=0.1100 MB_time=0.0393s
[DSWD][seed=40] epoch 088/100 | G=0.7535 D=0.4720 SW=0.7535 DIV=0.0180 MAC=0.1142 MB_time=0.0392s
[DSWD][seed=40] epoch 089/100 | G=0.6308 D=0.3918 SW=0.6308 DIV=0.0151 MAC=0.1031 MB_time=0.0392s
[DSWD][seed=40] epoch 090/100 | G=0.7947 D=0.8008 SW=0.7947 DIV=0.0170 MAC=0.1101 MB_time=0.0392s
  eval: {'fid': 97.11796300448714, 'kid_mean': 0.05991882085800171, 'kid_std': 0.0012735969108434264}
[SYNC-RESUME] DSWD seed=40 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_40 (count=4)
[SYNC-RESUME] DSWD seed=40 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_40 (count=4)
[DSWD][seed=40] epoch 091/100 | G=0.4776 D=0.6246 SW=0.4776 DIV=0.0123 MAC=0.0912 MB_time=0.0394s
[DSWD][seed=40] epoch 092/100 | G=0.6915 D=0.5682 SW=0.6915 DIV=0.0143 MAC=0.0991 MB_time=0.0392s
[DSWD][seed=40] epoch 093/100 | G=0.5337 D=0.4649 SW=0.5337 DIV=0.0121 MAC=0.0904 MB_time=0.0394s
[DSWD][seed=40] epoch 094/100 | G=0.5397 D=0.6055 SW=0.5397 DIV=0.0116 MAC=0.0880 MB_time=0.0392s
[DSWD][seed=40] epoch 095/100 | G=0.7139 D=0.2431 SW=0.7139 DIV=0.0145 MAC=0.0998 MB_time=0.0393s
[DSWD][seed=40] epoch 096/100 | G=0.5883 D=0.5663 SW=0.5883 DIV=0.0145 MAC=0.0998 MB_time=0.0391s
[DSWD][seed=40] epoch 097/100 | G=1.7245 D=0.0440 SW=1.7245 DIV=0.0303 MAC=0.1520 MB_time=0.0392s
[DSWD][seed=40] epoch 098/100 | G=1.9501 D=0.1308 SW=1.9501 DIV=0.0507 MAC=0.2093 MB_time=0.0393s
[DSWD][seed=40] epoch 099/100 | G=0.7938 D=0.1756 SW=0.7938 DIV=0.0253 MAC=0.1387 MB_time=0.0392s
[DSWD][seed=40] epoch 100/100 | G=0.7716 D=0.3987 SW=0.7716 DIV=0.0198 MAC=0.1195 MB_time=0.0392s
  eval: {'fid': 62.489474215944654, 'kid_mean': 0.043350329399108885, 'kid_std': 0.0012621521144936165}
[SYNC-RESUME] DSWD seed=40 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_40 (count=4)
[SYNC-RESUME] DSWD seed=40 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_40 (count=4)
[SYNC-RESUME] DSWD seed=40 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_40 (count=5)
[SYNC-FULL:OK] /content/runs_local/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_40 -> /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_40 (files_seen=43)
Drive not mounted, so nothing to flush and unmount.
[FLUSH] Drive 已强制同步完成
[DONE] DSWD seed=40 -> /content/runs_local/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_40
[INFO] No valid checkpoint found for HDSWD seed=40; starting fresh.
[HDSWD][seed=40] epoch 001/100 | G=0.7873 D=2.4493 SW=0.7873 DIV=0.0751 MAC=0.1564 MB_time=0.0358s
[HDSWD][seed=40] epoch 002/100 | G=0.5728 D=0.7191 SW=0.5728 DIV=0.0716 MAC=0.1537 MB_time=0.0359s
[HDSWD][seed=40] epoch 003/100 | G=0.7524 D=1.0161 SW=0.7524 DIV=0.0764 MAC=0.1535 MB_time=0.0355s
[HDSWD][seed=40] epoch 004/100 | G=0.4472 D=1.0597 SW=0.4472 DIV=0.0830 MAC=0.1540 MB_time=0.0354s
[HDSWD][seed=40] epoch 005/100 | G=0.5971 D=1.0512 SW=0.5971 DIV=0.0896 MAC=0.1544 MB_time=0.0355s
[HDSWD][seed=40] epoch 006/100 | G=0.6464 D=1.0703 SW=0.6464 DIV=0.1010 MAC=0.1562 MB_time=0.0354s
[HDSWD][seed=40] epoch 007/100 | G=0.7114 D=0.9993 SW=0.7114 DIV=0.1076 MAC=0.1567 MB_time=0.0355s
[HDSWD][seed=40] epoch 008/100 | G=0.8408 D=0.9269 SW=0.8408 DIV=0.1223 MAC=0.1592 MB_time=0.0355s
[HDSWD][seed=40] epoch 009/100 | G=0.7530 D=0.8854 SW=0.7530 DIV=0.1294 MAC=0.1605 MB_time=0.0354s
[HDSWD][seed=40] epoch 010/100 | G=0.7645 D=0.9395 SW=0.7645 DIV=0.1312 MAC=0.1600 MB_time=0.0356s
  eval: {'fid': 290.4997945823892, 'kid_mean': 0.27581980228424074, 'kid_std': 0.002063059922270659}
[SYNC-RESUME] HDSWD seed=40 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_40 (count=4)
[SYNC-RESUME] HDSWD seed=40 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_40 (count=4)
[HDSWD][seed=40] epoch 011/100 | G=0.6494 D=0.9298 SW=0.6494 DIV=0.1332 MAC=0.1598 MB_time=0.0357s
[HDSWD][seed=40] epoch 012/100 | G=0.5717 D=0.9749 SW=0.5717 DIV=0.1204 MAC=0.1565 MB_time=0.0355s
[HDSWD][seed=40] epoch 013/100 | G=0.5604 D=0.9870 SW=0.5604 DIV=0.1187 MAC=0.1560 MB_time=0.0356s
[HDSWD][seed=40] epoch 014/100 | G=0.5528 D=0.9489 SW=0.5528 DIV=0.1074 MAC=0.1532 MB_time=0.0357s
[HDSWD][seed=40] epoch 015/100 | G=0.5011 D=0.9533 SW=0.5011 DIV=0.1016 MAC=0.1522 MB_time=0.0355s
[HDSWD][seed=40] epoch 016/100 | G=0.4881 D=0.9949 SW=0.4881 DIV=0.1010 MAC=0.1516 MB_time=0.0354s
[HDSWD][seed=40] epoch 017/100 | G=0.4754 D=0.9787 SW=0.4754 DIV=0.0927 MAC=0.1500 MB_time=0.0358s
[HDSWD][seed=40] epoch 018/100 | G=0.4275 D=1.0352 SW=0.4275 DIV=0.0880 MAC=0.1487 MB_time=0.0357s
[HDSWD][seed=40] epoch 019/100 | G=0.4036 D=1.0742 SW=0.4036 DIV=0.0826 MAC=0.1472 MB_time=0.0355s
[HDSWD][seed=40] epoch 020/100 | G=0.3852 D=0.9941 SW=0.3852 DIV=0.0816 MAC=0.1466 MB_time=0.0357s
  eval: {'fid': 174.90261536521922, 'kid_mean': 0.1443219304084778, 'kid_std': 0.001603301872152666}
[SYNC-RESUME] HDSWD seed=40 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_40 (count=4)
[SYNC-RESUME] HDSWD seed=40 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_40 (count=4)
[HDSWD][seed=40] epoch 021/100 | G=0.4025 D=1.0290 SW=0.4025 DIV=0.0801 MAC=0.1465 MB_time=0.0355s
[HDSWD][seed=40] epoch 022/100 | G=0.4196 D=1.0149 SW=0.4196 DIV=0.0776 MAC=0.1459 MB_time=0.0356s
[HDSWD][seed=40] epoch 023/100 | G=0.4348 D=0.9719 SW=0.4348 DIV=0.0780 MAC=0.1463 MB_time=0.0354s
[HDSWD][seed=40] epoch 024/100 | G=0.5072 D=0.9675 SW=0.5072 DIV=0.0836 MAC=0.1475 MB_time=0.0361s
[HDSWD][seed=40] epoch 025/100 | G=0.5593 D=0.9070 SW=0.5593 DIV=0.0888 MAC=0.1488 MB_time=0.0357s
[HDSWD][seed=40] epoch 026/100 | G=0.6282 D=0.8998 SW=0.6282 DIV=0.0985 MAC=0.1511 MB_time=0.0356s
[HDSWD][seed=40] epoch 027/100 | G=0.6442 D=0.8948 SW=0.6442 DIV=0.1023 MAC=0.1522 MB_time=0.0357s
[HDSWD][seed=40] epoch 028/100 | G=0.5800 D=0.8223 SW=0.5800 DIV=0.0989 MAC=0.1520 MB_time=0.0355s
[HDSWD][seed=40] epoch 029/100 | G=0.6090 D=0.8643 SW=0.6090 DIV=0.1038 MAC=0.1533 MB_time=0.0356s
[HDSWD][seed=40] epoch 030/100 | G=0.5626 D=0.9154 SW=0.5626 DIV=0.1008 MAC=0.1527 MB_time=0.0355s
  eval: {'fid': 153.22876852640303, 'kid_mean': 0.11811677455902099, 'kid_std': 0.0015459273766840935}
[SYNC-RESUME] HDSWD seed=40 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_40 (count=4)
[SYNC-RESUME] HDSWD seed=40 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_40 (count=4)
[HDSWD][seed=40] epoch 031/100 | G=0.6890 D=0.7622 SW=0.6890 DIV=0.1013 MAC=0.1533 MB_time=0.0357s
[HDSWD][seed=40] epoch 032/100 | G=0.6188 D=0.8471 SW=0.6188 DIV=0.1115 MAC=0.1557 MB_time=0.0355s
[HDSWD][seed=40] epoch 033/100 | G=0.9203 D=0.6428 SW=0.9203 DIV=0.1106 MAC=0.1557 MB_time=0.0356s
[HDSWD][seed=40] epoch 034/100 | G=2.2825 D=0.2597 SW=2.2825 DIV=0.2478 MAC=0.1818 MB_time=0.0356s
[HDSWD][seed=40] epoch 035/100 | G=0.9635 D=0.6879 SW=0.9635 DIV=0.2341 MAC=0.1794 MB_time=0.0356s
[HDSWD][seed=40] epoch 036/100 | G=0.9816 D=0.6399 SW=0.9816 DIV=0.1820 MAC=0.1701 MB_time=0.0355s
[HDSWD][seed=40] epoch 037/100 | G=0.8582 D=0.6130 SW=0.8582 DIV=0.1471 MAC=0.1636 MB_time=0.0356s
[HDSWD][seed=40] epoch 038/100 | G=0.7338 D=0.7457 SW=0.7338 DIV=0.1356 MAC=0.1608 MB_time=0.0356s

In [26]:
# @title
# Run four structured modes with two switches:
# DSWD (none), HDSWD (projector only), HSW_DSW (slicer only), HSW_HDSWD (both)

cfg = TrainConfig()

cfg.output_root = "/content/runs_local"
cfg.drive_output_root = "/content/drive/MyDrive/cifar10_dsw_runs" if os.path.exists("/content/drive/MyDrive") else "./runs_drive_backup"
cfg.fidelity_cache_root = "/content/fidelity_cache_local"

cfg.p = 2
cfg.seeds = (2026,)
cfg.modes = ("DSWD", "HDSWD", "HSW_DSW", "HSW_HDSWD")

cfg.epochs = 100
cfg.eval_every = 10
cfg.sample_every = 5
cfg.run_tag = "bs512_structured_four_modes_v1"

cfg.latent_size = 100
cfg.lr_g = 5e-4
cfg.lr_d = 5e-4
cfg.lr_t = 1e-4

cfg.num_projections = 256
cfg.selector_steps = 1
cfg.use_diversity_reg = True
cfg.diversity_weight = 10.0

cfg.h_num_base = 128
cfg.h_num_bottleneck = 32
cfg.h_base_rank = 512
cfg.h_bottleneck_diversity_weight = 5.0
cfg.h_mix_act = "linear"

cfg.hsw_slicer_dims = (512, 128)
cfg.hsw_slicer_act = "linear"
cfg.hsw_proj_rank = 0

cfg.drive_backup_every = 10
cfg.drive_backup_on_eval = True
cfg.final_full_sync_to_drive = True
cfg.sync_history_on_backup = True
cfg.sync_eval_history_on_backup = True
cfg.sync_samples_on_backup = False
cfg.sync_eval_ckpts_on_backup = False

cfg.resume_if_possible = True
cfg.autoskip_complete = True

print("Experiment root:", experiment_root(cfg))
train_all(cfg)

Experiment root: /content/runs_local/cifar10_dsw_v2/bs512_structured_four_modes_v1
[INFO] No valid checkpoint found for DSWD seed=2026; starting fresh.
[DSWD][seed=2026] epoch 001/100 | G=0.8839 D=1.6723 SW=0.8839 DIV=0.1204 MAC=0.3334 MB_time=0.0393s
[DSWD][seed=2026] epoch 002/100 | G=0.7822 D=0.8189 SW=0.7822 DIV=0.0143 MAC=0.1128 MB_time=0.0392s
[DSWD][seed=2026] epoch 003/100 | G=1.0118 D=1.0988 SW=1.0118 DIV=0.0149 MAC=0.1101 MB_time=0.0395s
[DSWD][seed=2026] epoch 004/100 | G=1.3269 D=1.0134 SW=1.3269 DIV=0.0282 MAC=0.1560 MB_time=0.0392s
[DSWD][seed=2026] epoch 005/100 | G=1.3494 D=0.9831 SW=1.3494 DIV=0.0315 MAC=0.1665 MB_time=0.0392s
[DSWD][seed=2026] epoch 006/100 | G=1.3334 D=0.9006 SW=1.3334 DIV=0.0327 MAC=0.1699 MB_time=0.0392s
[DSWD][seed=2026] epoch 007/100 | G=1.4611 D=0.7999 SW=1.4611 DIV=0.0346 MAC=0.1756 MB_time=0.0394s
[DSWD][seed=2026] epoch 008/100 | G=1.4097 D=0.8150 SW=1.4097 DIV=0.0356 MAC=0.1785 MB_time=0.0393s
[DSWD][seed=2026] epoch 009/100 | G=1.3884 D=0.7637 SW=1.3884 DIV=0.0341 MAC=0.1746 MB_time=0.0392s
[DSWD][seed=2026] epoch 010/100 | G=1.2585 D=0.7976 SW=1.2585 DIV=0.0330 MAC=0.1716 MB_time=0.0392s
  eval: {'fid': 279.5413054995946, 'kid_mean': 0.25970699787139895, 'kid_std': 0.0021465330994223336}
[SYNC-RESUME] DSWD seed=2026 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_2026 (count=4)
[SYNC-RESUME] DSWD seed=2026 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_2026 (count=4)
[DSWD][seed=2026] epoch 011/100 | G=0.8523 D=0.9203 SW=0.8523 DIV=0.0229 MAC=0.1402 MB_time=0.0392s
[DSWD][seed=2026] epoch 012/100 | G=0.9232 D=0.8531 SW=0.9232 DIV=0.0217 MAC=0.1364 MB_time=0.0392s
[DSWD][seed=2026] epoch 013/100 | G=0.8426 D=0.8580 SW=0.8426 DIV=0.0204 MAC=0.1317 MB_time=0.0392s
[DSWD][seed=2026] epoch 014/100 | G=0.7475 D=0.9721 SW=0.7475 DIV=0.0177 MAC=0.1217 MB_time=0.0392s
[DSWD][seed=2026] epoch 015/100 | G=0.8509 D=0.7996 SW=0.8509 DIV=0.0192 MAC=0.1270 MB_time=0.0392s
[DSWD][seed=2026] epoch 016/100 | G=0.7987 D=0.8822 SW=0.7987 DIV=0.0188 MAC=0.1254 MB_time=0.0392s
[DSWD][seed=2026] epoch 017/100 | G=0.8054 D=0.8540 SW=0.8054 DIV=0.0186 MAC=0.1244 MB_time=0.0392s
[DSWD][seed=2026] epoch 018/100 | G=0.8116 D=0.8150 SW=0.8116 DIV=0.0178 MAC=0.1214 MB_time=0.0393s
[DSWD][seed=2026] epoch 019/100 | G=0.9609 D=0.7911 SW=0.9609 DIV=0.0210 MAC=0.1327 MB_time=0.0392s
[DSWD][seed=2026] epoch 020/100 | G=1.1300 D=0.7467 SW=1.1300 DIV=0.0266 MAC=0.1510 MB_time=0.0393s
  eval: {'fid': 197.54406459477426, 'kid_mean': 0.17433080673217774, 'kid_std': 0.0017771343634562134}
[SYNC-RESUME] DSWD seed=2026 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_2026 (count=4)
[SYNC-RESUME] DSWD seed=2026 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_2026 (count=4)
[DSWD][seed=2026] epoch 021/100 | G=1.0500 D=0.7217 SW=1.0500 DIV=0.0217 MAC=0.1352 MB_time=0.0392s
[DSWD][seed=2026] epoch 022/100 | G=1.4501 D=0.8387 SW=1.4501 DIV=0.0395 MAC=0.1850 MB_time=0.0392s
[DSWD][seed=2026] epoch 023/100 | G=0.7181 D=0.9001 SW=0.7181 DIV=0.0157 MAC=0.1119 MB_time=0.0392s
[DSWD][seed=2026] epoch 024/100 | G=0.9146 D=0.7315 SW=0.9146 DIV=0.0197 MAC=0.1266 MB_time=0.0392s
[DSWD][seed=2026] epoch 025/100 | G=0.8045 D=0.8103 SW=0.8045 DIV=0.0183 MAC=0.1213 MB_time=0.0393s
[DSWD][seed=2026] epoch 026/100 | G=0.9413 D=0.7679 SW=0.9413 DIV=0.0219 MAC=0.1339 MB_time=0.0392s
[DSWD][seed=2026] epoch 027/100 | G=1.3197 D=0.6237 SW=1.3197 DIV=0.0276 MAC=0.1528 MB_time=0.0393s
[DSWD][seed=2026] epoch 028/100 | G=1.7351 D=0.6000 SW=1.7351 DIV=0.0406 MAC=0.1891 MB_time=0.0393s
[DSWD][seed=2026] epoch 029/100 | G=0.9810 D=0.7947 SW=0.9810 DIV=0.0267 MAC=0.1495 MB_time=0.0392s
[DSWD][seed=2026] epoch 030/100 | G=1.5080 D=0.5756 SW=1.5080 DIV=0.0276 MAC=0.1522 MB_time=0.0392s
  eval: {'fid': 149.77273876611167, 'kid_mean': 0.11874527215957642, 'kid_std': 0.0016959908628644469}
[SYNC-RESUME] DSWD seed=2026 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_2026 (count=4)
[SYNC-RESUME] DSWD seed=2026 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_2026 (count=4)
[DSWD][seed=2026] epoch 031/100 | G=1.2691 D=0.6683 SW=1.2691 DIV=0.0369 MAC=0.1784 MB_time=0.0393s
[DSWD][seed=2026] epoch 032/100 | G=0.9847 D=0.6754 SW=0.9847 DIV=0.0261 MAC=0.1474 MB_time=0.0395s
[DSWD][seed=2026] epoch 033/100 | G=0.9428 D=0.6875 SW=0.9428 DIV=0.0226 MAC=0.1356 MB_time=0.0392s
[DSWD][seed=2026] epoch 034/100 | G=2.5258 D=0.4479 SW=2.5258 DIV=0.0494 MAC=0.2067 MB_time=0.0392s
[DSWD][seed=2026] epoch 035/100 | G=1.0287 D=0.7066 SW=1.0287 DIV=0.0330 MAC=0.1676 MB_time=0.0392s
[DSWD][seed=2026] epoch 036/100 | G=1.0880 D=0.5998 SW=1.0880 DIV=0.0249 MAC=0.1429 MB_time=0.0393s
[DSWD][seed=2026] epoch 037/100 | G=0.8844 D=0.6523 SW=0.8844 DIV=0.0229 MAC=0.1354 MB_time=0.0392s
[DSWD][seed=2026] epoch 038/100 | G=0.8477 D=0.6771 SW=0.8477 DIV=0.0197 MAC=0.1240 MB_time=0.0392s
[DSWD][seed=2026] epoch 039/100 | G=0.7520 D=0.7676 SW=0.7520 DIV=0.0198 MAC=0.1239 MB_time=0.0394s
[DSWD][seed=2026] epoch 040/100 | G=0.7639 D=0.7138 SW=0.7639 DIV=0.0182 MAC=0.1178 MB_time=0.0392s
  eval: {'fid': 124.5876999454162, 'kid_mean': 0.08783376455307007, 'kid_std': 0.0018272493336103067}
[SYNC-RESUME] DSWD seed=2026 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_2026 (count=4)
[SYNC-RESUME] DSWD seed=2026 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_2026 (count=4)
[DSWD][seed=2026] epoch 041/100 | G=0.8569 D=0.6582 SW=0.8569 DIV=0.0203 MAC=0.1251 MB_time=0.0393s
[DSWD][seed=2026] epoch 042/100 | G=0.7130 D=0.6758 SW=0.7130 DIV=0.0177 MAC=0.1149 MB_time=0.0392s
[DSWD][seed=2026] epoch 043/100 | G=2.0944 D=0.2873 SW=2.0944 DIV=0.0285 MAC=0.1482 MB_time=0.0392s
[DSWD][seed=2026] epoch 044/100 | G=3.2950 D=0.1521 SW=3.2950 DIV=0.0802 MAC=0.2722 MB_time=0.0393s
[DSWD][seed=2026] epoch 045/100 | G=1.2231 D=0.5402 SW=1.2231 DIV=0.0433 MAC=0.1931 MB_time=0.0394s
[DSWD][seed=2026] epoch 046/100 | G=1.0359 D=0.5870 SW=1.0359 DIV=0.0287 MAC=0.1518 MB_time=0.0392s
[DSWD][seed=2026] epoch 047/100 | G=0.7920 D=0.6950 SW=0.7920 DIV=0.0226 MAC=0.1317 MB_time=0.0391s
[DSWD][seed=2026] epoch 048/100 | G=1.2890 D=0.3786 SW=1.2890 DIV=0.0256 MAC=0.1418 MB_time=0.0392s
[DSWD][seed=2026] epoch 049/100 | G=0.7361 D=0.8594 SW=0.7361 DIV=0.0220 MAC=0.1297 MB_time=0.0392s
[DSWD][seed=2026] epoch 050/100 | G=1.0110 D=0.4118 SW=1.0110 DIV=0.0201 MAC=0.1226 MB_time=0.0392s
  eval: {'fid': 118.45088706179672, 'kid_mean': 0.08153581857681275, 'kid_std': 0.0014658407646269312}
[SYNC-RESUME] DSWD seed=2026 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_2026 (count=4)
[SYNC-RESUME] DSWD seed=2026 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_2026 (count=4)
[DSWD][seed=2026] epoch 051/100 | G=0.7022 D=0.7666 SW=0.7022 DIV=0.0199 MAC=0.1220 MB_time=0.0392s
[DSWD][seed=2026] epoch 052/100 | G=2.9506 D=0.1074 SW=2.9506 DIV=0.0407 MAC=0.1800 MB_time=0.0394s
[DSWD][seed=2026] epoch 053/100 | G=2.8196 D=0.2720 SW=2.8196 DIV=0.0792 MAC=0.2699 MB_time=0.0393s
[DSWD][seed=2026] epoch 054/100 | G=1.0424 D=0.5074 SW=1.0424 DIV=0.0383 MAC=0.1791 MB_time=0.0392s
[DSWD][seed=2026] epoch 055/100 | G=0.8500 D=0.4755 SW=0.8500 DIV=0.0263 MAC=0.1430 MB_time=0.0392s
[DSWD][seed=2026] epoch 056/100 | G=0.8140 D=0.6145 SW=0.8140 DIV=0.0215 MAC=0.1267 MB_time=0.0393s
[DSWD][seed=2026] epoch 057/100 | G=0.7271 D=0.5399 SW=0.7271 DIV=0.0190 MAC=0.1176 MB_time=0.0394s
[DSWD][seed=2026] epoch 058/100 | G=0.7436 D=0.6129 SW=0.7436 DIV=0.0178 MAC=0.1126 MB_time=0.0392s
[DSWD][seed=2026] epoch 059/100 | G=0.6183 D=0.8420 SW=0.6183 DIV=0.0152 MAC=0.1029 MB_time=0.0392s
[DSWD][seed=2026] epoch 060/100 | G=0.7464 D=0.5234 SW=0.7464 DIV=0.0173 MAC=0.1104 MB_time=0.0392s
  eval: {'fid': 99.06303743300424, 'kid_mean': 0.06278519630432129, 'kid_std': 0.0013195892336919925}
[SYNC-RESUME] DSWD seed=2026 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_2026 (count=4)
[SYNC-RESUME] DSWD seed=2026 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_2026 (count=4)
[DSWD][seed=2026] epoch 061/100 | G=0.6894 D=0.4812 SW=0.6894 DIV=0.0167 MAC=0.1078 MB_time=0.0393s
[DSWD][seed=2026] epoch 062/100 | G=0.5795 D=0.9880 SW=0.5795 DIV=0.0140 MAC=0.0970 MB_time=0.0398s
[DSWD][seed=2026] epoch 063/100 | G=0.7469 D=0.4593 SW=0.7469 DIV=0.0152 MAC=0.1021 MB_time=0.0392s
[DSWD][seed=2026] epoch 064/100 | G=0.8054 D=0.5645 SW=0.8054 DIV=0.0177 MAC=0.1113 MB_time=0.0392s
[DSWD][seed=2026] epoch 065/100 | G=0.6768 D=0.5662 SW=0.6768 DIV=0.0175 MAC=0.1105 MB_time=0.0393s
[DSWD][seed=2026] epoch 066/100 | G=0.8072 D=0.4550 SW=0.8072 DIV=0.0170 MAC=0.1086 MB_time=0.0391s
[DSWD][seed=2026] epoch 067/100 | G=0.6369 D=0.6696 SW=0.6369 DIV=0.0152 MAC=0.1018 MB_time=0.0393s
[DSWD][seed=2026] epoch 068/100 | G=0.8143 D=0.4819 SW=0.8143 DIV=0.0180 MAC=0.1122 MB_time=0.0394s
[DSWD][seed=2026] epoch 069/100 | G=0.7835 D=0.5425 SW=0.7835 DIV=0.0173 MAC=0.1097 MB_time=0.0391s
[DSWD][seed=2026] epoch 070/100 | G=0.9050 D=0.4621 SW=0.9050 DIV=0.0190 MAC=0.1161 MB_time=0.0392s
  eval: {'fid': 91.1530120870728, 'kid_mean': 0.05421516895294189, 'kid_std': 0.0012755967441484654}
[SYNC-RESUME] DSWD seed=2026 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_2026 (count=4)
[SYNC-RESUME] DSWD seed=2026 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_2026 (count=4)
[DSWD][seed=2026] epoch 071/100 | G=0.6736 D=0.5712 SW=0.6736 DIV=0.0170 MAC=0.1082 MB_time=0.0394s
[DSWD][seed=2026] epoch 072/100 | G=0.8585 D=0.3659 SW=0.8585 DIV=0.0179 MAC=0.1118 MB_time=0.0391s
[DSWD][seed=2026] epoch 073/100 | G=0.6902 D=1.0004 SW=0.6902 DIV=0.0171 MAC=0.1088 MB_time=0.0392s
[DSWD][seed=2026] epoch 074/100 | G=1.1040 D=0.4705 SW=1.1040 DIV=0.0144 MAC=0.0978 MB_time=0.0391s
[DSWD][seed=2026] epoch 075/100 | G=2.1327 D=0.0970 SW=2.1327 DIV=0.0460 MAC=0.1960 MB_time=0.0393s
[DSWD][seed=2026] epoch 076/100 | G=0.8450 D=0.4508 SW=0.8450 DIV=0.0270 MAC=0.1421 MB_time=0.0392s
[DSWD][seed=2026] epoch 077/100 | G=0.8437 D=0.3724 SW=0.8437 DIV=0.0209 MAC=0.1215 MB_time=0.0392s
[DSWD][seed=2026] epoch 078/100 | G=0.8009 D=0.5041 SW=0.8009 DIV=0.0196 MAC=0.1167 MB_time=0.0392s
[DSWD][seed=2026] epoch 079/100 | G=0.7933 D=0.5408 SW=0.7933 DIV=0.0187 MAC=0.1132 MB_time=0.0393s
[DSWD][seed=2026] epoch 080/100 | G=0.5563 D=0.5362 SW=0.5563 DIV=0.0147 MAC=0.0988 MB_time=0.0392s
  eval: {'fid': 80.06839471638426, 'kid_mean': 0.04372165203094482, 'kid_std': 0.0011631469801709484}
[SYNC-RESUME] DSWD seed=2026 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_2026 (count=4)
[SYNC-RESUME] DSWD seed=2026 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_2026 (count=4)
[DSWD][seed=2026] epoch 081/100 | G=0.5889 D=0.5972 SW=0.5889 DIV=0.0138 MAC=0.0946 MB_time=0.0392s
[DSWD][seed=2026] epoch 082/100 | G=0.7303 D=0.3194 SW=0.7303 DIV=0.0152 MAC=0.0996 MB_time=0.0392s
[DSWD][seed=2026] epoch 083/100 | G=1.6008 D=0.3205 SW=1.6008 DIV=0.0215 MAC=0.1207 MB_time=0.0393s
[DSWD][seed=2026] epoch 084/100 | G=0.9556 D=0.1521 SW=0.9556 DIV=0.0301 MAC=0.1487 MB_time=0.0393s
[DSWD][seed=2026] epoch 085/100 | G=0.6092 D=0.9272 SW=0.6092 DIV=0.0180 MAC=0.1096 MB_time=0.0393s
[DSWD][seed=2026] epoch 086/100 | G=0.6882 D=0.3805 SW=0.6882 DIV=0.0163 MAC=0.1036 MB_time=0.0392s
[DSWD][seed=2026] epoch 087/100 | G=0.6564 D=0.4634 SW=0.6564 DIV=0.0156 MAC=0.1006 MB_time=0.0393s
[DSWD][seed=2026] epoch 088/100 | G=0.6952 D=0.4557 SW=0.6952 DIV=0.0164 MAC=0.1035 MB_time=0.0393s
[DSWD][seed=2026] epoch 089/100 | G=0.6093 D=0.6910 SW=0.6093 DIV=0.0145 MAC=0.0967 MB_time=0.0394s
[DSWD][seed=2026] epoch 090/100 | G=1.1237 D=0.2351 SW=1.1237 DIV=0.0167 MAC=0.1045 MB_time=0.0392s
  eval: {'fid': 91.00603562387676, 'kid_mean': 0.05240013360977173, 'kid_std': 0.0012869430156556396}
[SYNC-RESUME] DSWD seed=2026 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_2026 (count=4)
[SYNC-RESUME] DSWD seed=2026 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_2026 (count=4)
[DSWD][seed=2026] epoch 091/100 | G=2.1310 D=0.1808 SW=2.1310 DIV=0.0456 MAC=0.1912 MB_time=0.0394s
[DSWD][seed=2026] epoch 092/100 | G=0.7135 D=0.2101 SW=0.7135 DIV=0.0234 MAC=0.1277 MB_time=0.0392s
[DSWD][seed=2026] epoch 093/100 | G=0.7412 D=0.3589 SW=0.7412 DIV=0.0194 MAC=0.1137 MB_time=0.0393s
[DSWD][seed=2026] epoch 094/100 | G=0.6585 D=0.6838 SW=0.6585 DIV=0.0161 MAC=0.1020 MB_time=0.0394s
[DSWD][seed=2026] epoch 095/100 | G=0.5901 D=0.3666 SW=0.5901 DIV=0.0151 MAC=0.0982 MB_time=0.0392s
[DSWD][seed=2026] epoch 096/100 | G=0.6941 D=0.3699 SW=0.6941 DIV=0.0159 MAC=0.1008 MB_time=0.0391s
[DSWD][seed=2026] epoch 097/100 | G=1.6387 D=0.1295 SW=1.6387 DIV=0.0243 MAC=0.1287 MB_time=0.0391s
[DSWD][seed=2026] epoch 098/100 | G=2.0854 D=0.0392 SW=2.0854 DIV=0.0510 MAC=0.2036 MB_time=0.0395s
[DSWD][seed=2026] epoch 099/100 | G=0.9752 D=0.2355 SW=0.9752 DIV=0.0282 MAC=0.1418 MB_time=0.0393s
[DSWD][seed=2026] epoch 100/100 | G=0.8455 D=0.4116 SW=0.8455 DIV=0.0239 MAC=0.1275 MB_time=0.0393s
  eval: {'fid': 57.27362302919613, 'kid_mean': 0.039733030796051026, 'kid_std': 0.0015016201901983336}
[SYNC-RESUME] DSWD seed=2026 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_2026 (count=4)
[SYNC-RESUME] DSWD seed=2026 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_2026 (count=4)
[SYNC-RESUME] DSWD seed=2026 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_2026 (count=5)
[SYNC-FULL:OK] /content/runs_local/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_2026 -> /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_2026 (files_seen=43)
Drive not mounted, so nothing to flush and unmount.
[FLUSH] Drive 已强制同步完成
[DONE] DSWD seed=2026 -> /content/runs_local/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_2026
[INFO] No valid checkpoint found for HDSWD seed=2026; starting fresh.
[HDSWD][seed=2026] epoch 001/100 | G=0.7474 D=2.5572 SW=0.7474 DIV=0.0693 MAC=0.1525 MB_time=0.0358s
[HDSWD][seed=2026] epoch 002/100 | G=0.7064 D=0.7552 SW=0.7064 DIV=0.0670 MAC=0.1505 MB_time=0.0357s
[HDSWD][seed=2026] epoch 003/100 | G=0.4781 D=1.1357 SW=0.4781 DIV=0.0709 MAC=0.1504 MB_time=0.0358s
[HDSWD][seed=2026] epoch 004/100 | G=0.4533 D=1.0253 SW=0.4533 DIV=0.0740 MAC=0.1500 MB_time=0.0355s
[HDSWD][seed=2026] epoch 005/100 | G=0.5385 D=1.0511 SW=0.5385 DIV=0.0833 MAC=0.1516 MB_time=0.0357s
[HDSWD][seed=2026] epoch 006/100 | G=0.6358 D=1.0895 SW=0.6358 DIV=0.0934 MAC=0.1533 MB_time=0.0355s
[HDSWD][seed=2026] epoch 007/100 | G=0.7025 D=0.9786 SW=0.7025 DIV=0.1028 MAC=0.1546 MB_time=0.0358s
[HDSWD][seed=2026] epoch 008/100 | G=0.9289 D=0.9052 SW=0.9289 DIV=0.1222 MAC=0.1588 MB_time=0.0356s
[HDSWD][seed=2026] epoch 009/100 | G=0.9346 D=0.8870 SW=0.9346 DIV=0.1354 MAC=0.1606 MB_time=0.0357s
[HDSWD][seed=2026] epoch 010/100 | G=0.9669 D=0.8545 SW=0.9669 DIV=0.1517 MAC=0.1632 MB_time=0.0355s
  eval: {'fid': 323.11779033820284, 'kid_mean': 0.31772263288497926, 'kid_std': 0.002845711893892344}
[SYNC-RESUME] HDSWD seed=2026 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_2026 (count=4)
[SYNC-RESUME] HDSWD seed=2026 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_2026 (count=4)
[HDSWD][seed=2026] epoch 011/100 | G=0.8845 D=0.9069 SW=0.8845 DIV=0.1443 MAC=0.1619 MB_time=0.0356s
[HDSWD][seed=2026] epoch 012/100 | G=0.6673 D=0.9695 SW=0.6673 DIV=0.1391 MAC=0.1604 MB_time=0.0356s
[HDSWD][seed=2026] epoch 013/100 | G=0.5434 D=0.9645 SW=0.5434 DIV=0.1215 MAC=0.1569 MB_time=0.0356s
[HDSWD][seed=2026] epoch 014/100 | G=0.5596 D=0.9372 SW=0.5596 DIV=0.1119 MAC=0.1540 MB_time=0.0361s
[HDSWD][seed=2026] epoch 015/100 | G=0.4740 D=1.0237 SW=0.4740 DIV=0.1049 MAC=0.1528 MB_time=0.0356s
[HDSWD][seed=2026] epoch 016/100 | G=0.4971 D=0.9371 SW=0.4971 DIV=0.0966 MAC=0.1506 MB_time=0.0360s
[HDSWD][seed=2026] epoch 017/100 | G=0.4893 D=0.9797 SW=0.4893 DIV=0.0923 MAC=0.1495 MB_time=0.0357s
[HDSWD][seed=2026] epoch 018/100 | G=0.5043 D=0.8978 SW=0.5043 DIV=0.0953 MAC=0.1504 MB_time=0.0359s
[HDSWD][seed=2026] epoch 019/100 | G=0.4787 D=0.9483 SW=0.4787 DIV=0.0910 MAC=0.1494 MB_time=0.0355s
[HDSWD][seed=2026] epoch 020/100 | G=0.4805 D=0.9559 SW=0.4805 DIV=0.0888 MAC=0.1487 MB_time=0.0359s
  eval: {'fid': 173.96741271505692, 'kid_mean': 0.14360228776931763, 'kid_std': 0.001812803133580185}
[SYNC-RESUME] HDSWD seed=2026 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_2026 (count=4)
[SYNC-RESUME] HDSWD seed=2026 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_2026 (count=4)
[HDSWD][seed=2026] epoch 021/100 | G=0.4883 D=0.9680 SW=0.4883 DIV=0.0864 MAC=0.1483 MB_time=0.0358s
[HDSWD][seed=2026] epoch 022/100 | G=0.4887 D=0.9084 SW=0.4887 DIV=0.0853 MAC=0.1480 MB_time=0.0355s
[HDSWD][seed=2026] epoch 023/100 | G=0.5404 D=0.8742 SW=0.5404 DIV=0.0900 MAC=0.1493 MB_time=0.0358s
[HDSWD][seed=2026] epoch 024/100 | G=0.6686 D=0.8001 SW=0.6686 DIV=0.0977 MAC=0.1510 MB_time=0.0355s
[HDSWD][seed=2026] epoch 025/100 | G=0.7251 D=0.8053 SW=0.7251 DIV=0.1067 MAC=0.1540 MB_time=0.0356s
[HDSWD][seed=2026] epoch 026/100 | G=0.8885 D=0.6817 SW=0.8885 DIV=0.1245 MAC=0.1576 MB_time=0.0355s
[HDSWD][seed=2026] epoch 027/100 | G=1.0507 D=0.7238 SW=1.0507 DIV=0.1530 MAC=0.1636 MB_time=0.0358s
[HDSWD][seed=2026] epoch 028/100 | G=1.4190 D=0.4990 SW=1.4190 DIV=0.1617 MAC=0.1655 MB_time=0.0355s
[HDSWD][seed=2026] epoch 029/100 | G=1.3193 D=0.7607 SW=1.3193 DIV=0.2250 MAC=0.1777 MB_time=0.0356s
[HDSWD][seed=2026] epoch 030/100 | G=1.0251 D=0.5883 SW=1.0251 DIV=0.1876 MAC=0.1713 MB_time=0.0355s
  eval: {'fid': 156.89049562433587, 'kid_mean': 0.12209970712661743, 'kid_std': 0.0019948126253833223}
[SYNC-RESUME] HDSWD seed=2026 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_2026 (count=4)
[SYNC-RESUME] HDSWD seed=2026 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_2026 (count=4)
[HDSWD][seed=2026] epoch 031/100 | G=0.8215 D=0.6922 SW=0.8215 DIV=0.1580 MAC=0.1653 MB_time=0.0358s
[HDSWD][seed=2026] epoch 032/100 | G=1.0336 D=0.5307 SW=1.0336 DIV=0.1473 MAC=0.1631 MB_time=0.0354s
[HDSWD][seed=2026] epoch 033/100 | G=1.0880 D=0.6330 SW=1.0880 DIV=0.1553 MAC=0.1645 MB_time=0.0357s
[HDSWD][seed=2026] epoch 034/100 | G=0.9489 D=0.6977 SW=0.9489 DIV=0.1582 MAC=0.1652 MB_time=0.0355s

In [27]:
# @title
# Run four structured modes with two switches:
# DSWD (none), HDSWD (projector only), HSW_DSW (slicer only), HSW_HDSWD (both)

cfg = TrainConfig()

cfg.output_root = "/content/runs_local"
cfg.drive_output_root = "/content/drive/MyDrive/cifar10_dsw_runs" if os.path.exists("/content/drive/MyDrive") else "./runs_drive_backup"
cfg.fidelity_cache_root = "/content/fidelity_cache_local"

cfg.p = 2
cfg.seeds = (3,)
cfg.modes = ("DSWD", "HDSWD", "HSW_DSW", "HSW_HDSWD")

cfg.epochs = 100
cfg.eval_every = 10
cfg.sample_every = 5
cfg.run_tag = "bs512_structured_four_modes_v1"

cfg.latent_size = 100
cfg.lr_g = 5e-4
cfg.lr_d = 5e-4
cfg.lr_t = 1e-4

cfg.num_projections = 256
cfg.selector_steps = 1
cfg.use_diversity_reg = True
cfg.diversity_weight = 10.0

cfg.h_num_base = 128
cfg.h_num_bottleneck = 32
cfg.h_base_rank = 512
cfg.h_bottleneck_diversity_weight = 5.0
cfg.h_mix_act = "linear"

cfg.hsw_slicer_dims = (512, 128)
cfg.hsw_slicer_act = "linear"
cfg.hsw_proj_rank = 0

cfg.drive_backup_every = 10
cfg.drive_backup_on_eval = True
cfg.final_full_sync_to_drive = True
cfg.sync_history_on_backup = True
cfg.sync_eval_history_on_backup = True
cfg.sync_samples_on_backup = False
cfg.sync_eval_ckpts_on_backup = False

cfg.resume_if_possible = True
cfg.autoskip_complete = True

print("Experiment root:", experiment_root(cfg))
train_all(cfg)

Experiment root: /content/runs_local/cifar10_dsw_v2/bs512_structured_four_modes_v1
[INFO] No valid checkpoint found for DSWD seed=3; starting fresh.
[DSWD][seed=3] epoch 001/100 | G=1.0014 D=2.5456 SW=1.0014 DIV=0.1374 MAC=0.3608 MB_time=0.0393s
[DSWD][seed=3] epoch 002/100 | G=0.7006 D=0.9333 SW=0.7006 DIV=0.0231 MAC=0.1461 MB_time=0.0393s
[DSWD][seed=3] epoch 003/100 | G=0.8714 D=1.0525 SW=0.8714 DIV=0.0147 MAC=0.1135 MB_time=0.0392s
[DSWD][seed=3] epoch 004/100 | G=1.3840 D=1.0489 SW=1.3840 DIV=0.0270 MAC=0.1549 MB_time=0.0392s
[DSWD][seed=3] epoch 005/100 | G=1.3302 D=0.9907 SW=1.3302 DIV=0.0302 MAC=0.1646 MB_time=0.0392s
[DSWD][seed=3] epoch 006/100 | G=1.5340 D=0.8516 SW=1.5340 DIV=0.0353 MAC=0.1794 MB_time=0.0393s
[DSWD][seed=3] epoch 007/100 | G=1.7381 D=0.7772 SW=1.7381 DIV=0.0410 MAC=0.1944 MB_time=0.0392s
[DSWD][seed=3] epoch 008/100 | G=1.7414 D=0.7031 SW=1.7414 DIV=0.0423 MAC=0.1978 MB_time=0.0393s
[DSWD][seed=3] epoch 009/100 | G=1.7437 D=0.7465 SW=1.7437 DIV=0.0431 MAC=0.1998 MB_time=0.0392s
[DSWD][seed=3] epoch 010/100 | G=1.4881 D=0.7666 SW=1.4881 DIV=0.0391 MAC=0.1898 MB_time=0.0392s
  eval: {'fid': 234.4834904024487, 'kid_mean': 0.20405177116394044, 'kid_std': 0.0019666506426720006}
[SYNC-RESUME] DSWD seed=3 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_3 (count=4)
[SYNC-RESUME] DSWD seed=3 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_3 (count=4)
[DSWD][seed=3] epoch 011/100 | G=1.1148 D=0.8479 SW=1.1148 DIV=0.0303 MAC=0.1654 MB_time=0.0393s
[DSWD][seed=3] epoch 012/100 | G=1.0081 D=0.8623 SW=1.0081 DIV=0.0253 MAC=0.1501 MB_time=0.0392s
[DSWD][seed=3] epoch 013/100 | G=0.9138 D=0.8613 SW=0.9138 DIV=0.0221 MAC=0.1397 MB_time=0.0393s
[DSWD][seed=3] epoch 014/100 | G=0.9314 D=0.8559 SW=0.9314 DIV=0.0227 MAC=0.1414 MB_time=0.0395s
[DSWD][seed=3] epoch 015/100 | G=0.9525 D=0.8070 SW=0.9525 DIV=0.0227 MAC=0.1418 MB_time=0.0393s
[DSWD][seed=3] epoch 016/100 | G=0.8821 D=0.9065 SW=0.8821 DIV=0.0209 MAC=0.1352 MB_time=0.0392s
[DSWD][seed=3] epoch 017/100 | G=0.9375 D=0.7784 SW=0.9375 DIV=0.0214 MAC=0.1372 MB_time=0.0391s
[DSWD][seed=3] epoch 018/100 | G=0.9743 D=0.8065 SW=0.9743 DIV=0.0236 MAC=0.1446 MB_time=0.0392s
[DSWD][seed=3] epoch 019/100 | G=0.9782 D=0.8624 SW=0.9782 DIV=0.0240 MAC=0.1459 MB_time=0.0393s
[DSWD][seed=3] epoch 020/100 | G=0.9842 D=0.7774 SW=0.9842 DIV=0.0214 MAC=0.1366 MB_time=0.0393s
  eval: {'fid': 189.79747259811052, 'kid_mean': 0.15825733423233032, 'kid_std': 0.001528343104729866}
[SYNC-RESUME] DSWD seed=3 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_3 (count=4)
[SYNC-RESUME] DSWD seed=3 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_3 (count=4)
[DSWD][seed=3] epoch 021/100 | G=1.1852 D=0.7294 SW=1.1852 DIV=0.0276 MAC=0.1573 MB_time=0.0392s
[DSWD][seed=3] epoch 022/100 | G=1.3099 D=0.6362 SW=1.3099 DIV=0.0271 MAC=0.1558 MB_time=0.0393s
[DSWD][seed=3] epoch 023/100 | G=1.1108 D=0.6911 SW=1.1108 DIV=0.0303 MAC=0.1653 MB_time=0.0392s
[DSWD][seed=3] epoch 024/100 | G=1.4782 D=0.7495 SW=1.4782 DIV=0.0350 MAC=0.1786 MB_time=0.0391s
[DSWD][seed=3] epoch 025/100 | G=0.9754 D=0.7389 SW=0.9754 DIV=0.0257 MAC=0.1506 MB_time=0.0392s
[DSWD][seed=3] epoch 026/100 | G=1.2456 D=0.6859 SW=1.2456 DIV=0.0247 MAC=0.1469 MB_time=0.0392s
[DSWD][seed=3] epoch 027/100 | G=1.4639 D=0.6352 SW=1.4639 DIV=0.0356 MAC=0.1799 MB_time=0.0391s
[DSWD][seed=3] epoch 028/100 | G=2.3361 D=0.2572 SW=2.3361 DIV=0.0440 MAC=0.1997 MB_time=0.0391s
[DSWD][seed=3] epoch 029/100 | G=1.7799 D=0.5665 SW=1.7799 DIV=0.0563 MAC=0.2287 MB_time=0.0392s
[DSWD][seed=3] epoch 030/100 | G=1.0189 D=0.6739 SW=1.0189 DIV=0.0322 MAC=0.1697 MB_time=0.0392s
  eval: {'fid': 172.8972768919936, 'kid_mean': 0.14233886003494262, 'kid_std': 0.001949855475843025}
[SYNC-RESUME] DSWD seed=3 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_3 (count=4)
[SYNC-RESUME] DSWD seed=3 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_3 (count=4)
[DSWD][seed=3] epoch 031/100 | G=0.9384 D=0.7711 SW=0.9384 DIV=0.0251 MAC=0.1474 MB_time=0.0394s
[DSWD][seed=3] epoch 032/100 | G=0.8234 D=0.7110 SW=0.8234 DIV=0.0204 MAC=0.1306 MB_time=0.0393s
[DSWD][seed=3] epoch 033/100 | G=0.7436 D=0.7379 SW=0.7436 DIV=0.0178 MAC=0.1205 MB_time=0.0392s
[DSWD][seed=3] epoch 034/100 | G=0.8880 D=0.7186 SW=0.8880 DIV=0.0201 MAC=0.1292 MB_time=0.0392s
[DSWD][seed=3] epoch 035/100 | G=0.6222 D=0.8995 SW=0.6222 DIV=0.0173 MAC=0.1179 MB_time=0.0393s
[DSWD][seed=3] epoch 036/100 | G=0.6827 D=0.7248 SW=0.6827 DIV=0.0138 MAC=0.1028 MB_time=0.0392s
[DSWD][seed=3] epoch 037/100 | G=0.8362 D=0.7004 SW=0.8362 DIV=0.0181 MAC=0.1202 MB_time=0.0393s
[DSWD][seed=3] epoch 038/100 | G=0.7204 D=0.6272 SW=0.7204 DIV=0.0168 MAC=0.1150 MB_time=0.0393s
[DSWD][seed=3] epoch 039/100 | G=0.7187 D=0.8503 SW=0.7187 DIV=0.0171 MAC=0.1156 MB_time=0.0393s
[DSWD][seed=3] epoch 040/100 | G=0.8202 D=0.6624 SW=0.8202 DIV=0.0154 MAC=0.1087 MB_time=0.0392s
  eval: {'fid': 138.7927606412299, 'kid_mean': 0.10450154542922974, 'kid_std': 0.0016445594772000454}
[SYNC-RESUME] DSWD seed=3 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_3 (count=4)
[SYNC-RESUME] DSWD seed=3 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_3 (count=4)
[DSWD][seed=3] epoch 041/100 | G=0.6464 D=0.6861 SW=0.6464 DIV=0.0165 MAC=0.1127 MB_time=0.0393s
[DSWD][seed=3] epoch 042/100 | G=0.8301 D=0.6097 SW=0.8301 DIV=0.0171 MAC=0.1149 MB_time=0.0393s
[DSWD][seed=3] epoch 043/100 | G=0.6326 D=0.7728 SW=0.6326 DIV=0.0155 MAC=0.1082 MB_time=0.0392s
[DSWD][seed=3] epoch 044/100 | G=0.6120 D=0.7588 SW=0.6120 DIV=0.0144 MAC=0.1030 MB_time=0.0393s
[DSWD][seed=3] epoch 045/100 | G=0.7057 D=0.6835 SW=0.7057 DIV=0.0147 MAC=0.1041 MB_time=0.0393s
[DSWD][seed=3] epoch 046/100 | G=0.9196 D=0.5322 SW=0.9196 DIV=0.0186 MAC=0.1195 MB_time=0.0393s
[DSWD][seed=3] epoch 047/100 | G=0.6609 D=0.8384 SW=0.6609 DIV=0.0143 MAC=0.1018 MB_time=0.0393s
[DSWD][seed=3] epoch 048/100 | G=3.0146 D=0.2089 SW=3.0146 DIV=0.0428 MAC=0.1841 MB_time=0.0394s
[DSWD][seed=3] epoch 049/100 | G=4.0161 D=0.0358 SW=4.0161 DIV=0.0975 MAC=0.3045 MB_time=0.0392s
[DSWD][seed=3] epoch 050/100 | G=1.5468 D=0.1451 SW=1.5468 DIV=0.0602 MAC=0.2326 MB_time=0.0392s
  eval: {'fid': 166.56504652310264, 'kid_mean': 0.13621989727020264, 'kid_std': 0.0017088478803076426}
[SYNC-RESUME] DSWD seed=3 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_3 (count=4)
[SYNC-RESUME] DSWD seed=3 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_3 (count=4)
[DSWD][seed=3] epoch 051/100 | G=0.9782 D=0.7796 SW=0.9782 DIV=0.0346 MAC=0.1696 MB_time=0.0392s
[DSWD][seed=3] epoch 052/100 | G=0.8990 D=0.5217 SW=0.8990 DIV=0.0244 MAC=0.1381 MB_time=0.0392s
[DSWD][seed=3] epoch 053/100 | G=0.7698 D=0.5888 SW=0.7698 DIV=0.0206 MAC=0.1248 MB_time=0.0392s
[DSWD][seed=3] epoch 054/100 | G=0.6495 D=0.7402 SW=0.6495 DIV=0.0181 MAC=0.1154 MB_time=0.0392s
[DSWD][seed=3] epoch 055/100 | G=0.6733 D=0.5895 SW=0.6733 DIV=0.0163 MAC=0.1082 MB_time=0.0392s
[DSWD][seed=3] epoch 056/100 | G=0.7010 D=0.5763 SW=0.7010 DIV=0.0164 MAC=0.1083 MB_time=0.0392s
[DSWD][seed=3] epoch 057/100 | G=0.6205 D=0.6571 SW=0.6205 DIV=0.0157 MAC=0.1052 MB_time=0.0393s
[DSWD][seed=3] epoch 058/100 | G=0.7306 D=0.6154 SW=0.7306 DIV=0.0154 MAC=0.1042 MB_time=0.0392s
[DSWD][seed=3] epoch 059/100 | G=0.6486 D=0.5373 SW=0.6486 DIV=0.0162 MAC=0.1073 MB_time=0.0392s
[DSWD][seed=3] epoch 060/100 | G=0.7237 D=0.5941 SW=0.7237 DIV=0.0166 MAC=0.1085 MB_time=0.0393s
  eval: {'fid': 98.76147307148415, 'kid_mean': 0.06211293697357178, 'kid_std': 0.001199112798272402}
[SYNC-RESUME] DSWD seed=3 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_3 (count=4)
[SYNC-RESUME] DSWD seed=3 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_3 (count=4)
[DSWD][seed=3] epoch 061/100 | G=0.5821 D=0.8068 SW=0.5821 DIV=0.0150 MAC=0.1020 MB_time=0.0393s
[DSWD][seed=3] epoch 062/100 | G=0.5655 D=0.6664 SW=0.5655 DIV=0.0124 MAC=0.0913 MB_time=0.0394s
[DSWD][seed=3] epoch 063/100 | G=0.6621 D=0.5332 SW=0.6621 DIV=0.0146 MAC=0.1002 MB_time=0.0393s
[DSWD][seed=3] epoch 064/100 | G=0.6910 D=0.6900 SW=0.6910 DIV=0.0143 MAC=0.0998 MB_time=0.0392s
[DSWD][seed=3] epoch 065/100 | G=0.8452 D=0.5001 SW=0.8452 DIV=0.0171 MAC=0.1102 MB_time=0.0392s
[DSWD][seed=3] epoch 066/100 | G=0.5923 D=0.5220 SW=0.5923 DIV=0.0159 MAC=0.1058 MB_time=0.0392s
[DSWD][seed=3] epoch 067/100 | G=0.6149 D=0.6225 SW=0.6149 DIV=0.0154 MAC=0.1027 MB_time=0.0392s
[DSWD][seed=3] epoch 068/100 | G=0.6397 D=0.5842 SW=0.6397 DIV=0.0143 MAC=0.0990 MB_time=0.0392s
[DSWD][seed=3] epoch 069/100 | G=0.5330 D=0.7070 SW=0.5330 DIV=0.0127 MAC=0.0920 MB_time=0.0393s
[DSWD][seed=3] epoch 070/100 | G=0.7271 D=0.5260 SW=0.7271 DIV=0.0138 MAC=0.0971 MB_time=0.0392s
  eval: {'fid': 88.07193028230506, 'kid_mean': 0.05153687000274658, 'kid_std': 0.0009845033387228213}
[SYNC-RESUME] DSWD seed=3 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_3 (count=4)
[SYNC-RESUME] DSWD seed=3 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_3 (count=4)
[DSWD][seed=3] epoch 071/100 | G=2.1096 D=0.0964 SW=2.1096 DIV=0.0292 MAC=0.1472 MB_time=0.0393s
[DSWD][seed=3] epoch 072/100 | G=0.9132 D=0.3741 SW=0.9132 DIV=0.0334 MAC=0.1614 MB_time=0.0394s
[DSWD][seed=3] epoch 073/100 | G=0.6548 D=0.5233 SW=0.6548 DIV=0.0179 MAC=0.1125 MB_time=0.0392s
[DSWD][seed=3] epoch 074/100 | G=0.6150 D=0.5779 SW=0.6150 DIV=0.0161 MAC=0.1049 MB_time=0.0391s
[DSWD][seed=3] epoch 075/100 | G=0.5747 D=0.7311 SW=0.5747 DIV=0.0146 MAC=0.0987 MB_time=0.0392s
[DSWD][seed=3] epoch 076/100 | G=0.5387 D=0.6783 SW=0.5387 DIV=0.0116 MAC=0.0869 MB_time=0.0392s
[DSWD][seed=3] epoch 077/100 | G=0.6523 D=0.5506 SW=0.6523 DIV=0.0132 MAC=0.0934 MB_time=0.0393s
[DSWD][seed=3] epoch 078/100 | G=0.7909 D=0.4673 SW=0.7909 DIV=0.0157 MAC=0.1031 MB_time=0.0392s
[DSWD][seed=3] epoch 079/100 | G=0.5684 D=0.4666 SW=0.5684 DIV=0.0148 MAC=0.1000 MB_time=0.0392s
[DSWD][seed=3] epoch 080/100 | G=0.7153 D=0.5731 SW=0.7153 DIV=0.0159 MAC=0.1038 MB_time=0.0393s
  eval: {'fid': 79.70838780319912, 'kid_mean': 0.042830610275268556, 'kid_std': 0.000944620281183908}
[SYNC-RESUME] DSWD seed=3 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_3 (count=4)
[SYNC-RESUME] DSWD seed=3 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_3 (count=4)
[DSWD][seed=3] epoch 081/100 | G=0.6634 D=0.4696 SW=0.6634 DIV=0.0151 MAC=0.1005 MB_time=0.0394s
[DSWD][seed=3] epoch 082/100 | G=0.5845 D=0.4929 SW=0.5845 DIV=0.0138 MAC=0.0952 MB_time=0.0393s
[DSWD][seed=3] epoch 083/100 | G=0.6462 D=0.4440 SW=0.6462 DIV=0.0144 MAC=0.0974 MB_time=0.0393s
[DSWD][seed=3] epoch 084/100 | G=2.2689 D=0.0439 SW=2.2689 DIV=0.0359 MAC=0.1645 MB_time=0.0392s
[DSWD][seed=3] epoch 085/100 | G=2.4904 D=0.0162 SW=2.4904 DIV=0.0624 MAC=0.2350 MB_time=0.0394s
[DSWD][seed=3] epoch 086/100 | G=2.0487 D=0.0408 SW=2.0487 DIV=0.0566 MAC=0.2221 MB_time=0.0392s
[DSWD][seed=3] epoch 087/100 | G=1.1702 D=0.0662 SW=1.1702 DIV=0.0375 MAC=0.1732 MB_time=0.0392s
[DSWD][seed=3] epoch 088/100 | G=1.0404 D=0.9259 SW=1.0404 DIV=0.0300 MAC=0.1504 MB_time=0.0393s
[DSWD][seed=3] epoch 089/100 | G=0.7611 D=0.4797 SW=0.7611 DIV=0.0203 MAC=0.1191 MB_time=0.0393s
[DSWD][seed=3] epoch 090/100 | G=0.6757 D=0.5449 SW=0.6757 DIV=0.0174 MAC=0.1084 MB_time=0.0393s
  eval: {'fid': 81.50507217036159, 'kid_mean': 0.045854580402374265, 'kid_std': 0.0010037668254439872}
[SYNC-RESUME] DSWD seed=3 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_3 (count=4)
[SYNC-RESUME] DSWD seed=3 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_3 (count=4)
[DSWD][seed=3] epoch 091/100 | G=0.6618 D=0.4932 SW=0.6618 DIV=0.0158 MAC=0.1026 MB_time=0.0393s
[DSWD][seed=3] epoch 092/100 | G=0.6380 D=0.4654 SW=0.6380 DIV=0.0154 MAC=0.1009 MB_time=0.0392s
[DSWD][seed=3] epoch 093/100 | G=0.6366 D=0.4242 SW=0.6366 DIV=0.0152 MAC=0.1000 MB_time=0.0392s
[DSWD][seed=3] epoch 094/100 | G=0.6007 D=0.4266 SW=0.6007 DIV=0.0138 MAC=0.0946 MB_time=0.0392s
[DSWD][seed=3] epoch 095/100 | G=0.6290 D=0.4393 SW=0.6290 DIV=0.0142 MAC=0.0961 MB_time=0.0392s
[DSWD][seed=3] epoch 096/100 | G=0.6568 D=0.4137 SW=0.6568 DIV=0.0152 MAC=0.0999 MB_time=0.0396s
[DSWD][seed=3] epoch 097/100 | G=0.6115 D=0.4720 SW=0.6115 DIV=0.0142 MAC=0.0963 MB_time=0.0396s
[DSWD][seed=3] epoch 098/100 | G=0.8054 D=0.2967 SW=0.8054 DIV=0.0167 MAC=0.1054 MB_time=0.0392s
[DSWD][seed=3] epoch 099/100 | G=0.4066 D=2.2299 SW=0.4066 DIV=0.0111 MAC=0.0839 MB_time=0.0394s
[DSWD][seed=3] epoch 100/100 | G=0.4827 D=0.6402 SW=0.4827 DIV=0.0082 MAC=0.0721 MB_time=0.0394s
  eval: {'fid': 53.32128249492621, 'kid_mean': 0.036474723815917966, 'kid_std': 0.0014254540401087792}
[SYNC-RESUME] DSWD seed=3 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_3 (count=4)
[SYNC-RESUME] DSWD seed=3 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_3 (count=4)
[SYNC-RESUME] DSWD seed=3 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_3 (count=5)
[SYNC-FULL:OK] /content/runs_local/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_3 -> /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_3 (files_seen=43)
Drive not mounted, so nothing to flush and unmount.
[FLUSH] Drive 已强制同步完成
[DONE] DSWD seed=3 -> /content/runs_local/cifar10_dsw_v2/bs512_structured_four_modes_v1/DSWD/seed_3
[INFO] No valid checkpoint found for HDSWD seed=3; starting fresh.
[HDSWD][seed=3] epoch 001/100 | G=0.8716 D=2.8837 SW=0.8716 DIV=0.0742 MAC=0.1554 MB_time=0.0362s
[HDSWD][seed=3] epoch 002/100 | G=0.5758 D=0.8063 SW=0.5758 DIV=0.0711 MAC=0.1528 MB_time=0.0358s
[HDSWD][seed=3] epoch 003/100 | G=0.5765 D=1.0631 SW=0.5765 DIV=0.0730 MAC=0.1518 MB_time=0.0360s
[HDSWD][seed=3] epoch 004/100 | G=0.6318 D=1.0262 SW=0.6318 DIV=0.0797 MAC=0.1524 MB_time=0.0358s
[HDSWD][seed=3] epoch 005/100 | G=0.6208 D=1.0644 SW=0.6208 DIV=0.0948 MAC=0.1549 MB_time=0.0356s
[HDSWD][seed=3] epoch 006/100 | G=0.7043 D=0.9503 SW=0.7043 DIV=0.1019 MAC=0.1559 MB_time=0.0356s
[HDSWD][seed=3] epoch 007/100 | G=0.8166 D=0.8647 SW=0.8166 DIV=0.1164 MAC=0.1584 MB_time=0.0358s
[HDSWD][seed=3] epoch 008/100 | G=0.8975 D=0.8984 SW=0.8975 DIV=0.1344 MAC=0.1611 MB_time=0.0356s
[HDSWD][seed=3] epoch 009/100 | G=0.8838 D=0.8602 SW=0.8838 DIV=0.1347 MAC=0.1605 MB_time=0.0358s
[HDSWD][seed=3] epoch 010/100 | G=0.8488 D=0.9177 SW=0.8488 DIV=0.1447 MAC=0.1622 MB_time=0.0357s
  eval: {'fid': 228.72805995418292, 'kid_mean': 0.19791127920150756, 'kid_std': 0.0019598574662796067}
[SYNC-RESUME] HDSWD seed=3 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_3 (count=4)
[SYNC-RESUME] HDSWD seed=3 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_3 (count=4)
[HDSWD][seed=3] epoch 011/100 | G=0.7116 D=0.9461 SW=0.7116 DIV=0.1420 MAC=0.1614 MB_time=0.0356s
[HDSWD][seed=3] epoch 012/100 | G=0.6000 D=1.0231 SW=0.6000 DIV=0.1322 MAC=0.1592 MB_time=0.0358s
[HDSWD][seed=3] epoch 013/100 | G=0.5443 D=0.9881 SW=0.5443 DIV=0.1154 MAC=0.1552 MB_time=0.0356s
[HDSWD][seed=3] epoch 014/100 | G=0.5293 D=0.9606 SW=0.5293 DIV=0.1046 MAC=0.1525 MB_time=0.0356s
[HDSWD][seed=3] epoch 015/100 | G=0.4994 D=0.9387 SW=0.4994 DIV=0.0995 MAC=0.1516 MB_time=0.0357s
[HDSWD][seed=3] epoch 016/100 | G=0.4503 D=1.0636 SW=0.4503 DIV=0.0937 MAC=0.1498 MB_time=0.0357s
[HDSWD][seed=3] epoch 017/100 | G=0.4491 D=0.9820 SW=0.4491 DIV=0.0910 MAC=0.1494 MB_time=0.0356s
[HDSWD][seed=3] epoch 018/100 | G=0.4860 D=1.0298 SW=0.4860 DIV=0.0917 MAC=0.1493 MB_time=0.0357s
[HDSWD][seed=3] epoch 019/100 | G=0.4390 D=1.0981 SW=0.4390 DIV=0.0878 MAC=0.1484 MB_time=0.0356s
[HDSWD][seed=3] epoch 020/100 | G=0.4627 D=0.9467 SW=0.4627 DIV=0.0843 MAC=0.1474 MB_time=0.0358s
  eval: {'fid': 197.97437412243335, 'kid_mean': 0.1658816933631897, 'kid_std': 0.0018604050307863172}
[SYNC-RESUME] HDSWD seed=3 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_3 (count=4)
[SYNC-RESUME] HDSWD seed=3 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_3 (count=4)
[HDSWD][seed=3] epoch 021/100 | G=0.5673 D=0.9410 SW=0.5673 DIV=0.0953 MAC=0.1503 MB_time=0.0358s
[HDSWD][seed=3] epoch 022/100 | G=0.5832 D=0.9589 SW=0.5832 DIV=0.0948 MAC=0.1498 MB_time=0.0355s
[HDSWD][seed=3] epoch 023/100 | G=0.6575 D=0.8964 SW=0.6575 DIV=0.1064 MAC=0.1528 MB_time=0.0356s
[HDSWD][seed=3] epoch 024/100 | G=0.8479 D=0.7804 SW=0.8479 DIV=0.1122 MAC=0.1541 MB_time=0.0355s
[HDSWD][seed=3] epoch 025/100 | G=0.6131 D=0.9509 SW=0.6131 DIV=0.1206 MAC=0.1562 MB_time=0.0359s
[HDSWD][seed=3] epoch 026/100 | G=0.8530 D=0.7436 SW=0.8530 DIV=0.1245 MAC=0.1574 MB_time=0.0355s
[HDSWD][seed=3] epoch 027/100 | G=0.9837 D=0.8043 SW=0.9837 DIV=0.1377 MAC=0.1605 MB_time=0.0359s
[HDSWD][seed=3] epoch 028/100 | G=0.7513 D=0.8944 SW=0.7513 DIV=0.1480 MAC=0.1627 MB_time=0.0356s
[HDSWD][seed=3] epoch 029/100 | G=0.7329 D=0.7962 SW=0.7329 DIV=0.1216 MAC=0.1572 MB_time=0.0357s
[HDSWD][seed=3] epoch 030/100 | G=0.7873 D=0.7966 SW=0.7873 DIV=0.1280 MAC=0.1587 MB_time=0.0359s
  eval: {'fid': 177.76515901435636, 'kid_mean': 0.15266096591949463, 'kid_std': 0.0016803257502031456}
[SYNC-RESUME] HDSWD seed=3 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_3 (count=4)
[SYNC-RESUME] HDSWD seed=3 copied sparse artifacts to /content/drive/MyDrive/cifar10_dsw_runs/cifar10_dsw_v2/bs512_structured_four_modes_v1/HDSWD/seed_3 (count=4)
[HDSWD][seed=3] epoch 031/100 | G=0.7644 D=0.7183 SW=0.7644 DIV=0.1322 MAC=0.1597 MB_time=0.0358s
[HDSWD][seed=3] epoch 032/100 | G=0.7331 D=0.8050 SW=0.7331 DIV=0.1166 MAC=0.1563 MB_time=0.0358s
[HDSWD][seed=3] epoch 033/100 | G=0.8008 D=0.5886 SW=0.8008 DIV=0.1258 MAC=0.1587 MB_time=0.0357s
[HDSWD][seed=3] epoch 034/100 | G=2.9697 D=0.0587 SW=2.9697 DIV=0.2451 MAC=0.1801 MB_time=0.0359s
[HDSWD][seed=3] epoch 035/100 | G=3.0968 D=0.0418 SW=3.0968 DIV=0.3784 MAC=0.2008 MB_time=0.0355s
[HDSWD][seed=3] epoch 036/100 | G=0.7217 D=1.0996 SW=0.7217 DIV=0.3183 MAC=0.1929 MB_time=0.0359s
[HDSWD][seed=3] epoch 037/100 | G=0.7755 D=0.8172 SW=0.7755 DIV=0.1895 MAC=0.1718 MB_time=0.0359s
[HDSWD][seed=3] epoch 038/100 | G=0.6838 D=0.7470 SW=0.6838 DIV=0.1371 MAC=0.1610 MB_time=0.0359s
[HDSWD][seed=3] epoch 039/100 | G=0.6140 D=0.8084 SW=0.6140 DIV=0.1115 MAC=0.1554 MB_time=0.0356s
[HDSWD][seed=3] epoch 040/100 | G=0.6719 D=0.7234 SW=0.6719 DIV=0.1092 MAC=0.1549 MB_time=0.0357s

In [28]:
# @title
# Summarize results (best checkpoint and final epoch)
from pathlib import Path
import pandas as pd

base = experiment_root(cfg)
rows_best = []
rows_final = []

for mode_dir in base.iterdir():
    if not mode_dir.is_dir():
        continue
    for seed_dir in mode_dir.iterdir():
        eval_csv = seed_dir / "logs" / "eval_history.csv"
        if not eval_csv.exists():
            continue
        df = pd.read_csv(eval_csv)
        if len(df) == 0:
            continue

        best = df.loc[df["fid"].idxmin()].copy()
        final = df.sort_values("epoch").iloc[-1].copy()

        best["seed"] = seed_dir.name
        final["seed"] = seed_dir.name
        rows_best.append(best)
        rows_final.append(final)

best_df = pd.DataFrame(rows_best).sort_values("fid").reset_index(drop=True)
final_df = pd.DataFrame(rows_final).sort_values("fid").reset_index(drop=True)

print("=== Best over training ===")
display(best_df)

print("\n=== Final epoch ===")
display(final_df)

=== Best over training ===

    epoch       seed       mode        fid  kid_mean   kid_std
0     100     seed_3       DSWD  53.321282  0.036475  0.001425
1     100    seed_42    HSW_DSW  54.988746  0.037053  0.001283
2     100     seed_3  HSW_HDSWD  56.851530  0.040016  0.001260
3     100  seed_2026       DSWD  57.273623  0.039733  0.001502
4     100  seed_2026  HSW_HDSWD  58.402174  0.041671  0.001408
5     100     seed_3      HDSWD  58.411206  0.041711  0.001530
6     100    seed_42      HDSWD  58.694691  0.041272  0.001359
7     100   seed_123       DSWD  58.962416  0.041094  0.001454
8     100    seed_40    HSW_DSW  59.035532  0.041350  0.001281
9     100    seed_42  HSW_HDSWD  59.506497  0.042151  0.001299
10    100    seed_40       DSWD  62.489474  0.043350  0.001262
11    100    seed_42       DSWD  62.531611  0.043902  0.001393
12    100    seed_40      HDSWD  64.040835  0.046364  0.001712
13    100    seed_40  HSW_HDSWD  65.237021  0.048917  0.001435
14    100     seed_3    HSW_DSW  65.311740  0.048392  0.001415
15    100   seed_123    HSW_DSW  71.982316  0.054797  0.001448
16    100   seed_123  HSW_HDSWD  77.625569  0.057942  0.001832
17    100  seed_2026    HSW_DSW  80.700080  0.065117  0.001582
18     90  seed_2026      HDSWD  81.415610  0.044364  0.001003
19     90   seed_123      HDSWD  83.118562  0.044150  0.001078

=== Final epoch ===

    epoch       seed       mode         fid  kid_mean   kid_std
0     100     seed_3       DSWD   53.321282  0.036475  0.001425
1     100    seed_42    HSW_DSW   54.988746  0.037053  0.001283
2     100     seed_3  HSW_HDSWD   56.851530  0.040016  0.001260
3     100  seed_2026       DSWD   57.273623  0.039733  0.001502
4     100  seed_2026  HSW_HDSWD   58.402174  0.041671  0.001408
5     100     seed_3      HDSWD   58.411206  0.041711  0.001530
6     100    seed_42      HDSWD   58.694691  0.041272  0.001359
7     100   seed_123       DSWD   58.962416  0.041094  0.001454
8     100    seed_40    HSW_DSW   59.035532  0.041350  0.001281
9     100    seed_42  HSW_HDSWD   59.506497  0.042151  0.001299
10    100    seed_40       DSWD   62.489474  0.043350  0.001262
11    100    seed_42       DSWD   62.531611  0.043902  0.001393
12    100    seed_40      HDSWD   64.040835  0.046364  0.001712
13    100    seed_40  HSW_HDSWD   65.237021  0.048917  0.001435
14    100     seed_3    HSW_DSW   65.311740  0.048392  0.001415
15    100   seed_123    HSW_DSW   71.982316  0.054797  0.001448
16    100   seed_123  HSW_HDSWD   77.625569  0.057942  0.001832
17    100  seed_2026    HSW_DSW   80.700080  0.065117  0.001582
18    100  seed_2026      HDSWD   87.240681  0.070478  0.001666
19    100   seed_123      HDSWD  249.245444  0.224762  0.002766